ALTER TABLE organizations
ADD COLUMN IF NOT EXISTS balance_due NUMERIC(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS gross_markup NUMERIC(5, 2);

ALTER TABLE offices
ADD COLUMN IF NOT EXISTS balance_due NUMERIC(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS gross_markup NUMERIC(5, 2);