// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: available_plans_snapshots_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldAvailablePlansSnapshots = `-- name: DeleteOldAvailablePlansSnapshots :exec
DELETE FROM available_plans_snapshots
where created_at < $1
`

func (q *Queries) DeleteOldAvailablePlansSnapshots(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldAvailablePlansSnapshots, createdAt)
	return err
}

const getSnapshotByID = `-- name: GetSnapshotByID :one
SELECT id, created_at, plans
FROM available_plans_snapshots
WHERE id = $1
`

func (q *Queries) GetSnapshotByID(ctx context.Context, id int64) (AvailablePlansSnapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshotByID, id)
	var i AvailablePlansSnapshot
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Plans)
	return i, err
}

const insertAvailablePlansSnapshot = `-- name: InsertAvailablePlansSnapshot :one
INSERT INTO available_plans_snapshots (plans)
VALUES ($1)
RETURNING id
`

func (q *Queries) InsertAvailablePlansSnapshot(ctx context.Context, plans []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertAvailablePlansSnapshot, plans)
	var id int64
	err := row.Scan(&id)
	return id, err
}
