// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: available_plans_snapshots_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldAvailablePlansSnapshots = `-- name: DeleteOldAvailablePlansSnapshots :exec
DELETE FROM available_plans_snapshots
where created_at < $1
`

func (q *Queries) DeleteOldAvailablePlansSnapshots(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldAvailablePlansSnapshots, createdAt)
	return err
}

const deleteSnapshotByID = `-- name: DeleteSnapshotByID :exec
DELETE FROM available_plans_snapshots WHERE ID = $1
`

func (q *Queries) DeleteSnapshotByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSnapshotByID, id)
	return err
}

const getSnapshotByID = `-- name: GetSnapshotByID :one
SELECT id, created_at, driver_age, pickup_date, pickup_time, return_date, return_time, country_code, plans
FROM available_plans_snapshots
WHERE id = $1
`

func (q *Queries) GetSnapshotByID(ctx context.Context, id int64) (AvailablePlansSnapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshotByID, id)
	var i AvailablePlansSnapshot
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.DriverAge,
		&i.PickupDate,
		&i.PickupTime,
		&i.ReturnDate,
		&i.ReturnTime,
		&i.CountryCode,
		&i.Plans,
	)
	return i, err
}

const insertAvailablePlansSnapshot = `-- name: InsertAvailablePlansSnapshot :one
INSERT INTO available_plans_snapshots (driver_age, pickup_date, pickup_time, return_date, return_time, country_code, plans)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertAvailablePlansSnapshotParams struct {
	DriverAge   string
	PickupDate  string
	PickupTime  string
	ReturnDate  string
	ReturnTime  string
	CountryCode string
	Plans       []byte
}

func (q *Queries) InsertAvailablePlansSnapshot(ctx context.Context, arg InsertAvailablePlansSnapshotParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAvailablePlansSnapshot,
		arg.DriverAge,
		arg.PickupDate,
		arg.PickupTime,
		arg.ReturnDate,
		arg.ReturnTime,
		arg.CountryCode,
		arg.Plans,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
