// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: currencies_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCurrency = `-- name: CreateCurrency :one
INSERT INTO currencies (currency_code, currency_iso_name, rate, created_at, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, currency_code, currency_iso_name, rate, created_at, updated_at
`

type CreateCurrencyParams struct {
	CurrencyCode    string
	CurrencyIsoName string
	Rate            pgtype.Numeric
}

func (q *Queries) CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error) {
	row := q.db.QueryRow(ctx, createCurrency, arg.CurrencyCode, arg.CurrencyIsoName, arg.Rate)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.CurrencyCode,
		&i.CurrencyIsoName,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCurrency = `-- name: DeleteCurrency :exec
DELETE FROM currencies
WHERE id = $1
`

func (q *Queries) DeleteCurrency(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCurrency, id)
	return err
}

const findCurrencyByISOName = `-- name: FindCurrencyByISOName :one
SELECT id, currency_code, currency_iso_name, rate, created_at, updated_at
FROM currencies
WHERE currency_iso_name = $1
`

func (q *Queries) FindCurrencyByISOName(ctx context.Context, currencyIsoName string) (Currency, error) {
	row := q.db.QueryRow(ctx, findCurrencyByISOName, currencyIsoName)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.CurrencyCode,
		&i.CurrencyIsoName,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT id, currency_code, currency_iso_name, rate, created_at, updated_at
FROM currencies
ORDER BY created_at DESC
`

func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Currency
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.ID,
			&i.CurrencyCode,
			&i.CurrencyIsoName,
			&i.Rate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurrency = `-- name: UpdateCurrency :one
UPDATE currencies
SET currency_code     = COALESCE($1, currency_code),
    currency_iso_name = COALESCE($2, currency_iso_name),
    rate              = COALESCE($3, rate),
    updated_at        = CURRENT_TIMESTAMP
WHERE id = $4
RETURNING id, currency_code, currency_iso_name, rate, created_at, updated_at
`

type UpdateCurrencyParams struct {
	CurrencyCode    *string
	CurrencyIsoName *string
	Rate            pgtype.Numeric
	ID              int32
}

func (q *Queries) UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error) {
	row := q.db.QueryRow(ctx, updateCurrency,
		arg.CurrencyCode,
		arg.CurrencyIsoName,
		arg.Rate,
		arg.ID,
	)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.CurrencyCode,
		&i.CurrencyIsoName,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
