// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hertz_markup_rates_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHertzMarkupRate = `-- name: DeleteHertzMarkupRate :one
DELETE FROM hertz_markup_rates
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteHertzMarkupRate(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteHertzMarkupRate, id)
	err := row.Scan(&id)
	return id, err
}

const getHertzMarkupRates = `-- name: GetHertzMarkupRates :many
SELECT car_group, brand, mark_up_gross, mark_up_net
FROM hertz_markup_rates
WHERE country = $1
  AND pickup_date_from <= $2::date
  AND pickup_date_to >= $2::date
  AND num_of_rental_days_from <= $3::int
  AND num_of_rental_days_to >= $3::int
  AND brand = ANY($4::text[])
  AND car_group = ANY($5::text[])
`

type GetHertzMarkupRatesParams struct {
	Country    string
	PickupDate pgtype.Date
	RentalDays int32
	Brands     []string
	CarGroups  []string
}

type GetHertzMarkupRatesRow struct {
	CarGroup    string
	Brand       string
	MarkUpGross float64
	MarkUpNet   float64
}

// Used by the markup logic to fetch rates for a given search.
func (q *Queries) GetHertzMarkupRates(ctx context.Context, arg GetHertzMarkupRatesParams) ([]GetHertzMarkupRatesRow, error) {
	rows, err := q.db.Query(ctx, getHertzMarkupRates,
		arg.Country,
		arg.PickupDate,
		arg.RentalDays,
		arg.Brands,
		arg.CarGroups,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHertzMarkupRatesRow
	for rows.Next() {
		var i GetHertzMarkupRatesRow
		if err := rows.Scan(
			&i.CarGroup,
			&i.Brand,
			&i.MarkUpGross,
			&i.MarkUpNet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHertzMarkupRate = `-- name: InsertHertzMarkupRate :one
INSERT INTO hertz_markup_rates (
    country, brand, pickup_date_from, pickup_date_to,
    car_group, num_of_rental_days_from, num_of_rental_days_to,
    mark_up_gross, mark_up_net
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, country, brand, pickup_date_from, pickup_date_to, car_group, num_of_rental_days_from, num_of_rental_days_to, mark_up_gross, mark_up_net, created_at, updated_at
`

type InsertHertzMarkupRateParams struct {
	Country             string
	Brand               string
	PickupDateFrom      pgtype.Date
	PickupDateTo        pgtype.Date
	CarGroup            string
	NumOfRentalDaysFrom int32
	NumOfRentalDaysTo   int32
	MarkUpGross         float64
	MarkUpNet           float64
}

func (q *Queries) InsertHertzMarkupRate(ctx context.Context, arg InsertHertzMarkupRateParams) (HertzMarkupRate, error) {
	row := q.db.QueryRow(ctx, insertHertzMarkupRate,
		arg.Country,
		arg.Brand,
		arg.PickupDateFrom,
		arg.PickupDateTo,
		arg.CarGroup,
		arg.NumOfRentalDaysFrom,
		arg.NumOfRentalDaysTo,
		arg.MarkUpGross,
		arg.MarkUpNet,
	)
	var i HertzMarkupRate
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.Brand,
		&i.PickupDateFrom,
		&i.PickupDateTo,
		&i.CarGroup,
		&i.NumOfRentalDaysFrom,
		&i.NumOfRentalDaysTo,
		&i.MarkUpGross,
		&i.MarkUpNet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHertzMarkupRates = `-- name: ListHertzMarkupRates :many
SELECT id, country, brand, pickup_date_from, pickup_date_to, car_group, num_of_rental_days_from, num_of_rental_days_to, mark_up_gross, mark_up_net, created_at, updated_at
FROM hertz_markup_rates
WHERE ($1::text IS NULL OR country = $1)
  AND ($2::text IS NULL OR brand = $2)
  AND ($3::text IS NULL OR car_group = $3)
ORDER BY
  CASE WHEN $4::text = 'country' AND $5::text = 'asc' THEN country END ASC,
  CASE WHEN $4::text = 'country' AND $5::text = 'desc' THEN country END DESC,
  CASE WHEN $4::text = 'brand' AND $5::text = 'asc' THEN brand END ASC,
  CASE WHEN $4::text = 'brand' AND $5::text = 'desc' THEN brand END DESC,
  CASE WHEN $4::text = 'car_group' AND $5::text = 'asc' THEN car_group END ASC,
  CASE WHEN $4::text = 'car_group' AND $5::text = 'desc' THEN car_group END DESC,
  CASE WHEN $4::text = 'pickup_date_from' AND $5::text = 'asc' THEN pickup_date_from END ASC,
  CASE WHEN $4::text = 'pickup_date_from' AND $5::text = 'desc' THEN pickup_date_from END DESC,
  CASE WHEN $4::text = 'num_of_rental_days_from' AND $5::text = 'asc' THEN num_of_rental_days_from END ASC,
  CASE WHEN $4::text = 'num_of_rental_days_from' AND $5::text = 'desc' THEN num_of_rental_days_from END DESC,
  id ASC
LIMIT $7::int
OFFSET $6::int
`

type ListHertzMarkupRatesParams struct {
	Country     *string
	Brand       *string
	CarGroup    *string
	SortField   string
	SortDir     string
	QueryOffset int32
	QueryLimit  int32
}

// Admin listing with pagination, optional filtering, and sorting.
func (q *Queries) ListHertzMarkupRates(ctx context.Context, arg ListHertzMarkupRatesParams) ([]HertzMarkupRate, error) {
	rows, err := q.db.Query(ctx, listHertzMarkupRates,
		arg.Country,
		arg.Brand,
		arg.CarGroup,
		arg.SortField,
		arg.SortDir,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HertzMarkupRate
	for rows.Next() {
		var i HertzMarkupRate
		if err := rows.Scan(
			&i.ID,
			&i.Country,
			&i.Brand,
			&i.PickupDateFrom,
			&i.PickupDateTo,
			&i.CarGroup,
			&i.NumOfRentalDaysFrom,
			&i.NumOfRentalDaysTo,
			&i.MarkUpGross,
			&i.MarkUpNet,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHertzMarkupRate = `-- name: UpdateHertzMarkupRate :one
UPDATE hertz_markup_rates
SET country = $2,
    brand = $3,
    pickup_date_from = $4,
    pickup_date_to = $5,
    car_group = $6,
    num_of_rental_days_from = $7,
    num_of_rental_days_to = $8,
    mark_up_gross = $9,
    mark_up_net = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, country, brand, pickup_date_from, pickup_date_to, car_group, num_of_rental_days_from, num_of_rental_days_to, mark_up_gross, mark_up_net, created_at, updated_at
`

type UpdateHertzMarkupRateParams struct {
	ID                  int64
	Country             string
	Brand               string
	PickupDateFrom      pgtype.Date
	PickupDateTo        pgtype.Date
	CarGroup            string
	NumOfRentalDaysFrom int32
	NumOfRentalDaysTo   int32
	MarkUpGross         float64
	MarkUpNet           float64
}

func (q *Queries) UpdateHertzMarkupRate(ctx context.Context, arg UpdateHertzMarkupRateParams) (HertzMarkupRate, error) {
	row := q.db.QueryRow(ctx, updateHertzMarkupRate,
		arg.ID,
		arg.Country,
		arg.Brand,
		arg.PickupDateFrom,
		arg.PickupDateTo,
		arg.CarGroup,
		arg.NumOfRentalDaysFrom,
		arg.NumOfRentalDaysTo,
		arg.MarkUpGross,
		arg.MarkUpNet,
	)
	var i HertzMarkupRate
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.Brand,
		&i.PickupDateFrom,
		&i.PickupDateTo,
		&i.CarGroup,
		&i.NumOfRentalDaysFrom,
		&i.NumOfRentalDaysTo,
		&i.MarkUpGross,
		&i.MarkUpNet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
