// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLocationByID = `-- name: DeleteLocationByID :exec
DELETE FROM locations
WHERE id = $1
`

func (q *Queries) DeleteLocationByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLocationByID, id)
	return err
}

const getLocationByBrokerLocationID = `-- name: GetLocationByBrokerLocationID :one
SELECT l.id, l.country, l.country_code, l.city, l.name, l.iata, l.created_at, l.updated_at, l.is_airport
FROM locations l
JOIN location_broker_codes lbc ON lbc.location_id = l.id
WHERE lbc.broker_location_id = $1
LIMIT 1
`

func (q *Queries) GetLocationByBrokerLocationID(ctx context.Context, brokerLocationID string) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByBrokerLocationID, brokerLocationID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.CountryCode,
		&i.City,
		&i.Name,
		&i.Iata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAirport,
	)
	return i, err
}

const getLocationById = `-- name: GetLocationById :one
SELECT id, country, country_code, city, name, iata, created_at, updated_at, is_airport
FROM locations
WHERE id = $1
`

func (q *Queries) GetLocationById(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationById, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.CountryCode,
		&i.City,
		&i.Name,
		&i.Iata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAirport,
	)
	return i, err
}

const getLocationIDByBrokerCode = `-- name: GetLocationIDByBrokerCode :one
SELECT lbc.location_id
FROM location_broker_codes lbc
WHERE lbc.broker = $1::broker
  AND lbc.broker_location_id = $2
  AND lbc.enabled = TRUE
LIMIT 1
`

type GetLocationIDByBrokerCodeParams struct {
	Broker           Broker
	BrokerLocationID string
}

func (q *Queries) GetLocationIDByBrokerCode(ctx context.Context, arg GetLocationIDByBrokerCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getLocationIDByBrokerCode, arg.Broker, arg.BrokerLocationID)
	var location_id int64
	err := row.Scan(&location_id)
	return location_id, err
}

const insertLocation = `-- name: InsertLocation :one
INSERT INTO locations (country, country_code, city, name, iata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, country, country_code, city, name, iata, created_at, updated_at, is_airport
`

type InsertLocationParams struct {
	Country     string
	CountryCode string
	City        *string
	Name        string
	Iata        *string
}

func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, insertLocation,
		arg.Country,
		arg.CountryCode,
		arg.City,
		arg.Name,
		arg.Iata,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.CountryCode,
		&i.City,
		&i.Name,
		&i.Iata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAirport,
	)
	return i, err
}

const insertManyLocation = `-- name: InsertManyLocation :many
INSERT INTO locations (country, country_code, city, name, iata)
SELECT
  NULLIF(unnest($1::text[]), '')::text,
  NULLIF(unnest($2::text[]), '')::text,
  NULLIF(unnest($3::text[]), '')::text,
  unnest($4::text[])::text,
  NULLIF(upper(unnest($5::text[])), '')::char(3)
RETURNING id
`

type InsertManyLocationParams struct {
	Countries    []string
	CountryCodes []string
	Cities       []string
	Names        []string
	Iatas        []string
}

func (q *Queries) InsertManyLocation(ctx context.Context, arg InsertManyLocationParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, insertManyLocation,
		arg.Countries,
		arg.CountryCodes,
		arg.Cities,
		arg.Names,
		arg.Iatas,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsWithoutAliases = `-- name: ListLocationsWithoutAliases :many
SELECT l.id, l.name, l.iata
FROM locations l
WHERE NOT EXISTS (
    SELECT 1
    FROM location_aliases la
    WHERE la.location_id = l.id
)
AND EXISTS (
    SELECT 1
    FROM location_broker_codes lbc
    WHERE lbc.location_id = l.id
      AND lbc.enabled = TRUE
)
ORDER BY
    CASE WHEN $1::boolean THEN l.id END DESC,
    CASE WHEN NOT $1::boolean THEN l.id END ASC
LIMIT 500
`

type ListLocationsWithoutAliasesRow struct {
	ID   int64
	Name string
	Iata *string
}

func (q *Queries) ListLocationsWithoutAliases(ctx context.Context, fromEnd bool) ([]ListLocationsWithoutAliasesRow, error) {
	rows, err := q.db.Query(ctx, listLocationsWithoutAliases, fromEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsWithoutAliasesRow
	for rows.Next() {
		var i ListLocationsWithoutAliasesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Iata); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLocations = `-- name: SearchLocations :many
WITH matched_locations AS (
    SELECT
        l.id,
        l.country,
        l.country_code,
        l.city,
        l.name,
        l.iata,
        l.is_airport,
        l.created_at,
        l.updated_at,
        CASE
            -- IATA exact always wins
            WHEN upper(l.iata::text) = upper($1::text) THEN 0

            -- Exact alias
            WHEN EXISTS (
                SELECT 1
                FROM location_aliases la
                WHERE la.location_id = l.id
                  AND lower(la.alias) = lower($1::text)
            ) THEN 1

            -- Exact canonical fields
            WHEN lower(l.name) = lower($1::text) THEN 2
            WHEN lower(coalesce(l.city, '')) = lower($1::text) THEN 3
            WHEN lower(l.country) = lower($1::text) THEN 4

            -- Prefix matches
            WHEN l.name ILIKE $1::text || '%' THEN 5
            WHEN coalesce(l.city, '') ILIKE $1::text || '%' THEN 6
            WHEN l.country ILIKE $1::text || '%' THEN 7

            WHEN EXISTS (
                SELECT 1
                FROM location_aliases la
                WHERE la.location_id = l.id
                  AND la.alias ILIKE $1::text || '%'
            ) THEN 8

            -- Contains fallback
            WHEN l.name ILIKE '%' || $1::text || '%' THEN 9
            WHEN coalesce(l.city, '') ILIKE '%' || $1::text || '%' THEN 10
            WHEN l.country ILIKE '%' || $1::text || '%' THEN 11
            WHEN l.iata ILIKE '%' || $1::text || '%' THEN 12

            WHEN EXISTS (
                SELECT 1
                FROM location_aliases la
                WHERE la.location_id = l.id
                  AND la.alias ILIKE '%' || $1::text || '%'
            ) THEN 13

            ELSE 14
        END AS search_rank
    FROM locations l
    WHERE EXISTS (
        SELECT 1
        FROM location_broker_codes lbc
        WHERE lbc.location_id = l.id
          AND lbc.enabled = TRUE
    )
    AND (
        l.name ILIKE '%' || $1::text || '%'
        OR l.country ILIKE '%' || $1::text || '%'
        OR l.city ILIKE '%' || $1::text || '%'
        OR l.iata ILIKE '%' || $1::text || '%'
        OR EXISTS (
            SELECT 1
            FROM location_aliases la
            WHERE la.location_id = l.id
              AND la.alias ILIKE '%' || $1::text || '%'
        )
    )
)
SELECT
    id,
    country,
    country_code,
    city,
    name,
    iata,
    is_airport,
    created_at,
    updated_at
FROM matched_locations
ORDER BY
    search_rank ASC,
    CASE WHEN is_airport THEN 0 ELSE 1 END ASC,
    lower(name) ASC
LIMIT 100
`

type SearchLocationsRow struct {
	ID          int64
	Country     string
	CountryCode string
	City        *string
	Name        string
	Iata        *string
	IsAirport   bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) SearchLocations(ctx context.Context, search string) ([]SearchLocationsRow, error) {
	rows, err := q.db.Query(ctx, searchLocations, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchLocationsRow
	for rows.Next() {
		var i SearchLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Country,
			&i.CountryCode,
			&i.City,
			&i.Name,
			&i.Iata,
			&i.IsAirport,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleIsAirport = `-- name: ToggleIsAirport :exec
UPDATE locations
SET is_airport = $1,
    updated_at = now()
WHERE id = $2
`

type ToggleIsAirportParams struct {
	IsAirport bool
	ID        int64
}

func (q *Queries) ToggleIsAirport(ctx context.Context, arg ToggleIsAirportParams) error {
	_, err := q.db.Exec(ctx, toggleIsAirport, arg.IsAirport, arg.ID)
	return err
}

const upsertLocationByCountryCodeName = `-- name: UpsertLocationByCountryCodeName :one
INSERT INTO locations (country, country_code, city, name, iata)
VALUES (
  NULLIF($1, '')::text,
  NULLIF($2, '')::text,
  NULLIF($3, '')::text,
  $4::text,
  NULL
)
ON CONFLICT (country_code, lower(name))
DO UPDATE SET
  country      = EXCLUDED.country,
  country_code = EXCLUDED.country_code,
  city         = EXCLUDED.city,
  name         = EXCLUDED.name,
  updated_at   = now()
RETURNING id
`

type UpsertLocationByCountryCodeNameParams struct {
	Country     interface{}
	CountryCode interface{}
	City        interface{}
	Name        string
}

func (q *Queries) UpsertLocationByCountryCodeName(ctx context.Context, arg UpsertLocationByCountryCodeNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertLocationByCountryCodeName,
		arg.Country,
		arg.CountryCode,
		arg.City,
		arg.Name,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertLocationByIATA = `-- name: UpsertLocationByIATA :one
INSERT INTO locations (country, country_code, city, name, iata)
VALUES (
  NULLIF($1, '')::text,
  NULLIF($2, '')::text,
  NULLIF($3, '')::text,
  $4::text,
  NULLIF(upper($5), '')::char(3)
)
ON CONFLICT (iata) WHERE iata IS NOT NULL
DO UPDATE SET
  country      = EXCLUDED.country,
  country_code = EXCLUDED.country_code,
  city         = EXCLUDED.city,
  name         = EXCLUDED.name,
  updated_at   = now()
RETURNING id
`

type UpsertLocationByIATAParams struct {
	Country     interface{}
	CountryCode interface{}
	City        interface{}
	Name        string
	Iata        interface{}
}

func (q *Queries) UpsertLocationByIATA(ctx context.Context, arg UpsertLocationByIATAParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertLocationByIATA,
		arg.Country,
		arg.CountryCode,
		arg.City,
		arg.Name,
		arg.Iata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
