// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: location_broker_codes_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLocationBrokerCodesByLocationID = `-- name: CountLocationBrokerCodesByLocationID :one
SELECT COUNT(*) FROM location_broker_codes
WHERE location_id = $1
`

func (q *Queries) CountLocationBrokerCodesByLocationID(ctx context.Context, locationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLocationBrokerCodesByLocationID, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLocationBrokerCode = `-- name: DeleteLocationBrokerCode :one
DELETE FROM location_broker_codes
WHERE id = $1
RETURNING location_id
`

func (q *Queries) DeleteLocationBrokerCode(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteLocationBrokerCode, id)
	var location_id int64
	err := row.Scan(&location_id)
	return location_id, err
}

const disableLocationBrokerCode = `-- name: DisableLocationBrokerCode :exec
UPDATE location_broker_codes
SET
    enabled = FALSE,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

func (q *Queries) DisableLocationBrokerCode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableLocationBrokerCode, id)
	return err
}

const enableLocationBrokerCode = `-- name: EnableLocationBrokerCode :exec
UPDATE location_broker_codes
SET
    enabled = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

func (q *Queries) EnableLocationBrokerCode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, enableLocationBrokerCode, id)
	return err
}

const getAllLocationBrokerCodesByLocationIDs = `-- name: GetAllLocationBrokerCodesByLocationIDs :many
SELECT
    lbc.id, lbc.location_id, lbc.broker, lbc.broker_location_id, lbc.enabled, lbc.created_at, lbc.updated_at,
    l.country_code AS location_country_code
FROM
    location_broker_codes lbc
    JOIN locations l ON l.id = lbc.location_id
WHERE
    lbc.location_id = ANY ($1::bigint[])
`

type GetAllLocationBrokerCodesByLocationIDsRow struct {
	ID                  int64
	LocationID          int64
	Broker              Broker
	BrokerLocationID    string
	Enabled             bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	LocationCountryCode string
}

func (q *Queries) GetAllLocationBrokerCodesByLocationIDs(ctx context.Context, locationIds []int64) ([]GetAllLocationBrokerCodesByLocationIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllLocationBrokerCodesByLocationIDs, locationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLocationBrokerCodesByLocationIDsRow
	for rows.Next() {
		var i GetAllLocationBrokerCodesByLocationIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Broker,
			&i.BrokerLocationID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationCountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationBrokerCode = `-- name: GetLocationBrokerCode :one
SELECT
    id,
    location_id,
    broker,
    broker_location_id,
    enabled,
    created_at,
    updated_at
FROM
    location_broker_codes
WHERE
    (
        broker = $1
        AND broker_location_id = $2
    )
    OR (
        location_id = $3
        AND broker = $1
    )
LIMIT
    1
`

type GetLocationBrokerCodeParams struct {
	Broker           Broker
	BrokerLocationID string
	LocationID       int64
}

func (q *Queries) GetLocationBrokerCode(ctx context.Context, arg GetLocationBrokerCodeParams) (LocationBrokerCode, error) {
	row := q.db.QueryRow(ctx, getLocationBrokerCode, arg.Broker, arg.BrokerLocationID, arg.LocationID)
	var i LocationBrokerCode
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Broker,
		&i.BrokerLocationID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLocationBrokerCode = `-- name: InsertLocationBrokerCode :one
INSERT INTO
    location_broker_codes (location_id, broker, broker_location_id)
VALUES
    (
        $1,
        $2,
        $3
    ) RETURNING id,
    location_id,
    broker,
    broker_location_id,
    enabled,
    created_at,
    updated_at
`

type InsertLocationBrokerCodeParams struct {
	LocationID       int64
	Broker           Broker
	BrokerLocationID string
}

func (q *Queries) InsertLocationBrokerCode(ctx context.Context, arg InsertLocationBrokerCodeParams) (LocationBrokerCode, error) {
	row := q.db.QueryRow(ctx, insertLocationBrokerCode, arg.LocationID, arg.Broker, arg.BrokerLocationID)
	var i LocationBrokerCode
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Broker,
		&i.BrokerLocationID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocationBrokerCodesWithLocation = `-- name: ListLocationBrokerCodesWithLocation :many
SELECT
    lbc.id,
    lbc.location_id,
    lbc.broker,
    lbc.broker_location_id,
    lbc.enabled,
    lbc.created_at,
    lbc.updated_at,
    l.country AS location_country,
    l.country_code AS location_country_code,
    l.city AS location_city,
    l.name AS location_name,
    l.iata AS location_iata
FROM
    location_broker_codes lbc
    JOIN locations l ON l.id = lbc.location_id
WHERE
    l.country_code ILIKE '%' || $3 || '%'
    OR l.city ILIKE '%' || $3 || '%'
    OR l.name ILIKE '%' || $3 || '%'
    OR l.iata ILIKE '%' || $3 || '%'
ORDER BY
    l.country_code, l.name, lbc.broker
LIMIT $1
OFFSET $2
`

type ListLocationBrokerCodesWithLocationParams struct {
	Limit  int32
	Offset int32
	Search *string
}

type ListLocationBrokerCodesWithLocationRow struct {
	ID                  int64
	LocationID          int64
	Broker              Broker
	BrokerLocationID    string
	Enabled             bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	LocationCountry     string
	LocationCountryCode string
	LocationCity        *string
	LocationName        string
	LocationIata        *string
}

func (q *Queries) ListLocationBrokerCodesWithLocation(ctx context.Context, arg ListLocationBrokerCodesWithLocationParams) ([]ListLocationBrokerCodesWithLocationRow, error) {
	rows, err := q.db.Query(ctx, listLocationBrokerCodesWithLocation, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationBrokerCodesWithLocationRow
	for rows.Next() {
		var i ListLocationBrokerCodesWithLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Broker,
			&i.BrokerLocationID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationCountry,
			&i.LocationCountryCode,
			&i.LocationCity,
			&i.LocationName,
			&i.LocationIata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
