// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: markup_rates_query.sql

package db

import (
	"context"
)

const countMarkupRates = `-- name: CountMarkupRates :one
SELECT COUNT(*) AS total
FROM markup_rates
WHERE ($1::text IS NULL OR country_code ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR broker::text ILIKE '%' || $2 || '%')
`

type CountMarkupRatesParams struct {
	CountryCode *string
	Broker      *string
}

// Count total rows matching the same filters (for pagination).
func (q *Queries) CountMarkupRates(ctx context.Context, arg CountMarkupRatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMarkupRates, arg.CountryCode, arg.Broker)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const deleteMarkupRate = `-- name: DeleteMarkupRate :one
DELETE FROM markup_rates
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteMarkupRate(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteMarkupRate, id)
	err := row.Scan(&id)
	return id, err
}

const getMarkupRates = `-- name: GetMarkupRates :many
SELECT mark_up_gross, mark_up_net
FROM markup_rates
WHERE country_code = $1
  AND broker = $2::broker
`

type GetMarkupRatesParams struct {
	CountryCode string
	Broker      Broker
}

type GetMarkupRatesRow struct {
	MarkUpGross float64
	MarkUpNet   float64
}

// Used by the markup logic to fetch rates for a given search.
func (q *Queries) GetMarkupRates(ctx context.Context, arg GetMarkupRatesParams) ([]GetMarkupRatesRow, error) {
	rows, err := q.db.Query(ctx, getMarkupRates, arg.CountryCode, arg.Broker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMarkupRatesRow
	for rows.Next() {
		var i GetMarkupRatesRow
		if err := rows.Scan(&i.MarkUpGross, &i.MarkUpNet); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMarkupRate = `-- name: InsertMarkupRate :one
INSERT INTO markup_rates (country_code, broker, mark_up_gross, mark_up_net)
VALUES ($1, $2, $3, $4)
RETURNING id, country_code, mark_up_gross, mark_up_net, created_at, updated_at, broker
`

type InsertMarkupRateParams struct {
	CountryCode string
	Broker      Broker
	MarkUpGross float64
	MarkUpNet   float64
}

func (q *Queries) InsertMarkupRate(ctx context.Context, arg InsertMarkupRateParams) (MarkupRate, error) {
	row := q.db.QueryRow(ctx, insertMarkupRate,
		arg.CountryCode,
		arg.Broker,
		arg.MarkUpGross,
		arg.MarkUpNet,
	)
	var i MarkupRate
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.MarkUpGross,
		&i.MarkUpNet,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Broker,
	)
	return i, err
}

const listMarkupRates = `-- name: ListMarkupRates :many
SELECT id, country_code, mark_up_gross, mark_up_net, created_at, updated_at, broker
FROM markup_rates
WHERE ($1::text IS NULL OR country_code ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR broker::text ILIKE '%' || $2 || '%')
ORDER BY
  CASE WHEN $3::text = 'country_code' AND $4::text = 'asc' THEN country_code END ASC,
  CASE WHEN $3::text = 'country_code' AND $4::text = 'desc' THEN country_code END DESC,
  CASE WHEN $3::text = 'broker' AND $4::text = 'asc' THEN broker::text END ASC,
  CASE WHEN $3::text = 'broker' AND $4::text = 'desc' THEN broker::text END DESC,
  id ASC
LIMIT $6::int
OFFSET $5::int
`

type ListMarkupRatesParams struct {
	CountryCode *string
	Broker      *string
	SortField   string
	SortDir     string
	QueryOffset int32
	QueryLimit  int32
}

// Admin listing with pagination, optional filtering, and sorting.
func (q *Queries) ListMarkupRates(ctx context.Context, arg ListMarkupRatesParams) ([]MarkupRate, error) {
	rows, err := q.db.Query(ctx, listMarkupRates,
		arg.CountryCode,
		arg.Broker,
		arg.SortField,
		arg.SortDir,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkupRate
	for rows.Next() {
		var i MarkupRate
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.MarkUpGross,
			&i.MarkUpNet,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Broker,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarkupRate = `-- name: UpdateMarkupRate :one
UPDATE markup_rates
SET country_code = $2,
    broker = $3,
    mark_up_gross = $4,
    mark_up_net = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, country_code, mark_up_gross, mark_up_net, created_at, updated_at, broker
`

type UpdateMarkupRateParams struct {
	ID          int64
	CountryCode string
	Broker      Broker
	MarkUpGross float64
	MarkUpNet   float64
}

func (q *Queries) UpdateMarkupRate(ctx context.Context, arg UpdateMarkupRateParams) (MarkupRate, error) {
	row := q.db.QueryRow(ctx, updateMarkupRate,
		arg.ID,
		arg.CountryCode,
		arg.Broker,
		arg.MarkUpGross,
		arg.MarkUpNet,
	)
	var i MarkupRate
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.MarkUpGross,
		&i.MarkUpNet,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Broker,
	)
	return i, err
}
