// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Broker string

const (
	BrokerFlex  Broker = "flex"
	BrokerHertz Broker = "hertz"
)

func (e *Broker) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Broker(s)
	case string:
		*e = Broker(s)
	default:
		return fmt.Errorf("unsupported scan type for Broker: %T", src)
	}
	return nil
}

type NullBroker struct {
	Broker Broker
	Valid  bool // Valid is true if Broker is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBroker) Scan(value interface{}) error {
	if value == nil {
		ns.Broker, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Broker.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBroker) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Broker), nil
}

type BrokerTranslationStatus string

const (
	BrokerTranslationStatusPending    BrokerTranslationStatus = "pending"
	BrokerTranslationStatusTranslated BrokerTranslationStatus = "translated"
	BrokerTranslationStatusVerified   BrokerTranslationStatus = "verified"
)

func (e *BrokerTranslationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BrokerTranslationStatus(s)
	case string:
		*e = BrokerTranslationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BrokerTranslationStatus: %T", src)
	}
	return nil
}

type NullBrokerTranslationStatus struct {
	BrokerTranslationStatus BrokerTranslationStatus
	Valid                   bool // Valid is true if BrokerTranslationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBrokerTranslationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BrokerTranslationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BrokerTranslationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBrokerTranslationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BrokerTranslationStatus), nil
}

type AvailablePlansSnapshot struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	DriverAge   string
	PickupDate  string
	PickupTime  string
	ReturnDate  string
	ReturnTime  string
	CountryCode string
	Plans       []byte
}

type BrokerTranslation struct {
	ID              int32
	SourceText      string
	TargetText      *string
	Status          BrokerTranslationStatus
	ConfidenceScore *int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Coupon struct {
	ID        int32
	Name      string
	Code      string
	Discount  int32
	IsEnabled bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Currency struct {
	ID              int32
	CurrencyCode    string
	CurrencyIsoName string
	Rate            pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type HertzMarkupRate struct {
	ID                  int64
	Country             string
	Brand               string
	PickupDateFrom      pgtype.Date
	PickupDateTo        pgtype.Date
	CarGroup            string
	NumOfRentalDaysFrom int32
	NumOfRentalDaysTo   int32
	MarkUpGross         float64
	MarkUpNet           float64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type Location struct {
	ID          int64
	Country     string
	CountryCode string
	City        *string
	Name        string
	Iata        *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type LocationBrokerCode struct {
	ID               int64
	LocationID       int64
	Broker           Broker
	BrokerLocationID string
	Enabled          bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
