// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: price_offers_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPriceOffersByAgent = `-- name: CountPriceOffersByAgent :one
SELECT COUNT(*)::BIGINT AS total
FROM price_offers
WHERE agent_id = $1
  AND ($2::offer_status IS NULL OR status = $2::offer_status)
  AND ($3::text IS NULL OR price_offers.name ILIKE '%' || $3::text || '%')
`

type CountPriceOffersByAgentParams struct {
	AgentID    int64
	Status     NullOfferStatus
	NameSearch *string
}

func (q *Queries) CountPriceOffersByAgent(ctx context.Context, arg CountPriceOffersByAgentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceOffersByAgent, arg.AgentID, arg.Status, arg.NameSearch)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPriceOffer = `-- name: CreatePriceOffer :one
INSERT INTO price_offers (
    agent_id,
    name,
    pickup_location_id,
    dropoff_location_id,
    pickup_date,
    dropoff_date,
    rental_days,
    pickup_time,
    dropoff_time,
    driver_age,
    plan_id,
    broker,
    rate_qualifier,
    supplier_code,
    car_details,
    plan_inclusions,
    currency_code,
    currency_rate,
    purchase_price,
    markup_percentage,
    broker_erp_price,
    bt_erp_price,
    total_price,
    offered_currency_code,
    offered_price,
    pay_at_pickup
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,    
    $25,
    $26
)
RETURNING id, reservation_id, token, agent_id, status, name, pickup_location_id, dropoff_location_id, pickup_date, dropoff_date, pickup_time, dropoff_time, driver_age, rental_days, plan_id, broker, rate_qualifier, supplier_code, car_details, plan_inclusions, currency_code, currency_rate, purchase_price, markup_percentage, broker_erp_price, bt_erp_price, total_price, offered_currency_code, offered_price, renewed_at, created_at, updated_at, pay_at_pickup
`

type CreatePriceOfferParams struct {
	AgentID             int64
	Name                string
	PickupLocationID    int64
	DropoffLocationID   int64
	PickupDate          pgtype.Date
	DropoffDate         pgtype.Date
	RentalDays          int32
	PickupTime          string
	DropoffTime         string
	DriverAge           string
	PlanID              string
	Broker              Broker
	RateQualifier       string
	SupplierCode        string
	CarDetails          []byte
	PlanInclusions      []string
	CurrencyCode        string
	CurrencyRate        pgtype.Numeric
	PurchasePrice       pgtype.Numeric
	MarkupPercentage    pgtype.Numeric
	BrokerErpPrice      pgtype.Numeric
	BtErpPrice          int32
	TotalPrice          int32
	OfferedCurrencyCode string
	OfferedPrice        int32
	PayAtPickup         []byte
}

func (q *Queries) CreatePriceOffer(ctx context.Context, arg CreatePriceOfferParams) (PriceOffer, error) {
	row := q.db.QueryRow(ctx, createPriceOffer,
		arg.AgentID,
		arg.Name,
		arg.PickupLocationID,
		arg.DropoffLocationID,
		arg.PickupDate,
		arg.DropoffDate,
		arg.RentalDays,
		arg.PickupTime,
		arg.DropoffTime,
		arg.DriverAge,
		arg.PlanID,
		arg.Broker,
		arg.RateQualifier,
		arg.SupplierCode,
		arg.CarDetails,
		arg.PlanInclusions,
		arg.CurrencyCode,
		arg.CurrencyRate,
		arg.PurchasePrice,
		arg.MarkupPercentage,
		arg.BrokerErpPrice,
		arg.BtErpPrice,
		arg.TotalPrice,
		arg.OfferedCurrencyCode,
		arg.OfferedPrice,
		arg.PayAtPickup,
	)
	var i PriceOffer
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.Token,
		&i.AgentID,
		&i.Status,
		&i.Name,
		&i.PickupLocationID,
		&i.DropoffLocationID,
		&i.PickupDate,
		&i.DropoffDate,
		&i.PickupTime,
		&i.DropoffTime,
		&i.DriverAge,
		&i.RentalDays,
		&i.PlanID,
		&i.Broker,
		&i.RateQualifier,
		&i.SupplierCode,
		&i.CarDetails,
		&i.PlanInclusions,
		&i.CurrencyCode,
		&i.CurrencyRate,
		&i.PurchasePrice,
		&i.MarkupPercentage,
		&i.BrokerErpPrice,
		&i.BtErpPrice,
		&i.TotalPrice,
		&i.OfferedCurrencyCode,
		&i.OfferedPrice,
		&i.RenewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayAtPickup,
	)
	return i, err
}

const getPriceOfferById = `-- name: GetPriceOfferById :one
SELECT 
    price_offers.id, price_offers.reservation_id, price_offers.token, price_offers.agent_id, price_offers.status, price_offers.name, price_offers.pickup_location_id, price_offers.dropoff_location_id, price_offers.pickup_date, price_offers.dropoff_date, price_offers.pickup_time, price_offers.dropoff_time, price_offers.driver_age, price_offers.rental_days, price_offers.plan_id, price_offers.broker, price_offers.rate_qualifier, price_offers.supplier_code, price_offers.car_details, price_offers.plan_inclusions, price_offers.currency_code, price_offers.currency_rate, price_offers.purchase_price, price_offers.markup_percentage, price_offers.broker_erp_price, price_offers.bt_erp_price, price_offers.total_price, price_offers.offered_currency_code, price_offers.offered_price, price_offers.renewed_at, price_offers.created_at, price_offers.updated_at, price_offers.pay_at_pickup, 
    pl.name AS pickup_location, 
    pl.country_code,
    dl.name AS dropoff_location, 
    lbc_pickup.broker_location_id AS pickup_broker_location_id,
    lbc_dropoff.broker_location_id AS dropoff_broker_location_id
FROM price_offers
    JOIN locations pl ON price_offers.pickup_location_id = pl.id
    JOIN locations dl ON price_offers.dropoff_location_id = dl.id
    JOIN location_broker_codes lbc_pickup ON lbc_pickup.location_id = pl.id AND lbc_pickup.broker = price_offers.broker
    JOIN location_broker_codes lbc_dropoff ON lbc_dropoff.location_id = dl.id AND lbc_dropoff.broker = price_offers.broker
WHERE price_offers.id = $1 AND price_offers.agent_id = $2
`

type GetPriceOfferByIdParams struct {
	ID      int64
	AgentID int64
}

type GetPriceOfferByIdRow struct {
	ID                      int64
	ReservationID           *int64
	Token                   pgtype.UUID
	AgentID                 int64
	Status                  OfferStatus
	Name                    string
	PickupLocationID        int64
	DropoffLocationID       int64
	PickupDate              pgtype.Date
	DropoffDate             pgtype.Date
	PickupTime              string
	DropoffTime             string
	DriverAge               string
	RentalDays              int32
	PlanID                  string
	Broker                  Broker
	RateQualifier           string
	SupplierCode            string
	CarDetails              []byte
	PlanInclusions          []string
	CurrencyCode            string
	CurrencyRate            pgtype.Numeric
	PurchasePrice           pgtype.Numeric
	MarkupPercentage        pgtype.Numeric
	BrokerErpPrice          pgtype.Numeric
	BtErpPrice              int32
	TotalPrice              int32
	OfferedCurrencyCode     string
	OfferedPrice            int32
	RenewedAt               pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	PayAtPickup             []byte
	PickupLocation          string
	CountryCode             string
	DropoffLocation         string
	PickupBrokerLocationID  string
	DropoffBrokerLocationID string
}

func (q *Queries) GetPriceOfferById(ctx context.Context, arg GetPriceOfferByIdParams) (GetPriceOfferByIdRow, error) {
	row := q.db.QueryRow(ctx, getPriceOfferById, arg.ID, arg.AgentID)
	var i GetPriceOfferByIdRow
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.Token,
		&i.AgentID,
		&i.Status,
		&i.Name,
		&i.PickupLocationID,
		&i.DropoffLocationID,
		&i.PickupDate,
		&i.DropoffDate,
		&i.PickupTime,
		&i.DropoffTime,
		&i.DriverAge,
		&i.RentalDays,
		&i.PlanID,
		&i.Broker,
		&i.RateQualifier,
		&i.SupplierCode,
		&i.CarDetails,
		&i.PlanInclusions,
		&i.CurrencyCode,
		&i.CurrencyRate,
		&i.PurchasePrice,
		&i.MarkupPercentage,
		&i.BrokerErpPrice,
		&i.BtErpPrice,
		&i.TotalPrice,
		&i.OfferedCurrencyCode,
		&i.OfferedPrice,
		&i.RenewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayAtPickup,
		&i.PickupLocation,
		&i.CountryCode,
		&i.DropoffLocation,
		&i.PickupBrokerLocationID,
		&i.DropoffBrokerLocationID,
	)
	return i, err
}

const getPriceOfferByToken = `-- name: GetPriceOfferByToken :one
SELECT price_offers.id, price_offers.reservation_id, price_offers.token, price_offers.agent_id, price_offers.status, price_offers.name, price_offers.pickup_location_id, price_offers.dropoff_location_id, price_offers.pickup_date, price_offers.dropoff_date, price_offers.pickup_time, price_offers.dropoff_time, price_offers.driver_age, price_offers.rental_days, price_offers.plan_id, price_offers.broker, price_offers.rate_qualifier, price_offers.supplier_code, price_offers.car_details, price_offers.plan_inclusions, price_offers.currency_code, price_offers.currency_rate, price_offers.purchase_price, price_offers.markup_percentage, price_offers.broker_erp_price, price_offers.bt_erp_price, price_offers.total_price, price_offers.offered_currency_code, price_offers.offered_price, price_offers.renewed_at, price_offers.created_at, price_offers.updated_at, price_offers.pay_at_pickup , pl.name AS pickup_location, dl.name AS dropoff_location
FROM price_offers
    JOIN locations pl ON price_offers.pickup_location_id = pl.id
    JOIN locations dl ON price_offers.dropoff_location_id = dl.id
 WHERE token = $1 AND status != 'unavailable'
`

type GetPriceOfferByTokenRow struct {
	ID                  int64
	ReservationID       *int64
	Token               pgtype.UUID
	AgentID             int64
	Status              OfferStatus
	Name                string
	PickupLocationID    int64
	DropoffLocationID   int64
	PickupDate          pgtype.Date
	DropoffDate         pgtype.Date
	PickupTime          string
	DropoffTime         string
	DriverAge           string
	RentalDays          int32
	PlanID              string
	Broker              Broker
	RateQualifier       string
	SupplierCode        string
	CarDetails          []byte
	PlanInclusions      []string
	CurrencyCode        string
	CurrencyRate        pgtype.Numeric
	PurchasePrice       pgtype.Numeric
	MarkupPercentage    pgtype.Numeric
	BrokerErpPrice      pgtype.Numeric
	BtErpPrice          int32
	TotalPrice          int32
	OfferedCurrencyCode string
	OfferedPrice        int32
	RenewedAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	PayAtPickup         []byte
	PickupLocation      string
	DropoffLocation     string
}

func (q *Queries) GetPriceOfferByToken(ctx context.Context, token pgtype.UUID) (GetPriceOfferByTokenRow, error) {
	row := q.db.QueryRow(ctx, getPriceOfferByToken, token)
	var i GetPriceOfferByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.Token,
		&i.AgentID,
		&i.Status,
		&i.Name,
		&i.PickupLocationID,
		&i.DropoffLocationID,
		&i.PickupDate,
		&i.DropoffDate,
		&i.PickupTime,
		&i.DropoffTime,
		&i.DriverAge,
		&i.RentalDays,
		&i.PlanID,
		&i.Broker,
		&i.RateQualifier,
		&i.SupplierCode,
		&i.CarDetails,
		&i.PlanInclusions,
		&i.CurrencyCode,
		&i.CurrencyRate,
		&i.PurchasePrice,
		&i.MarkupPercentage,
		&i.BrokerErpPrice,
		&i.BtErpPrice,
		&i.TotalPrice,
		&i.OfferedCurrencyCode,
		&i.OfferedPrice,
		&i.RenewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayAtPickup,
		&i.PickupLocation,
		&i.DropoffLocation,
	)
	return i, err
}

const listPriceOffersByAgent = `-- name: ListPriceOffersByAgent :many
SELECT price_offers.id, status, price_offers.name, 
pl.name AS pickup_location, dl.name AS dropoff_location, 
pickup_date, dropoff_date, pickup_time, dropoff_time, 
currency_code, total_price, offered_currency_code, offered_price, 
price_offers.created_at
FROM price_offers
    JOIN locations pl ON price_offers.pickup_location_id = pl.id
    JOIN locations dl ON price_offers.dropoff_location_id = dl.id
WHERE agent_id = $1
  AND ($2::offer_status IS NULL OR status = $2::offer_status)
  AND ($3::text IS NULL OR price_offers.name ILIKE '%' || $3::text || '%')
ORDER BY price_offers.created_at DESC
LIMIT $5
OFFSET $4
`

type ListPriceOffersByAgentParams struct {
	AgentID    int64
	Status     NullOfferStatus
	NameSearch *string
	PageOffset int32
	PageSize   int32
}

type ListPriceOffersByAgentRow struct {
	ID                  int64
	Status              OfferStatus
	Name                string
	PickupLocation      string
	DropoffLocation     string
	PickupDate          pgtype.Date
	DropoffDate         pgtype.Date
	PickupTime          string
	DropoffTime         string
	CurrencyCode        string
	TotalPrice          int32
	OfferedCurrencyCode string
	OfferedPrice        int32
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) ListPriceOffersByAgent(ctx context.Context, arg ListPriceOffersByAgentParams) ([]ListPriceOffersByAgentRow, error) {
	rows, err := q.db.Query(ctx, listPriceOffersByAgent,
		arg.AgentID,
		arg.Status,
		arg.NameSearch,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPriceOffersByAgentRow
	for rows.Next() {
		var i ListPriceOffersByAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.PickupLocation,
			&i.DropoffLocation,
			&i.PickupDate,
			&i.DropoffDate,
			&i.PickupTime,
			&i.DropoffTime,
			&i.CurrencyCode,
			&i.TotalPrice,
			&i.OfferedCurrencyCode,
			&i.OfferedPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewPriceOfferDetails = `-- name: RenewPriceOfferDetails :exec
UPDATE price_offers SET
    car_details = $1,
    plan_inclusions = $2,
    currency_code = $3,
    purchase_price = $4,
    markup_percentage = $5,
    broker_erp_price = $6,
    bt_erp_price = $7,
    total_price = $8,
    renewed_at = now(),
    updated_at = now()
WHERE id = $9 AND agent_id = $10 AND status != 'unavailable'
`

type RenewPriceOfferDetailsParams struct {
	CarDetails       []byte
	PlanInclusions   []string
	CurrencyCode     string
	PurchasePrice    pgtype.Numeric
	MarkupPercentage pgtype.Numeric
	BrokerErpPrice   pgtype.Numeric
	BtErpPrice       int32
	TotalPrice       int32
	ID               int64
	AgentID          int64
}

func (q *Queries) RenewPriceOfferDetails(ctx context.Context, arg RenewPriceOfferDetailsParams) error {
	_, err := q.db.Exec(ctx, renewPriceOfferDetails,
		arg.CarDetails,
		arg.PlanInclusions,
		arg.CurrencyCode,
		arg.PurchasePrice,
		arg.MarkupPercentage,
		arg.BrokerErpPrice,
		arg.BtErpPrice,
		arg.TotalPrice,
		arg.ID,
		arg.AgentID,
	)
	return err
}

const renewPriceOfferUnavailable = `-- name: RenewPriceOfferUnavailable :exec
UPDATE price_offers SET
    status = 'unavailable',
    renewed_at = now(),
    updated_at = now()
WHERE id = $1 AND agent_id = $2 AND reservation_id IS NULL
`

type RenewPriceOfferUnavailableParams struct {
	ID      int64
	AgentID int64
}

func (q *Queries) RenewPriceOfferUnavailable(ctx context.Context, arg RenewPriceOfferUnavailableParams) error {
	_, err := q.db.Exec(ctx, renewPriceOfferUnavailable, arg.ID, arg.AgentID)
	return err
}

const setPriceOfferRenewedAt = `-- name: SetPriceOfferRenewedAt :exec
UPDATE price_offers SET
    renewed_at = $1
WHERE id = $2 AND agent_id = $3 AND reservation_id IS NULL
`

type SetPriceOfferRenewedAtParams struct {
	RenewedAt pgtype.Timestamptz
	ID        int64
	AgentID   int64
}

func (q *Queries) SetPriceOfferRenewedAt(ctx context.Context, arg SetPriceOfferRenewedAtParams) error {
	_, err := q.db.Exec(ctx, setPriceOfferRenewedAt, arg.RenewedAt, arg.ID, arg.AgentID)
	return err
}

const updatePriceOffer = `-- name: UpdatePriceOffer :exec
UPDATE price_offers SET
    status = COALESCE($1, status),
    name = COALESCE($2, name),
    offered_currency_code = COALESCE($3, offered_currency_code),
    offered_price = COALESCE($4, offered_price),
    reservation_id = $5,
    updated_at = now()
WHERE id = $6 AND agent_id = $7 AND status != 'unavailable' AND reservation_id IS NULL
`

type UpdatePriceOfferParams struct {
	Status              NullOfferStatus
	Name                *string
	OfferedCurrencyCode *string
	OfferedPrice        *int32
	ReservationID       *int64
	ID                  int64
	AgentID             int64
}

func (q *Queries) UpdatePriceOffer(ctx context.Context, arg UpdatePriceOfferParams) error {
	_, err := q.db.Exec(ctx, updatePriceOffer,
		arg.Status,
		arg.Name,
		arg.OfferedCurrencyCode,
		arg.OfferedPrice,
		arg.ReservationID,
		arg.ID,
		arg.AgentID,
	)
	return err
}
