// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: price_offers_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPriceOffer = `-- name: CreatePriceOffer :one
INSERT INTO price_offers (
    agent_id,
    notes,
    pickup_location_id,
    dropoff_location_id,
    pickup_date,
    return_date,
    pickup_time,
    dropoff_time,
    driver_age,
    supplier_code,
    car_details,
    plan_inclusions,
    currency_code,
    purchase_price,
    markup_percentage,
    broker_erp_price,
    bt_erp_price,
    total_price,
    offered_currency_code,
    offered_price,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21
)
RETURNING id, token, agent_id, status, notes, pickup_location_id, dropoff_location_id, pickup_date, return_date, pickup_time, dropoff_time, driver_age, supplier_code, car_details, plan_inclusions, currency_code, purchase_price, markup_percentage, broker_erp_price, bt_erp_price, total_price, offered_currency_code, offered_price, expires_at, created_at, updated_at
`

type CreatePriceOfferParams struct {
	AgentID             int32
	Notes               *string
	PickupLocationID    string
	DropoffLocationID   string
	PickupDate          pgtype.Date
	ReturnDate          pgtype.Date
	PickupTime          string
	DropoffTime         string
	DriverAge           int32
	SupplierCode        string
	CarDetails          []byte
	PlanInclusions      []string
	CurrencyCode        string
	PurchasePrice       pgtype.Numeric
	MarkupPercentage    pgtype.Numeric
	BrokerErpPrice      pgtype.Numeric
	BtErpPrice          int32
	TotalPrice          int32
	OfferedCurrencyCode string
	OfferedPrice        int32
	ExpiresAt           pgtype.Timestamptz
}

func (q *Queries) CreatePriceOffer(ctx context.Context, arg CreatePriceOfferParams) (PriceOffer, error) {
	row := q.db.QueryRow(ctx, createPriceOffer,
		arg.AgentID,
		arg.Notes,
		arg.PickupLocationID,
		arg.DropoffLocationID,
		arg.PickupDate,
		arg.ReturnDate,
		arg.PickupTime,
		arg.DropoffTime,
		arg.DriverAge,
		arg.SupplierCode,
		arg.CarDetails,
		arg.PlanInclusions,
		arg.CurrencyCode,
		arg.PurchasePrice,
		arg.MarkupPercentage,
		arg.BrokerErpPrice,
		arg.BtErpPrice,
		arg.TotalPrice,
		arg.OfferedCurrencyCode,
		arg.OfferedPrice,
		arg.ExpiresAt,
	)
	var i PriceOffer
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.AgentID,
		&i.Status,
		&i.Notes,
		&i.PickupLocationID,
		&i.DropoffLocationID,
		&i.PickupDate,
		&i.ReturnDate,
		&i.PickupTime,
		&i.DropoffTime,
		&i.DriverAge,
		&i.SupplierCode,
		&i.CarDetails,
		&i.PlanInclusions,
		&i.CurrencyCode,
		&i.PurchasePrice,
		&i.MarkupPercentage,
		&i.BrokerErpPrice,
		&i.BtErpPrice,
		&i.TotalPrice,
		&i.OfferedCurrencyCode,
		&i.OfferedPrice,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPriceOfferById = `-- name: GetPriceOfferById :one
SELECT id, token, agent_id, status, notes, pickup_location_id, dropoff_location_id, pickup_date, return_date, pickup_time, dropoff_time, driver_age, supplier_code, car_details, plan_inclusions, currency_code, purchase_price, markup_percentage, broker_erp_price, bt_erp_price, total_price, offered_currency_code, offered_price, expires_at, created_at, updated_at FROM price_offers WHERE id = $1 AND agent_id = $2
`

type GetPriceOfferByIdParams struct {
	ID      int64
	AgentID int32
}

func (q *Queries) GetPriceOfferById(ctx context.Context, arg GetPriceOfferByIdParams) (PriceOffer, error) {
	row := q.db.QueryRow(ctx, getPriceOfferById, arg.ID, arg.AgentID)
	var i PriceOffer
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.AgentID,
		&i.Status,
		&i.Notes,
		&i.PickupLocationID,
		&i.DropoffLocationID,
		&i.PickupDate,
		&i.ReturnDate,
		&i.PickupTime,
		&i.DropoffTime,
		&i.DriverAge,
		&i.SupplierCode,
		&i.CarDetails,
		&i.PlanInclusions,
		&i.CurrencyCode,
		&i.PurchasePrice,
		&i.MarkupPercentage,
		&i.BrokerErpPrice,
		&i.BtErpPrice,
		&i.TotalPrice,
		&i.OfferedCurrencyCode,
		&i.OfferedPrice,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPriceOfferByToken = `-- name: GetPriceOfferByToken :one
SELECT id, token, agent_id, status, notes, pickup_location_id, dropoff_location_id, pickup_date, return_date, pickup_time, dropoff_time, driver_age, supplier_code, car_details, plan_inclusions, currency_code, purchase_price, markup_percentage, broker_erp_price, bt_erp_price, total_price, offered_currency_code, offered_price, expires_at, created_at, updated_at FROM price_offers WHERE token = $1
`

func (q *Queries) GetPriceOfferByToken(ctx context.Context, token pgtype.UUID) (PriceOffer, error) {
	row := q.db.QueryRow(ctx, getPriceOfferByToken, token)
	var i PriceOffer
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.AgentID,
		&i.Status,
		&i.Notes,
		&i.PickupLocationID,
		&i.DropoffLocationID,
		&i.PickupDate,
		&i.ReturnDate,
		&i.PickupTime,
		&i.DropoffTime,
		&i.DriverAge,
		&i.SupplierCode,
		&i.CarDetails,
		&i.PlanInclusions,
		&i.CurrencyCode,
		&i.PurchasePrice,
		&i.MarkupPercentage,
		&i.BrokerErpPrice,
		&i.BtErpPrice,
		&i.TotalPrice,
		&i.OfferedCurrencyCode,
		&i.OfferedPrice,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPriceOffersByAgent = `-- name: ListPriceOffersByAgent :many
SELECT price_offers.id, status, notes, 
pl.name AS pickup_location, dl.name AS dropoff_location, 
pickup_date, return_date, pickup_time, dropoff_time, 
currency_code, total_price, offered_currency_code, offered_price, 
expires_at, price_offers.created_at
FROM price_offers
    JOIN locations pl ON price_offers.pickup_location_id = pl.id
    JOIN locations dl ON price_offers.dropoff_location_id = dl.id
WHERE agent_id = $1
  AND ($2::offer_status IS NULL OR status = $2::offer_status)
  AND ($3::text IS NULL OR notes ILIKE '%' || $3::text || '%')
ORDER BY price_offers.created_at DESC
LIMIT $5
OFFSET $4
`

type ListPriceOffersByAgentParams struct {
	AgentID     int32
	Status      NullOfferStatus
	NotesSearch *string
	PageOffset  int32
	PageSize    int32
}

type ListPriceOffersByAgentRow struct {
	ID                  int64
	Status              OfferStatus
	Notes               *string
	PickupLocation      string
	DropoffLocation     string
	PickupDate          pgtype.Date
	ReturnDate          pgtype.Date
	PickupTime          string
	DropoffTime         string
	CurrencyCode        string
	TotalPrice          int32
	OfferedCurrencyCode string
	OfferedPrice        int32
	ExpiresAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) ListPriceOffersByAgent(ctx context.Context, arg ListPriceOffersByAgentParams) ([]ListPriceOffersByAgentRow, error) {
	rows, err := q.db.Query(ctx, listPriceOffersByAgent,
		arg.AgentID,
		arg.Status,
		arg.NotesSearch,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPriceOffersByAgentRow
	for rows.Next() {
		var i ListPriceOffersByAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Notes,
			&i.PickupLocation,
			&i.DropoffLocation,
			&i.PickupDate,
			&i.ReturnDate,
			&i.PickupTime,
			&i.DropoffTime,
			&i.CurrencyCode,
			&i.TotalPrice,
			&i.OfferedCurrencyCode,
			&i.OfferedPrice,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceOffer = `-- name: UpdatePriceOffer :exec
UPDATE price_offers SET
    status = COALESCE($1, status),
    notes = COALESCE($2, notes),
    offered_currency_code = COALESCE($3, offered_currency_code),
    offered_price = COALESCE($4, offered_price),
    updated_at = now()
WHERE id = $5 AND agent_id = $6
`

type UpdatePriceOfferParams struct {
	Status              NullOfferStatus
	Notes               *string
	OfferedCurrencyCode *string
	OfferedPrice        *int32
	ID                  int64
	AgentID             int32
}

func (q *Queries) UpdatePriceOffer(ctx context.Context, arg UpdatePriceOfferParams) error {
	_, err := q.db.Exec(ctx, updatePriceOffer,
		arg.Status,
		arg.Notes,
		arg.OfferedCurrencyCode,
		arg.OfferedPrice,
		arg.ID,
		arg.AgentID,
	)
	return err
}
