// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApprovePriceOffer(ctx context.Context, id int64) (PriceOffer, error)
	CheckBrokerTranslationExists(ctx context.Context, sourceText string) (int64, error)
	CountAllTranslations(ctx context.Context, arg CountAllTranslationsParams) (int64, error)
	CountLocationBrokerCodesByLocationID(ctx context.Context, locationID int64) (int64, error)
	CountLocationBrokerCodesWithLocation(ctx context.Context, arg CountLocationBrokerCodesWithLocationParams) (int64, error)
	// Count total rows matching the same filters (for pagination).
	CountMarkupRates(ctx context.Context, arg CountMarkupRatesParams) (int64, error)
	CountPriceOffersByAgent(ctx context.Context, arg CountPriceOffersByAgentParams) (int64, error)
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	CreatePriceOffer(ctx context.Context, arg CreatePriceOfferParams) (PriceOffer, error)
	DeleteBrokerTranslation(ctx context.Context, id int64) error
	DeleteCoupon(ctx context.Context, id int64) error
	DeleteCurrency(ctx context.Context, id int64) error
	DeleteLocationBrokerCode(ctx context.Context, id int64) (int64, error)
	DeleteLocationByID(ctx context.Context, id int64) error
	DeleteMarkupRate(ctx context.Context, id int64) (int64, error)
	DeleteOldAvailablePlansSnapshots(ctx context.Context, createdAt pgtype.Timestamptz) error
	DeleteSnapshotByID(ctx context.Context, id int64) error
	// Imports treat existing locations as the source of truth: a supplier's import only fills in
	// what a location is missing, and never renames or relocates it.
	FillLocationByIATA(ctx context.Context, arg FillLocationByIATAParams) (int64, error)
	FindCouponByCode(ctx context.Context, code string) (Coupon, error)
	FindCurrencyByISOName(ctx context.Context, currencyIsoName string) (Currency, error)
	GetAllLocationBrokerCodesByLocationIDs(ctx context.Context, locationIds []int64) ([]GetAllLocationBrokerCodesByLocationIDsRow, error)
	GetAllTranslationSourceTexts(ctx context.Context) ([]string, error)
	GetAllVerifiedTranslations(ctx context.Context) ([]GetAllVerifiedTranslationsRow, error)
	// Used by the markup logic to fetch rates for a given search.
	GetBrokerMarkupRateByCountryCode(ctx context.Context, arg GetBrokerMarkupRateByCountryCodeParams) (GetBrokerMarkupRateByCountryCodeRow, error)
	GetLocationBrokerCode(ctx context.Context, arg GetLocationBrokerCodeParams) (LocationBrokerCode, error)
	GetLocationByBrokerLocationID(ctx context.Context, brokerLocationID string) (Location, error)
	GetLocationById(ctx context.Context, id int64) (Location, error)
	// Unlike GetLocationIDByBrokerCode, this also finds disabled codes.
	GetLocationIDByAnyBrokerCode(ctx context.Context, arg GetLocationIDByAnyBrokerCodeParams) (int64, error)
	GetLocationIDByBrokerCode(ctx context.Context, arg GetLocationIDByBrokerCodeParams) (int64, error)
	GetLocationIDByLocationBrokerCodeID(ctx context.Context, id int64) (int64, error)
	GetLocationsByIDs(ctx context.Context, ids []int64) ([]Location, error)
	GetPriceOfferById(ctx context.Context, arg GetPriceOfferByIdParams) (GetPriceOfferByIdRow, error)
	GetPriceOfferByToken(ctx context.Context, token pgtype.UUID) (GetPriceOfferByTokenRow, error)
	GetSnapshotByID(ctx context.Context, id int64) (AvailablePlansSnapshot, error)
	InsertAvailablePlansSnapshot(ctx context.Context, arg InsertAvailablePlansSnapshotParams) (int64, error)
	InsertBrokerTranslation(ctx context.Context, sourceText string) (int64, error)
	InsertBrokerTranslationFull(ctx context.Context, arg InsertBrokerTranslationFullParams) (int64, error)
	InsertLocation(ctx context.Context, arg InsertLocationParams) (Location, error)
	InsertLocationBrokerCode(ctx context.Context, arg InsertLocationBrokerCodeParams) (LocationBrokerCode, error)
	InsertManyLocation(ctx context.Context, arg InsertManyLocationParams) ([]int64, error)
	InsertManyLocationAliases(ctx context.Context, arg InsertManyLocationAliasesParams) error
	InsertMarkupRate(ctx context.Context, arg InsertMarkupRateParams) (MarkupRate, error)
	ListAllTranslations(ctx context.Context, arg ListAllTranslationsParams) ([]BrokerTranslation, error)
	ListCoupons(ctx context.Context) ([]Coupon, error)
	ListCurrencies(ctx context.Context) ([]Currency, error)
	ListLocationAliasesByLocationIDs(ctx context.Context, locationIds []int64) ([]ListLocationAliasesByLocationIDsRow, error)
	ListLocationBrokerCodesWithLocation(ctx context.Context, arg ListLocationBrokerCodesWithLocationParams) ([]ListLocationBrokerCodesWithLocationRow, error)
	// Groups locations of the same country whose names match once everything but letters and digits
	// is stripped and case is ignored ("Athens - downtown" and "Athens Downtown").
	ListLocationMergeSuggestions(ctx context.Context) ([]ListLocationMergeSuggestionsRow, error)
	ListLocationsWithoutAliases(ctx context.Context, fromEnd bool) ([]ListLocationsWithoutAliasesRow, error)
	// Admin listing with pagination, optional filtering, and sorting.
	ListMarkupRates(ctx context.Context, arg ListMarkupRatesParams) ([]MarkupRate, error)
	ListPendingTranslations(ctx context.Context) ([]BrokerTranslation, error)
	ListPriceOffersByAgent(ctx context.Context, arg ListPriceOffersByAgentParams) ([]ListPriceOffersByAgentRow, error)
	LockLocationsForMerge(ctx context.Context, ids []int64) ([]Location, error)
	MoveLocationAliases(ctx context.Context, arg MoveLocationAliasesParams) error
	MoveLocationBrokerCodes(ctx context.Context, arg MoveLocationBrokerCodesParams) error
	MovePriceOfferLocations(ctx context.Context, arg MovePriceOfferLocationsParams) error
	RenewPriceOfferDetails(ctx context.Context, arg RenewPriceOfferDetailsParams) error
	RenewPriceOfferUnavailable(ctx context.Context, arg RenewPriceOfferUnavailableParams) error
	SearchLocations(ctx context.Context, search string) ([]SearchLocationsRow, error)
	SearchLocationsForMerge(ctx context.Context, search string) ([]Location, error)
	SetPriceOfferRenewedAt(ctx context.Context, arg SetPriceOfferRenewedAtParams) error
	ToggleIsAirport(ctx context.Context, arg ToggleIsAirportParams) error
	ToggleLocationBrokerCode(ctx context.Context, arg ToggleLocationBrokerCodeParams) error
	TranslatePendingTranslation(ctx context.Context, arg TranslatePendingTranslationParams) error
	UpdateBrokerTranslation(ctx context.Context, arg UpdateBrokerTranslationParams) error
	UpdateCoupon(ctx context.Context, arg UpdateCouponParams) (Coupon, error)
	UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error)
	UpdateLocationFields(ctx context.Context, arg UpdateLocationFieldsParams) (Location, error)
	UpdateMarkupRate(ctx context.Context, arg UpdateMarkupRateParams) (MarkupRate, error)
	UpdatePriceOffer(ctx context.Context, arg UpdatePriceOfferParams) error
	UpsertCurrencies(ctx context.Context, arg UpsertCurrenciesParams) error
	// iata is set only when no location already has it (see FillLocationByIATA), and then only on a
	// new location, which is created as an airport.
	UpsertLocationByCountryCodeName(ctx context.Context, arg UpsertLocationByCountryCodeNameParams) (int64, error)
	VerifyBrokerTranslation(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
