// Code generated by MockGen. DO NOT EDIT.
// Source: services/accounts/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=services/accounts/db/querier.go -destination=services/accounts/mocks/querier_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "encore.app/services/accounts/db"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CheckUserExists mocks base method.
func (m *MockQuerier) CheckUserExists(ctx context.Context, email string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserExists", ctx, email)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserExists indicates an expected call of CheckUserExists.
func (mr *MockQuerierMockRecorder) CheckUserExists(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserExists", reflect.TypeOf((*MockQuerier)(nil).CheckUserExists), ctx, email)
}

// CountAgents mocks base method.
func (m *MockQuerier) CountAgents(ctx context.Context, arg db.CountAgentsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAgents", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAgents indicates an expected call of CountAgents.
func (mr *MockQuerierMockRecorder) CountAgents(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAgents", reflect.TypeOf((*MockQuerier)(nil).CountAgents), ctx, arg)
}

// CountContacts mocks base method.
func (m *MockQuerier) CountContacts(ctx context.Context, arg db.CountContactsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountContacts", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountContacts indicates an expected call of CountContacts.
func (mr *MockQuerierMockRecorder) CountContacts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountContacts", reflect.TypeOf((*MockQuerier)(nil).CountContacts), ctx, arg)
}

// CountOffices mocks base method.
func (m *MockQuerier) CountOffices(ctx context.Context, arg db.CountOfficesParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOffices", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOffices indicates an expected call of CountOffices.
func (mr *MockQuerierMockRecorder) CountOffices(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOffices", reflect.TypeOf((*MockQuerier)(nil).CountOffices), ctx, arg)
}

// CountOrganizations mocks base method.
func (m *MockQuerier) CountOrganizations(ctx context.Context, arg db.CountOrganizationsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOrganizations", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOrganizations indicates an expected call of CountOrganizations.
func (mr *MockQuerierMockRecorder) CountOrganizations(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOrganizations", reflect.TypeOf((*MockQuerier)(nil).CountOrganizations), ctx, arg)
}

// CreateAgent mocks base method.
func (m *MockQuerier) CreateAgent(ctx context.Context, arg db.CreateAgentParams) (db.CreateAgentRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgent", ctx, arg)
	ret0, _ := ret[0].(db.CreateAgentRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAgent indicates an expected call of CreateAgent.
func (mr *MockQuerierMockRecorder) CreateAgent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgent", reflect.TypeOf((*MockQuerier)(nil).CreateAgent), ctx, arg)
}

// CreateContact mocks base method.
func (m *MockQuerier) CreateContact(ctx context.Context, arg db.CreateContactParams) (db.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContact", ctx, arg)
	ret0, _ := ret[0].(db.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContact indicates an expected call of CreateContact.
func (mr *MockQuerierMockRecorder) CreateContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContact", reflect.TypeOf((*MockQuerier)(nil).CreateContact), ctx, arg)
}

// CreateCustomer mocks base method.
func (m *MockQuerier) CreateCustomer(ctx context.Context, arg db.CreateCustomerParams) (db.CreateCustomerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, arg)
	ret0, _ := ret[0].(db.CreateCustomerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockQuerierMockRecorder) CreateCustomer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockQuerier)(nil).CreateCustomer), ctx, arg)
}

// CreateOffice mocks base method.
func (m *MockQuerier) CreateOffice(ctx context.Context, arg db.CreateOfficeParams) (db.Office, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOffice", ctx, arg)
	ret0, _ := ret[0].(db.Office)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOffice indicates an expected call of CreateOffice.
func (mr *MockQuerierMockRecorder) CreateOffice(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOffice", reflect.TypeOf((*MockQuerier)(nil).CreateOffice), ctx, arg)
}

// CreateOrganization mocks base method.
func (m *MockQuerier) CreateOrganization(ctx context.Context, arg db.CreateOrganizationParams) (db.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, arg)
	ret0, _ := ret[0].(db.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockQuerierMockRecorder) CreateOrganization(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockQuerier)(nil).CreateOrganization), ctx, arg)
}

// CreateStaffUser mocks base method.
func (m *MockQuerier) CreateStaffUser(ctx context.Context, arg db.CreateStaffUserParams) (db.CreateStaffUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStaffUser", ctx, arg)
	ret0, _ := ret[0].(db.CreateStaffUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStaffUser indicates an expected call of CreateStaffUser.
func (mr *MockQuerierMockRecorder) CreateStaffUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStaffUser", reflect.TypeOf((*MockQuerier)(nil).CreateStaffUser), ctx, arg)
}

// DeleteContact mocks base method.
func (m *MockQuerier) DeleteContact(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContact", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContact indicates an expected call of DeleteContact.
func (mr *MockQuerierMockRecorder) DeleteContact(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContact", reflect.TypeOf((*MockQuerier)(nil).DeleteContact), ctx, id)
}

// DeleteRefreshToken mocks base method.
func (m *MockQuerier) DeleteRefreshToken(ctx context.Context, jti string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, jti)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockQuerierMockRecorder) DeleteRefreshToken(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockQuerier)(nil).DeleteRefreshToken), ctx, jti)
}

// DeleteRefreshTokensByUserId mocks base method.
func (m *MockQuerier) DeleteRefreshTokensByUserId(ctx context.Context, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshTokensByUserId", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshTokensByUserId indicates an expected call of DeleteRefreshTokensByUserId.
func (mr *MockQuerierMockRecorder) DeleteRefreshTokensByUserId(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshTokensByUserId", reflect.TypeOf((*MockQuerier)(nil).DeleteRefreshTokensByUserId), ctx, userID)
}

// DeleteUser mocks base method.
func (m *MockQuerier) DeleteUser(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockQuerierMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockQuerier)(nil).DeleteUser), ctx, id)
}

// GetAgentsBillingContacts mocks base method.
func (m *MockQuerier) GetAgentsBillingContacts(ctx context.Context, usersIds []int32) ([]db.GetAgentsBillingContactsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentsBillingContacts", ctx, usersIds)
	ret0, _ := ret[0].([]db.GetAgentsBillingContactsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentsBillingContacts indicates an expected call of GetAgentsBillingContacts.
func (mr *MockQuerierMockRecorder) GetAgentsBillingContacts(ctx, usersIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentsBillingContacts", reflect.TypeOf((*MockQuerier)(nil).GetAgentsBillingContacts), ctx, usersIds)
}

// GetRefreshToken mocks base method.
func (m *MockQuerier) GetRefreshToken(ctx context.Context, jti string) (db.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, jti)
	ret0, _ := ret[0].(db.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockQuerierMockRecorder) GetRefreshToken(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockQuerier)(nil).GetRefreshToken), ctx, jti)
}

// GetUserByEmail mocks base method.
func (m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockQuerierMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserByEmail), ctx, email)
}

// GetUserById mocks base method.
func (m *MockQuerier) GetUserById(ctx context.Context, id int32) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, id)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockQuerierMockRecorder) GetUserById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockQuerier)(nil).GetUserById), ctx, id)
}

// GetUserByPhone mocks base method.
func (m *MockQuerier) GetUserByPhone(ctx context.Context, phoneNumber *string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPhone", ctx, phoneNumber)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPhone indicates an expected call of GetUserByPhone.
func (mr *MockQuerierMockRecorder) GetUserByPhone(ctx, phoneNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhone", reflect.TypeOf((*MockQuerier)(nil).GetUserByPhone), ctx, phoneNumber)
}

// ListAdminsEmails mocks base method.
func (m *MockQuerier) ListAdminsEmails(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdminsEmails", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdminsEmails indicates an expected call of ListAdminsEmails.
func (mr *MockQuerierMockRecorder) ListAdminsEmails(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdminsEmails", reflect.TypeOf((*MockQuerier)(nil).ListAdminsEmails), ctx)
}

// ListAgents mocks base method.
func (m *MockQuerier) ListAgents(ctx context.Context, arg db.ListAgentsParams) ([]db.ListAgentsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgents", ctx, arg)
	ret0, _ := ret[0].([]db.ListAgentsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgents indicates an expected call of ListAgents.
func (mr *MockQuerierMockRecorder) ListAgents(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgents", reflect.TypeOf((*MockQuerier)(nil).ListAgents), ctx, arg)
}

// ListContacts mocks base method.
func (m *MockQuerier) ListContacts(ctx context.Context, arg db.ListContactsParams) ([]db.ListContactsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContacts", ctx, arg)
	ret0, _ := ret[0].([]db.ListContactsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContacts indicates an expected call of ListContacts.
func (mr *MockQuerierMockRecorder) ListContacts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContacts", reflect.TypeOf((*MockQuerier)(nil).ListContacts), ctx, arg)
}

// ListOffices mocks base method.
func (m *MockQuerier) ListOffices(ctx context.Context, arg db.ListOfficesParams) ([]db.ListOfficesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOffices", ctx, arg)
	ret0, _ := ret[0].([]db.ListOfficesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOffices indicates an expected call of ListOffices.
func (mr *MockQuerierMockRecorder) ListOffices(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOffices", reflect.TypeOf((*MockQuerier)(nil).ListOffices), ctx, arg)
}

// ListOrganizations mocks base method.
func (m *MockQuerier) ListOrganizations(ctx context.Context, arg db.ListOrganizationsParams) ([]db.ListOrganizationsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", ctx, arg)
	ret0, _ := ret[0].([]db.ListOrganizationsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockQuerierMockRecorder) ListOrganizations(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockQuerier)(nil).ListOrganizations), ctx, arg)
}

// ListStaffByRole mocks base method.
func (m *MockQuerier) ListStaffByRole(ctx context.Context, role db.UserRole) ([]db.ListStaffByRoleRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStaffByRole", ctx, role)
	ret0, _ := ret[0].([]db.ListStaffByRoleRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStaffByRole indicates an expected call of ListStaffByRole.
func (mr *MockQuerierMockRecorder) ListStaffByRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStaffByRole", reflect.TypeOf((*MockQuerier)(nil).ListStaffByRole), ctx, role)
}

// SaveOTP mocks base method.
func (m *MockQuerier) SaveOTP(ctx context.Context, arg db.SaveOTPParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOTP", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOTP indicates an expected call of SaveOTP.
func (mr *MockQuerierMockRecorder) SaveOTP(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOTP", reflect.TypeOf((*MockQuerier)(nil).SaveOTP), ctx, arg)
}

// SaveRefreshToken mocks base method.
func (m *MockQuerier) SaveRefreshToken(ctx context.Context, arg db.SaveRefreshTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRefreshToken indicates an expected call of SaveRefreshToken.
func (mr *MockQuerierMockRecorder) SaveRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshToken", reflect.TypeOf((*MockQuerier)(nil).SaveRefreshToken), ctx, arg)
}

// UpdateContact mocks base method.
func (m *MockQuerier) UpdateContact(ctx context.Context, arg db.UpdateContactParams) (db.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContact", ctx, arg)
	ret0, _ := ret[0].(db.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContact indicates an expected call of UpdateContact.
func (mr *MockQuerierMockRecorder) UpdateContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContact", reflect.TypeOf((*MockQuerier)(nil).UpdateContact), ctx, arg)
}

// UpdateOffice mocks base method.
func (m *MockQuerier) UpdateOffice(ctx context.Context, arg db.UpdateOfficeParams) (db.Office, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOffice", ctx, arg)
	ret0, _ := ret[0].(db.Office)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOffice indicates an expected call of UpdateOffice.
func (mr *MockQuerierMockRecorder) UpdateOffice(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOffice", reflect.TypeOf((*MockQuerier)(nil).UpdateOffice), ctx, arg)
}

// UpdateOrganization mocks base method.
func (m *MockQuerier) UpdateOrganization(ctx context.Context, arg db.UpdateOrganizationParams) (db.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganization", ctx, arg)
	ret0, _ := ret[0].(db.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganization indicates an expected call of UpdateOrganization.
func (mr *MockQuerierMockRecorder) UpdateOrganization(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganization", reflect.TypeOf((*MockQuerier)(nil).UpdateOrganization), ctx, arg)
}

// UpdateUser mocks base method.
func (m *MockQuerier) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.UpdateUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, arg)
	ret0, _ := ret[0].(db.UpdateUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockQuerierMockRecorder) UpdateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockQuerier)(nil).UpdateUser), ctx, arg)
}
