/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    media: Media;
    'addon-images': AddonImage;
    pages: Page;
    sharedSections: SharedSection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'addon-images': AddonImagesSelect<false> | AddonImagesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    sharedSections: SharedSectionsSelect<false> | SharedSectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('he' | 'en') | ('he' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'he' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  userId: string;
  username: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addon-images".
 */
export interface AddonImage {
  id: number;
  addonId: string;
  englishName: string;
  hebrewName: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * הגדירו slug שונה לכל שפה. עמוד הבית ישמר כ-"home" ב-Payload ויומף ל-"/" ב-Next.js.
   */
  slug: string;
  /**
   * תיאור קצר לכרטיסיות ותוצאות חיפוש, עד 220 תווים.
   */
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  layout?: (RichTextBlock | FAQBlock | SharedSectionRefBlock | SidebarSectionBlock)[] | null;
  includeBgDecorations?: boolean | null;
  template: 'default' | 'landing' | 'about' | 'faq' | 'legal' | 'help';
  relatedPages?: (number | Page)[] | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  maxWidth: 'sm' | 'md' | 'lg' | 'full';
  textAlign?: ('start' | 'center' | 'end') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  eyebrow?: string | null;
  title?: string | null;
  subtitle?: string | null;
  /**
   * כל קטגוריה מציגה כותרת וקבוצת שאלות-תשובות. לדוגמה: "לפני ההשכרה".
   */
  categories?:
    | {
        /**
         * לדוגמה: לפני ההשכרה / בזמן ההשכרה / אחרי ההשכרה. ניתן להשאיר ריק אם אין קטגוריות.
         */
        heading?: string | null;
        items?:
          | {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SharedSectionRefBlock".
 */
export interface SharedSectionRefBlock {
  /**
   * בחרו אזור קיים מהספרייה המשותפת (ניוזלטר, חברות השכרה, סטטיסטיקות וכד׳).
   */
  section: number | SharedSection;
  /**
   * שינויים חזותיים לעמוד הזה בלבד, מבלי לפגוע באזור המשותף.
   */
  overrides?: {
    spacingTop?: ('default' | 'none' | 'sm' | 'md' | 'lg') | null;
    spacingBottom?: ('default' | 'none' | 'sm' | 'md' | 'lg') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'sharedSectionRef';
}
/**
 * אזורים שניתן לשלב בכל עמוד או בדף הבית. עריכה כאן תשתקף בכל מקום שהאזור מוטמע.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sharedSections".
 */
export interface SharedSection {
  id: number;
  /**
   * שם לזיהוי בממשק הניהול בלבד. לא מוצג בפרונטאנד.
   */
  internalTitle: string;
  /**
   * בחרו את סוג האזור. הבחירה קובעת אילו שדות יוצגו.
   */
  type: 'newsletter' | 'suppliers' | 'stats';
  newsletter?: {
    title: string;
    subtitle?: string | null;
    /**
     * רשימת bullets שתוצג לצד הטופס.
     */
    benefits?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    formTitle?: string | null;
    formSubTitle?: string | null;
    emailPlaceholder?: string | null;
    submitButtonLabel: string;
    consentLabel?: string | null;
    privacyTextBeforeLink?: string | null;
    privacyLinkLabel?: string | null;
    privacyPage?: (number | null) | Page;
  };
  suppliers?: {
    /**
     * לדוגמה: "השותפים שלנו"
     */
    pillText?: string | null;
    /**
     * לדוגמה: "חברות ההשכרה המובילות בעולם"
     */
    title: string;
    subtitle?: string | null;
    /**
     * לוגו לכל חברת השכרה. השתמשו ב-SVG או PNG שקוף.
     */
    logos?:
      | {
          logo: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  stats?: {
    pillText?: string | null;
    title: string;
    subtitle?: string | null;
    items?:
      | {
          /**
           * לדוגמה: "+20,000", "4.9", "אלפי"
           */
          value: string;
          /**
           * לדוגמה: "הזמנות", "דירוג לקוחות", "יעדים"
           */
          label: string;
          /**
           * אופציונלי: תמונה/אייקון SVG לצד הנתון.
           */
          icon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SidebarSectionBlock".
 */
export interface SidebarSectionBlock {
  sections?:
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sidebarSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'addon-images';
        value: number | AddonImage;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'sharedSections';
        value: number | SharedSection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  userId?: T;
  username?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addon-images_select".
 */
export interface AddonImagesSelect<T extends boolean = true> {
  addonId?: T;
  englishName?: T;
  hebrewName?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  layout?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        sharedSectionRef?: T | SharedSectionRefBlockSelect<T>;
        sidebarSection?: T | SidebarSectionBlockSelect<T>;
      };
  includeBgDecorations?: T;
  template?: T;
  relatedPages?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  maxWidth?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  categories?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SharedSectionRefBlock_select".
 */
export interface SharedSectionRefBlockSelect<T extends boolean = true> {
  section?: T;
  overrides?:
    | T
    | {
        spacingTop?: T;
        spacingBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SidebarSectionBlock_select".
 */
export interface SidebarSectionBlockSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sharedSections_select".
 */
export interface SharedSectionsSelect<T extends boolean = true> {
  internalTitle?: T;
  type?: T;
  newsletter?:
    | T
    | {
        title?: T;
        subtitle?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
        formTitle?: T;
        formSubTitle?: T;
        emailPlaceholder?: T;
        submitButtonLabel?: T;
        consentLabel?: T;
        privacyTextBeforeLink?: T;
        privacyLinkLabel?: T;
        privacyPage?: T;
      };
  suppliers?:
    | T
    | {
        pillText?: T;
        title?: T;
        subtitle?: T;
        logos?:
          | T
          | {
              logo?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        pillText?: T;
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  links?:
    | {
        type: 'link' | 'mega';
        label?: string | null;
        page?: (number | null) | Page;
        megaLabel?: string | null;
        megaLinks?:
          | {
              label: string;
              page: number | Page;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  firstFloorLinks?:
    | {
        label: string;
        page: number | Page;
        id?: string | null;
      }[]
    | null;
  socialsTitle?: string | null;
  socialsLinks?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  linkGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              page: number | Page;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  thirdFloorLinks?:
    | {
        label: string;
        page: number | Page;
        id?: string | null;
      }[]
    | null;
  rights?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  links?:
    | T
    | {
        type?: T;
        label?: T;
        page?: T;
        megaLabel?: T;
        megaLinks?:
          | T
          | {
              label?: T;
              page?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  firstFloorLinks?:
    | T
    | {
        label?: T;
        page?: T;
        id?: T;
      };
  socialsTitle?: T;
  socialsLinks?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  linkGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              page?: T;
              id?: T;
            };
        id?: T;
      };
  thirdFloorLinks?:
    | T
    | {
        label?: T;
        page?: T;
        id?: T;
      };
  rights?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}