// Code generated by MockGen. DO NOT EDIT.
// Source: services/reservation/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=services/reservation/db/querier.go -destination=services/reservation/mocks/querier_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "encore.app/services/reservation/db"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// ApplyVoucher mocks base method.
func (m *MockQuerier) ApplyVoucher(ctx context.Context, arg db.ApplyVoucherParams) (db.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyVoucher", ctx, arg)
	ret0, _ := ret[0].(db.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyVoucher indicates an expected call of ApplyVoucher.
func (mr *MockQuerierMockRecorder) ApplyVoucher(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyVoucher", reflect.TypeOf((*MockQuerier)(nil).ApplyVoucher), ctx, arg)
}

// CancelReservation mocks base method.
func (m *MockQuerier) CancelReservation(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelReservation", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelReservation indicates an expected call of CancelReservation.
func (mr *MockQuerierMockRecorder) CancelReservation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelReservation", reflect.TypeOf((*MockQuerier)(nil).CancelReservation), ctx, id)
}

// CountReservationsByUser mocks base method.
func (m *MockQuerier) CountReservationsByUser(ctx context.Context, arg db.CountReservationsByUserParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountReservationsByUser", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountReservationsByUser indicates an expected call of CountReservationsByUser.
func (mr *MockQuerierMockRecorder) CountReservationsByUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountReservationsByUser", reflect.TypeOf((*MockQuerier)(nil).CountReservationsByUser), ctx, arg)
}

// CountReservationsReport mocks base method.
func (m *MockQuerier) CountReservationsReport(ctx context.Context, arg db.CountReservationsReportParams) (db.CountReservationsReportRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountReservationsReport", ctx, arg)
	ret0, _ := ret[0].(db.CountReservationsReportRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountReservationsReport indicates an expected call of CountReservationsReport.
func (mr *MockQuerierMockRecorder) CountReservationsReport(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountReservationsReport", reflect.TypeOf((*MockQuerier)(nil).CountReservationsReport), ctx, arg)
}

// GetBillingReservation mocks base method.
func (m *MockQuerier) GetBillingReservation(ctx context.Context, id int64) (db.GetBillingReservationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBillingReservation", ctx, id)
	ret0, _ := ret[0].(db.GetBillingReservationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBillingReservation indicates an expected call of GetBillingReservation.
func (mr *MockQuerierMockRecorder) GetBillingReservation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBillingReservation", reflect.TypeOf((*MockQuerier)(nil).GetBillingReservation), ctx, id)
}

// GetOpenReservationsPickingUpWithinWeek mocks base method.
func (m *MockQuerier) GetOpenReservationsPickingUpWithinWeek(ctx context.Context) ([]db.GetOpenReservationsPickingUpWithinWeekRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenReservationsPickingUpWithinWeek", ctx)
	ret0, _ := ret[0].([]db.GetOpenReservationsPickingUpWithinWeekRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenReservationsPickingUpWithinWeek indicates an expected call of GetOpenReservationsPickingUpWithinWeek.
func (mr *MockQuerierMockRecorder) GetOpenReservationsPickingUpWithinWeek(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenReservationsPickingUpWithinWeek", reflect.TypeOf((*MockQuerier)(nil).GetOpenReservationsPickingUpWithinWeek), ctx)
}

// GetOutboxByTopic mocks base method.
func (m *MockQuerier) GetOutboxByTopic(ctx context.Context, topic string) ([]db.Outbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutboxByTopic", ctx, topic)
	ret0, _ := ret[0].([]db.Outbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutboxByTopic indicates an expected call of GetOutboxByTopic.
func (mr *MockQuerierMockRecorder) GetOutboxByTopic(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutboxByTopic", reflect.TypeOf((*MockQuerier)(nil).GetOutboxByTopic), ctx, topic)
}

// GetPaymentPendingReservations mocks base method.
func (m *MockQuerier) GetPaymentPendingReservations(ctx context.Context) ([]db.GetPaymentPendingReservationsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentPendingReservations", ctx)
	ret0, _ := ret[0].([]db.GetPaymentPendingReservationsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentPendingReservations indicates an expected call of GetPaymentPendingReservations.
func (mr *MockQuerierMockRecorder) GetPaymentPendingReservations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentPendingReservations", reflect.TypeOf((*MockQuerier)(nil).GetPaymentPendingReservations), ctx)
}

// GetPaymentPendingReservationsByBillingEntity mocks base method.
func (m *MockQuerier) GetPaymentPendingReservationsByBillingEntity(ctx context.Context, arg db.GetPaymentPendingReservationsByBillingEntityParams) ([]db.GetPaymentPendingReservationsByBillingEntityRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentPendingReservationsByBillingEntity", ctx, arg)
	ret0, _ := ret[0].([]db.GetPaymentPendingReservationsByBillingEntityRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentPendingReservationsByBillingEntity indicates an expected call of GetPaymentPendingReservationsByBillingEntity.
func (mr *MockQuerierMockRecorder) GetPaymentPendingReservationsByBillingEntity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentPendingReservationsByBillingEntity", reflect.TypeOf((*MockQuerier)(nil).GetPaymentPendingReservationsByBillingEntity), ctx, arg)
}

// GetReservationByID mocks base method.
func (m *MockQuerier) GetReservationByID(ctx context.Context, id int64) (db.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservationByID", ctx, id)
	ret0, _ := ret[0].(db.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReservationByID indicates an expected call of GetReservationByID.
func (mr *MockQuerierMockRecorder) GetReservationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservationByID", reflect.TypeOf((*MockQuerier)(nil).GetReservationByID), ctx, id)
}

// GetReservationCurrencyCode mocks base method.
func (m *MockQuerier) GetReservationCurrencyCode(ctx context.Context, id int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservationCurrencyCode", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReservationCurrencyCode indicates an expected call of GetReservationCurrencyCode.
func (mr *MockQuerierMockRecorder) GetReservationCurrencyCode(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservationCurrencyCode", reflect.TypeOf((*MockQuerier)(nil).GetReservationCurrencyCode), ctx, id)
}

// InsertReservation mocks base method.
func (m *MockQuerier) InsertReservation(ctx context.Context, arg db.InsertReservationParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertReservation", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertReservation indicates an expected call of InsertReservation.
func (mr *MockQuerierMockRecorder) InsertReservation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertReservation", reflect.TypeOf((*MockQuerier)(nil).InsertReservation), ctx, arg)
}

// ListBusinessesBalancesReport mocks base method.
func (m *MockQuerier) ListBusinessesBalancesReport(ctx context.Context) ([]db.ListBusinessesBalancesReportRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBusinessesBalancesReport", ctx)
	ret0, _ := ret[0].([]db.ListBusinessesBalancesReportRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBusinessesBalancesReport indicates an expected call of ListBusinessesBalancesReport.
func (mr *MockQuerierMockRecorder) ListBusinessesBalancesReport(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBusinessesBalancesReport", reflect.TypeOf((*MockQuerier)(nil).ListBusinessesBalancesReport), ctx)
}

// ListReservationsByUser mocks base method.
func (m *MockQuerier) ListReservationsByUser(ctx context.Context, arg db.ListReservationsByUserParams) ([]db.ListReservationsByUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReservationsByUser", ctx, arg)
	ret0, _ := ret[0].([]db.ListReservationsByUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReservationsByUser indicates an expected call of ListReservationsByUser.
func (mr *MockQuerierMockRecorder) ListReservationsByUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReservationsByUser", reflect.TypeOf((*MockQuerier)(nil).ListReservationsByUser), ctx, arg)
}

// ListReservationsReport mocks base method.
func (m *MockQuerier) ListReservationsReport(ctx context.Context, arg db.ListReservationsReportParams) ([]db.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReservationsReport", ctx, arg)
	ret0, _ := ret[0].([]db.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReservationsReport indicates an expected call of ListReservationsReport.
func (mr *MockQuerierMockRecorder) ListReservationsReport(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReservationsReport", reflect.TypeOf((*MockQuerier)(nil).ListReservationsReport), ctx, arg)
}

// ResolveReservationsPayment mocks base method.
func (m *MockQuerier) ResolveReservationsPayment(ctx context.Context, ids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveReservationsPayment", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveReservationsPayment indicates an expected call of ResolveReservationsPayment.
func (mr *MockQuerierMockRecorder) ResolveReservationsPayment(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveReservationsPayment", reflect.TypeOf((*MockQuerier)(nil).ResolveReservationsPayment), ctx, ids)
}

// VoucherReservationAfterPayment mocks base method.
func (m *MockQuerier) VoucherReservationAfterPayment(ctx context.Context, arg db.VoucherReservationAfterPaymentParams) (db.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VoucherReservationAfterPayment", ctx, arg)
	ret0, _ := ret[0].(db.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VoucherReservationAfterPayment indicates an expected call of VoucherReservationAfterPayment.
func (mr *MockQuerierMockRecorder) VoucherReservationAfterPayment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoucherReservationAfterPayment", reflect.TypeOf((*MockQuerier)(nil).VoucherReservationAfterPayment), ctx, arg)
}
