// Code generated by MockGen. DO NOT EDIT.
// Source: services/reservation/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=services/reservation/db/querier.go -destination=services/reservation/mocks/querier_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "encore.app/services/reservation/db"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// ApplyVoucher mocks base method.
func (m *MockQuerier) ApplyVoucher(ctx context.Context, arg db.ApplyVoucherParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyVoucher", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyVoucher indicates an expected call of ApplyVoucher.
func (mr *MockQuerierMockRecorder) ApplyVoucher(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyVoucher", reflect.TypeOf((*MockQuerier)(nil).ApplyVoucher), ctx, arg)
}

// CancelReservation mocks base method.
func (m *MockQuerier) CancelReservation(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelReservation", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelReservation indicates an expected call of CancelReservation.
func (mr *MockQuerierMockRecorder) CancelReservation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelReservation", reflect.TypeOf((*MockQuerier)(nil).CancelReservation), ctx, id)
}

// CountReservationsByUser mocks base method.
func (m *MockQuerier) CountReservationsByUser(ctx context.Context, arg db.CountReservationsByUserParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountReservationsByUser", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountReservationsByUser indicates an expected call of CountReservationsByUser.
func (mr *MockQuerierMockRecorder) CountReservationsByUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountReservationsByUser", reflect.TypeOf((*MockQuerier)(nil).CountReservationsByUser), ctx, arg)
}

// GetReservationByID mocks base method.
func (m *MockQuerier) GetReservationByID(ctx context.Context, id int64) (db.GetReservationByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservationByID", ctx, id)
	ret0, _ := ret[0].(db.GetReservationByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReservationByID indicates an expected call of GetReservationByID.
func (mr *MockQuerierMockRecorder) GetReservationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservationByID", reflect.TypeOf((*MockQuerier)(nil).GetReservationByID), ctx, id)
}

// InsertReservation mocks base method.
func (m *MockQuerier) InsertReservation(ctx context.Context, arg db.InsertReservationParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertReservation", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertReservation indicates an expected call of InsertReservation.
func (mr *MockQuerierMockRecorder) InsertReservation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertReservation", reflect.TypeOf((*MockQuerier)(nil).InsertReservation), ctx, arg)
}

// ListReservationsByUser mocks base method.
func (m *MockQuerier) ListReservationsByUser(ctx context.Context, arg db.ListReservationsByUserParams) ([]db.ListReservationsByUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReservationsByUser", ctx, arg)
	ret0, _ := ret[0].([]db.ListReservationsByUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReservationsByUser indicates an expected call of ListReservationsByUser.
func (mr *MockQuerierMockRecorder) ListReservationsByUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReservationsByUser", reflect.TypeOf((*MockQuerier)(nil).ListReservationsByUser), ctx, arg)
}
