import type { Metadata } from "next";
import {
  SUPPORTED_LANGS,
  type SupportedLang,
} from "@/shared/constants/supported_langs";
import { absoluteUrl } from "./site";

/** Matches `localization.defaultLocale` in payload.config.ts. */
export const DEFAULT_LANG: SupportedLang = "he";

/**
 * Shape of a localized field fetched with `locale: "all"`.
 *
 * Payload's `localization.fallback` defaults to `true`, so a normal
 * `locale: "en"` fetch silently returns the Hebrew value for an untranslated
 * doc. `locale: "all"` returns the raw per-locale values and applies no
 * fallback — it is the only reliable way to tell "translated" from "fell back".
 */
export type LocalizedValue<T = string> = Partial<Record<SupportedLang, T | null>>;

/** True when `lang` has its own value, rather than falling back to Hebrew. */
export function hasTranslation(
  value: LocalizedValue | undefined,
  lang: SupportedLang,
): boolean {
  const raw = value?.[lang];
  return typeof raw === "string" && raw.trim().length > 0;
}

/**
 * Builds a locale-prefixed path, percent-encoding each segment.
 *
 * Slugs are generated by `slugify` in CMS/collections/Pages.ts, which preserves
 * `\p{L}` — Hebrew slugs are real Hebrew and must be encoded in URLs. The
 * routes `decodeURIComponent` them on the way back in.
 */
export function localePath(lang: SupportedLang, ...segments: string[]): string {
  const encoded = segments.filter(Boolean).map(encodeURIComponent);
  return encoded.length ? `/${lang}/${encoded.join("/")}` : `/${lang}`;
}

/**
 * Locale → path for a doc's localized slug, skipping locales with no real
 * translation. Shared by the sitemap and by each route's `generateMetadata` so
 * both agree on which URLs are genuine translations.
 */
export function localizedPaths(
  slug: LocalizedValue | undefined,
  build: (lang: SupportedLang, slug: string) => string,
): Partial<Record<SupportedLang, string>> {
  const paths: Partial<Record<SupportedLang, string>> = {};
  for (const lang of SUPPORTED_LANGS) {
    if (!hasTranslation(slug, lang)) continue;
    paths[lang] = build(lang, slug![lang]!.trim());
  }
  return paths;
}

/**
 * Canonical + hreflang for one page.
 *
 * `pathByLang` should omit any locale that has no real translation. Two things
 * follow from that automatically:
 *  - an untranslated `/en/…` URL canonicals to its Hebrew original instead of
 *    competing with it as duplicate content;
 *  - no hreflang is declared for a locale that would really serve Hebrew.
 */
export function buildAlternates(
  lang: SupportedLang,
  pathByLang: Partial<Record<SupportedLang, string>>,
): Metadata["alternates"] {
  const canonicalPath = pathByLang[lang] ?? pathByLang[DEFAULT_LANG];
  if (!canonicalPath) return undefined;

  const translated = SUPPORTED_LANGS.filter((code) => pathByLang[code]);

  // With a single translation there is nothing to cross-reference.
  if (translated.length < 2) {
    return { canonical: absoluteUrl(canonicalPath) };
  }

  const languages: Record<string, string> = {};
  for (const code of translated) {
    languages[code] = absoluteUrl(pathByLang[code]!);
  }
  languages["x-default"] =
    languages[DEFAULT_LANG] ?? absoluteUrl(pathByLang[translated[0]]!);

  return { canonical: absoluteUrl(canonicalPath), languages };
}
