// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: location_supplier_codes_query.sql

package db

import (
	"context"
)

const getLocationSupplierCode = `-- name: GetLocationSupplierCode :one
SELECT
  id,
  location_id,
  supplier,
  supplier_location_id,
  enabled,
  created_at,
  updated_at
FROM
  location_supplier_codes
WHERE
  (
    supplier = $1
    AND supplier_location_id = $2
  )
  OR (
    location_id = $3
    AND supplier = $1
  )
LIMIT 1
`

type GetLocationSupplierCodeParams struct {
	Supplier           Supplier
	SupplierLocationID string
	LocationID         int64
}

func (q *Queries) GetLocationSupplierCode(ctx context.Context, arg GetLocationSupplierCodeParams) (LocationSupplierCode, error) {
	row := q.db.QueryRow(ctx, getLocationSupplierCode, arg.Supplier, arg.SupplierLocationID, arg.LocationID)
	var i LocationSupplierCode
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Supplier,
		&i.SupplierLocationID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLocationSupplierCode = `-- name: InsertLocationSupplierCode :one
INSERT INTO
  location_supplier_codes (location_id, supplier, supplier_location_id)
VALUES
  (
    $1,
    $2,
    $3
  ) RETURNING id,
  location_id,
  supplier,
  supplier_location_id,
  enabled,
  created_at,
  updated_at
`

type InsertLocationSupplierCodeParams struct {
	LocationID         int64
	Supplier           Supplier
	SupplierLocationID string
}

func (q *Queries) InsertLocationSupplierCode(ctx context.Context, arg InsertLocationSupplierCodeParams) (LocationSupplierCode, error) {
	row := q.db.QueryRow(ctx, insertLocationSupplierCode, arg.LocationID, arg.Supplier, arg.SupplierLocationID)
	var i LocationSupplierCode
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Supplier,
		&i.SupplierLocationID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
