// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: locations_query.sql

package db

import (
	"context"
)

const upsertLocationByCountryCodeName = `-- name: UpsertLocationByCountryCodeName :one
INSERT INTO locations (country, country_code, city, name, iata)
VALUES (
  NULLIF($1, '')::text,
  NULLIF($2, '')::text,
  NULLIF($3, '')::text,
  $4::text,
  NULL
)
ON CONFLICT (country_code, lower(name))
DO UPDATE SET
  country      = EXCLUDED.country,
  country_code = EXCLUDED.country_code,
  city         = EXCLUDED.city,
  name         = EXCLUDED.name,
  updated_at   = now()
RETURNING id
`

type UpsertLocationByCountryCodeNameParams struct {
	Country     interface{}
	CountryCode interface{}
	City        interface{}
	Name        string
}

func (q *Queries) UpsertLocationByCountryCodeName(ctx context.Context, arg UpsertLocationByCountryCodeNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertLocationByCountryCodeName,
		arg.Country,
		arg.CountryCode,
		arg.City,
		arg.Name,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertLocationByIATA = `-- name: UpsertLocationByIATA :one
INSERT INTO locations (country, country_code, city, name, iata)
VALUES (
  NULLIF($1, '')::text,
  NULLIF($2, '')::text,
  NULLIF($3, '')::text,
  $4::text,
  NULLIF(upper($5), '')::char(3)
)
ON CONFLICT (iata) WHERE iata IS NOT NULL
DO UPDATE SET
  country      = EXCLUDED.country,
  country_code = EXCLUDED.country_code,
  city         = EXCLUDED.city,
  name         = EXCLUDED.name,
  updated_at   = now()
RETURNING id
`

type UpsertLocationByIATAParams struct {
	Country     interface{}
	CountryCode interface{}
	City        interface{}
	Name        string
	Iata        interface{}
}

func (q *Queries) UpsertLocationByIATA(ctx context.Context, arg UpsertLocationByIATAParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertLocationByIATA,
		arg.Country,
		arg.CountryCode,
		arg.City,
		arg.Name,
		arg.Iata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
