// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Supplier string

const (
	SupplierFlex  Supplier = "flex"
	SupplierHertz Supplier = "hertz"
)

func (e *Supplier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Supplier(s)
	case string:
		*e = Supplier(s)
	default:
		return fmt.Errorf("unsupported scan type for Supplier: %T", src)
	}
	return nil
}

type NullSupplier struct {
	Supplier Supplier
	Valid    bool // Valid is true if Supplier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSupplier) Scan(value interface{}) error {
	if value == nil {
		ns.Supplier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Supplier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSupplier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Supplier), nil
}

type Location struct {
	ID          int64
	Country     string
	CountryCode string
	City        string
	Name        string
	Iata        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type LocationSupplierCode struct {
	ID                 int64
	LocationID         int64
	Supplier           Supplier
	SupplierLocationID string
	Enabled            bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
