// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetLocationSupplierCode(ctx context.Context, arg GetLocationSupplierCodeParams) (LocationSupplierCode, error)
	InsertLocationSupplierCode(ctx context.Context, arg InsertLocationSupplierCodeParams) (LocationSupplierCode, error)
	UpsertLocationByCountryCodeName(ctx context.Context, arg UpsertLocationByCountryCodeNameParams) (int64, error)
	UpsertLocationByIATA(ctx context.Context, arg UpsertLocationByIATAParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
