// Code generated by MockGen. DO NOT EDIT.
// Source: services/booking/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=services/booking/db/querier.go -destination=services/booking/mocks/querier_mock.go -package=locations_mocks
//

// Package locations_mocks is a generated GoMock package.
package locations_mocks

import (
	context "context"
	reflect "reflect"

	db "encore.app/services/booking/db"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CheckBrokerTranslationExists mocks base method.
func (m *MockQuerier) CheckBrokerTranslationExists(ctx context.Context, sourceText string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBrokerTranslationExists", ctx, sourceText)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBrokerTranslationExists indicates an expected call of CheckBrokerTranslationExists.
func (mr *MockQuerierMockRecorder) CheckBrokerTranslationExists(ctx, sourceText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBrokerTranslationExists", reflect.TypeOf((*MockQuerier)(nil).CheckBrokerTranslationExists), ctx, sourceText)
}

// CountAllTranslations mocks base method.
func (m *MockQuerier) CountAllTranslations(ctx context.Context, arg db.CountAllTranslationsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAllTranslations", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAllTranslations indicates an expected call of CountAllTranslations.
func (mr *MockQuerierMockRecorder) CountAllTranslations(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAllTranslations", reflect.TypeOf((*MockQuerier)(nil).CountAllTranslations), ctx, arg)
}

// CountHertzMarkupRates mocks base method.
func (m *MockQuerier) CountHertzMarkupRates(ctx context.Context, arg db.CountHertzMarkupRatesParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountHertzMarkupRates", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountHertzMarkupRates indicates an expected call of CountHertzMarkupRates.
func (mr *MockQuerierMockRecorder) CountHertzMarkupRates(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountHertzMarkupRates", reflect.TypeOf((*MockQuerier)(nil).CountHertzMarkupRates), ctx, arg)
}

// CountLocationBrokerCodesByLocationID mocks base method.
func (m *MockQuerier) CountLocationBrokerCodesByLocationID(ctx context.Context, locationID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLocationBrokerCodesByLocationID", ctx, locationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLocationBrokerCodesByLocationID indicates an expected call of CountLocationBrokerCodesByLocationID.
func (mr *MockQuerierMockRecorder) CountLocationBrokerCodesByLocationID(ctx, locationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLocationBrokerCodesByLocationID", reflect.TypeOf((*MockQuerier)(nil).CountLocationBrokerCodesByLocationID), ctx, locationID)
}

// CountLocationBrokerCodesWithLocation mocks base method.
func (m *MockQuerier) CountLocationBrokerCodesWithLocation(ctx context.Context, arg db.CountLocationBrokerCodesWithLocationParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLocationBrokerCodesWithLocation", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLocationBrokerCodesWithLocation indicates an expected call of CountLocationBrokerCodesWithLocation.
func (mr *MockQuerierMockRecorder) CountLocationBrokerCodesWithLocation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLocationBrokerCodesWithLocation", reflect.TypeOf((*MockQuerier)(nil).CountLocationBrokerCodesWithLocation), ctx, arg)
}

// CreateCoupon mocks base method.
func (m *MockQuerier) CreateCoupon(ctx context.Context, arg db.CreateCouponParams) (db.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCoupon", ctx, arg)
	ret0, _ := ret[0].(db.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCoupon indicates an expected call of CreateCoupon.
func (mr *MockQuerierMockRecorder) CreateCoupon(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCoupon", reflect.TypeOf((*MockQuerier)(nil).CreateCoupon), ctx, arg)
}

// CreateCurrency mocks base method.
func (m *MockQuerier) CreateCurrency(ctx context.Context, arg db.CreateCurrencyParams) (db.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCurrency", ctx, arg)
	ret0, _ := ret[0].(db.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCurrency indicates an expected call of CreateCurrency.
func (mr *MockQuerierMockRecorder) CreateCurrency(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCurrency", reflect.TypeOf((*MockQuerier)(nil).CreateCurrency), ctx, arg)
}

// DeleteBrokerTranslation mocks base method.
func (m *MockQuerier) DeleteBrokerTranslation(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBrokerTranslation", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBrokerTranslation indicates an expected call of DeleteBrokerTranslation.
func (mr *MockQuerierMockRecorder) DeleteBrokerTranslation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBrokerTranslation", reflect.TypeOf((*MockQuerier)(nil).DeleteBrokerTranslation), ctx, id)
}

// DeleteCoupon mocks base method.
func (m *MockQuerier) DeleteCoupon(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCoupon", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCoupon indicates an expected call of DeleteCoupon.
func (mr *MockQuerierMockRecorder) DeleteCoupon(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCoupon", reflect.TypeOf((*MockQuerier)(nil).DeleteCoupon), ctx, id)
}

// DeleteCurrency mocks base method.
func (m *MockQuerier) DeleteCurrency(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCurrency", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCurrency indicates an expected call of DeleteCurrency.
func (mr *MockQuerierMockRecorder) DeleteCurrency(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCurrency", reflect.TypeOf((*MockQuerier)(nil).DeleteCurrency), ctx, id)
}

// DeleteHertzMarkupRate mocks base method.
func (m *MockQuerier) DeleteHertzMarkupRate(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHertzMarkupRate", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteHertzMarkupRate indicates an expected call of DeleteHertzMarkupRate.
func (mr *MockQuerierMockRecorder) DeleteHertzMarkupRate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHertzMarkupRate", reflect.TypeOf((*MockQuerier)(nil).DeleteHertzMarkupRate), ctx, id)
}

// DeleteLocationBrokerCode mocks base method.
func (m *MockQuerier) DeleteLocationBrokerCode(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLocationBrokerCode", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLocationBrokerCode indicates an expected call of DeleteLocationBrokerCode.
func (mr *MockQuerierMockRecorder) DeleteLocationBrokerCode(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLocationBrokerCode", reflect.TypeOf((*MockQuerier)(nil).DeleteLocationBrokerCode), ctx, id)
}

// DeleteLocationByID mocks base method.
func (m *MockQuerier) DeleteLocationByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLocationByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLocationByID indicates an expected call of DeleteLocationByID.
func (mr *MockQuerierMockRecorder) DeleteLocationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLocationByID", reflect.TypeOf((*MockQuerier)(nil).DeleteLocationByID), ctx, id)
}

// DeleteOldAvailablePlansSnapshots mocks base method.
func (m *MockQuerier) DeleteOldAvailablePlansSnapshots(ctx context.Context, createdAt pgtype.Timestamptz) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldAvailablePlansSnapshots", ctx, createdAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldAvailablePlansSnapshots indicates an expected call of DeleteOldAvailablePlansSnapshots.
func (mr *MockQuerierMockRecorder) DeleteOldAvailablePlansSnapshots(ctx, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldAvailablePlansSnapshots", reflect.TypeOf((*MockQuerier)(nil).DeleteOldAvailablePlansSnapshots), ctx, createdAt)
}

// DeleteSnapshotByID mocks base method.
func (m *MockQuerier) DeleteSnapshotByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshotByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSnapshotByID indicates an expected call of DeleteSnapshotByID.
func (mr *MockQuerierMockRecorder) DeleteSnapshotByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshotByID", reflect.TypeOf((*MockQuerier)(nil).DeleteSnapshotByID), ctx, id)
}

// DisableLocationBrokerCode mocks base method.
func (m *MockQuerier) DisableLocationBrokerCode(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableLocationBrokerCode", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableLocationBrokerCode indicates an expected call of DisableLocationBrokerCode.
func (mr *MockQuerierMockRecorder) DisableLocationBrokerCode(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableLocationBrokerCode", reflect.TypeOf((*MockQuerier)(nil).DisableLocationBrokerCode), ctx, id)
}

// EnableLocationBrokerCode mocks base method.
func (m *MockQuerier) EnableLocationBrokerCode(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableLocationBrokerCode", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableLocationBrokerCode indicates an expected call of EnableLocationBrokerCode.
func (mr *MockQuerierMockRecorder) EnableLocationBrokerCode(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableLocationBrokerCode", reflect.TypeOf((*MockQuerier)(nil).EnableLocationBrokerCode), ctx, id)
}

// FindCouponByCode mocks base method.
func (m *MockQuerier) FindCouponByCode(ctx context.Context, code string) (db.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCouponByCode", ctx, code)
	ret0, _ := ret[0].(db.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCouponByCode indicates an expected call of FindCouponByCode.
func (mr *MockQuerierMockRecorder) FindCouponByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCouponByCode", reflect.TypeOf((*MockQuerier)(nil).FindCouponByCode), ctx, code)
}

// FindCurrencyByISOName mocks base method.
func (m *MockQuerier) FindCurrencyByISOName(ctx context.Context, currencyIsoName string) (db.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCurrencyByISOName", ctx, currencyIsoName)
	ret0, _ := ret[0].(db.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCurrencyByISOName indicates an expected call of FindCurrencyByISOName.
func (mr *MockQuerierMockRecorder) FindCurrencyByISOName(ctx, currencyIsoName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCurrencyByISOName", reflect.TypeOf((*MockQuerier)(nil).FindCurrencyByISOName), ctx, currencyIsoName)
}

// GetAllLocationBrokerCodesByLocationIDs mocks base method.
func (m *MockQuerier) GetAllLocationBrokerCodesByLocationIDs(ctx context.Context, locationIds []int64) ([]db.GetAllLocationBrokerCodesByLocationIDsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLocationBrokerCodesByLocationIDs", ctx, locationIds)
	ret0, _ := ret[0].([]db.GetAllLocationBrokerCodesByLocationIDsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLocationBrokerCodesByLocationIDs indicates an expected call of GetAllLocationBrokerCodesByLocationIDs.
func (mr *MockQuerierMockRecorder) GetAllLocationBrokerCodesByLocationIDs(ctx, locationIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLocationBrokerCodesByLocationIDs", reflect.TypeOf((*MockQuerier)(nil).GetAllLocationBrokerCodesByLocationIDs), ctx, locationIds)
}

// GetAllVerifiedTranslations mocks base method.
func (m *MockQuerier) GetAllVerifiedTranslations(ctx context.Context) ([]db.GetAllVerifiedTranslationsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllVerifiedTranslations", ctx)
	ret0, _ := ret[0].([]db.GetAllVerifiedTranslationsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllVerifiedTranslations indicates an expected call of GetAllVerifiedTranslations.
func (mr *MockQuerierMockRecorder) GetAllVerifiedTranslations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllVerifiedTranslations", reflect.TypeOf((*MockQuerier)(nil).GetAllVerifiedTranslations), ctx)
}

// GetHertzMarkupRates mocks base method.
func (m *MockQuerier) GetHertzMarkupRates(ctx context.Context, arg db.GetHertzMarkupRatesParams) ([]db.GetHertzMarkupRatesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHertzMarkupRates", ctx, arg)
	ret0, _ := ret[0].([]db.GetHertzMarkupRatesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHertzMarkupRates indicates an expected call of GetHertzMarkupRates.
func (mr *MockQuerierMockRecorder) GetHertzMarkupRates(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHertzMarkupRates", reflect.TypeOf((*MockQuerier)(nil).GetHertzMarkupRates), ctx, arg)
}

// GetLocationBrokerCode mocks base method.
func (m *MockQuerier) GetLocationBrokerCode(ctx context.Context, arg db.GetLocationBrokerCodeParams) (db.LocationBrokerCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocationBrokerCode", ctx, arg)
	ret0, _ := ret[0].(db.LocationBrokerCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocationBrokerCode indicates an expected call of GetLocationBrokerCode.
func (mr *MockQuerierMockRecorder) GetLocationBrokerCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocationBrokerCode", reflect.TypeOf((*MockQuerier)(nil).GetLocationBrokerCode), ctx, arg)
}

// GetLocationByBrokerLocationID mocks base method.
func (m *MockQuerier) GetLocationByBrokerLocationID(ctx context.Context, brokerLocationID string) (db.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocationByBrokerLocationID", ctx, brokerLocationID)
	ret0, _ := ret[0].(db.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocationByBrokerLocationID indicates an expected call of GetLocationByBrokerLocationID.
func (mr *MockQuerierMockRecorder) GetLocationByBrokerLocationID(ctx, brokerLocationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocationByBrokerLocationID", reflect.TypeOf((*MockQuerier)(nil).GetLocationByBrokerLocationID), ctx, brokerLocationID)
}

// GetLocationById mocks base method.
func (m *MockQuerier) GetLocationById(ctx context.Context, id int64) (db.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocationById", ctx, id)
	ret0, _ := ret[0].(db.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocationById indicates an expected call of GetLocationById.
func (mr *MockQuerierMockRecorder) GetLocationById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocationById", reflect.TypeOf((*MockQuerier)(nil).GetLocationById), ctx, id)
}

// GetSnapshotByID mocks base method.
func (m *MockQuerier) GetSnapshotByID(ctx context.Context, id int64) (db.AvailablePlansSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSnapshotByID", ctx, id)
	ret0, _ := ret[0].(db.AvailablePlansSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSnapshotByID indicates an expected call of GetSnapshotByID.
func (mr *MockQuerierMockRecorder) GetSnapshotByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshotByID", reflect.TypeOf((*MockQuerier)(nil).GetSnapshotByID), ctx, id)
}

// InsertAvailablePlansSnapshot mocks base method.
func (m *MockQuerier) InsertAvailablePlansSnapshot(ctx context.Context, arg db.InsertAvailablePlansSnapshotParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAvailablePlansSnapshot", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAvailablePlansSnapshot indicates an expected call of InsertAvailablePlansSnapshot.
func (mr *MockQuerierMockRecorder) InsertAvailablePlansSnapshot(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAvailablePlansSnapshot", reflect.TypeOf((*MockQuerier)(nil).InsertAvailablePlansSnapshot), ctx, arg)
}

// InsertBrokerTranslation mocks base method.
func (m *MockQuerier) InsertBrokerTranslation(ctx context.Context, sourceText string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBrokerTranslation", ctx, sourceText)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertBrokerTranslation indicates an expected call of InsertBrokerTranslation.
func (mr *MockQuerierMockRecorder) InsertBrokerTranslation(ctx, sourceText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBrokerTranslation", reflect.TypeOf((*MockQuerier)(nil).InsertBrokerTranslation), ctx, sourceText)
}

// InsertBrokerTranslationFull mocks base method.
func (m *MockQuerier) InsertBrokerTranslationFull(ctx context.Context, arg db.InsertBrokerTranslationFullParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBrokerTranslationFull", ctx, arg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertBrokerTranslationFull indicates an expected call of InsertBrokerTranslationFull.
func (mr *MockQuerierMockRecorder) InsertBrokerTranslationFull(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBrokerTranslationFull", reflect.TypeOf((*MockQuerier)(nil).InsertBrokerTranslationFull), ctx, arg)
}

// InsertHertzMarkupRate mocks base method.
func (m *MockQuerier) InsertHertzMarkupRate(ctx context.Context, arg db.InsertHertzMarkupRateParams) (db.HertzMarkupRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHertzMarkupRate", ctx, arg)
	ret0, _ := ret[0].(db.HertzMarkupRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertHertzMarkupRate indicates an expected call of InsertHertzMarkupRate.
func (mr *MockQuerierMockRecorder) InsertHertzMarkupRate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHertzMarkupRate", reflect.TypeOf((*MockQuerier)(nil).InsertHertzMarkupRate), ctx, arg)
}

// InsertLocation mocks base method.
func (m *MockQuerier) InsertLocation(ctx context.Context, arg db.InsertLocationParams) (db.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLocation", ctx, arg)
	ret0, _ := ret[0].(db.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertLocation indicates an expected call of InsertLocation.
func (mr *MockQuerierMockRecorder) InsertLocation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLocation", reflect.TypeOf((*MockQuerier)(nil).InsertLocation), ctx, arg)
}

// InsertLocationBrokerCode mocks base method.
func (m *MockQuerier) InsertLocationBrokerCode(ctx context.Context, arg db.InsertLocationBrokerCodeParams) (db.LocationBrokerCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLocationBrokerCode", ctx, arg)
	ret0, _ := ret[0].(db.LocationBrokerCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertLocationBrokerCode indicates an expected call of InsertLocationBrokerCode.
func (mr *MockQuerierMockRecorder) InsertLocationBrokerCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLocationBrokerCode", reflect.TypeOf((*MockQuerier)(nil).InsertLocationBrokerCode), ctx, arg)
}

// InsertManyLocation mocks base method.
func (m *MockQuerier) InsertManyLocation(ctx context.Context, arg db.InsertManyLocationParams) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertManyLocation", ctx, arg)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertManyLocation indicates an expected call of InsertManyLocation.
func (mr *MockQuerierMockRecorder) InsertManyLocation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertManyLocation", reflect.TypeOf((*MockQuerier)(nil).InsertManyLocation), ctx, arg)
}

// ListAllTranslations mocks base method.
func (m *MockQuerier) ListAllTranslations(ctx context.Context, arg db.ListAllTranslationsParams) ([]db.BrokerTranslation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllTranslations", ctx, arg)
	ret0, _ := ret[0].([]db.BrokerTranslation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllTranslations indicates an expected call of ListAllTranslations.
func (mr *MockQuerierMockRecorder) ListAllTranslations(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllTranslations", reflect.TypeOf((*MockQuerier)(nil).ListAllTranslations), ctx, arg)
}

// ListCoupons mocks base method.
func (m *MockQuerier) ListCoupons(ctx context.Context) ([]db.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCoupons", ctx)
	ret0, _ := ret[0].([]db.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCoupons indicates an expected call of ListCoupons.
func (mr *MockQuerierMockRecorder) ListCoupons(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCoupons", reflect.TypeOf((*MockQuerier)(nil).ListCoupons), ctx)
}

// ListCurrencies mocks base method.
func (m *MockQuerier) ListCurrencies(ctx context.Context) ([]db.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCurrencies", ctx)
	ret0, _ := ret[0].([]db.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCurrencies indicates an expected call of ListCurrencies.
func (mr *MockQuerierMockRecorder) ListCurrencies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCurrencies", reflect.TypeOf((*MockQuerier)(nil).ListCurrencies), ctx)
}

// ListHertzMarkupRates mocks base method.
func (m *MockQuerier) ListHertzMarkupRates(ctx context.Context, arg db.ListHertzMarkupRatesParams) ([]db.HertzMarkupRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHertzMarkupRates", ctx, arg)
	ret0, _ := ret[0].([]db.HertzMarkupRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHertzMarkupRates indicates an expected call of ListHertzMarkupRates.
func (mr *MockQuerierMockRecorder) ListHertzMarkupRates(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHertzMarkupRates", reflect.TypeOf((*MockQuerier)(nil).ListHertzMarkupRates), ctx, arg)
}

// ListLocationBrokerCodesWithLocation mocks base method.
func (m *MockQuerier) ListLocationBrokerCodesWithLocation(ctx context.Context, arg db.ListLocationBrokerCodesWithLocationParams) ([]db.ListLocationBrokerCodesWithLocationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLocationBrokerCodesWithLocation", ctx, arg)
	ret0, _ := ret[0].([]db.ListLocationBrokerCodesWithLocationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLocationBrokerCodesWithLocation indicates an expected call of ListLocationBrokerCodesWithLocation.
func (mr *MockQuerierMockRecorder) ListLocationBrokerCodesWithLocation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLocationBrokerCodesWithLocation", reflect.TypeOf((*MockQuerier)(nil).ListLocationBrokerCodesWithLocation), ctx, arg)
}

// SearchLocations mocks base method.
func (m *MockQuerier) SearchLocations(ctx context.Context, search string) ([]db.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchLocations", ctx, search)
	ret0, _ := ret[0].([]db.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchLocations indicates an expected call of SearchLocations.
func (mr *MockQuerierMockRecorder) SearchLocations(ctx, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchLocations", reflect.TypeOf((*MockQuerier)(nil).SearchLocations), ctx, search)
}

// UpdateBrokerTranslation mocks base method.
func (m *MockQuerier) UpdateBrokerTranslation(ctx context.Context, arg db.UpdateBrokerTranslationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBrokerTranslation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBrokerTranslation indicates an expected call of UpdateBrokerTranslation.
func (mr *MockQuerierMockRecorder) UpdateBrokerTranslation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBrokerTranslation", reflect.TypeOf((*MockQuerier)(nil).UpdateBrokerTranslation), ctx, arg)
}

// UpdateCoupon mocks base method.
func (m *MockQuerier) UpdateCoupon(ctx context.Context, arg db.UpdateCouponParams) (db.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCoupon", ctx, arg)
	ret0, _ := ret[0].(db.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCoupon indicates an expected call of UpdateCoupon.
func (mr *MockQuerierMockRecorder) UpdateCoupon(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCoupon", reflect.TypeOf((*MockQuerier)(nil).UpdateCoupon), ctx, arg)
}

// UpdateCurrency mocks base method.
func (m *MockQuerier) UpdateCurrency(ctx context.Context, arg db.UpdateCurrencyParams) (db.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrency", ctx, arg)
	ret0, _ := ret[0].(db.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCurrency indicates an expected call of UpdateCurrency.
func (mr *MockQuerierMockRecorder) UpdateCurrency(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrency", reflect.TypeOf((*MockQuerier)(nil).UpdateCurrency), ctx, arg)
}

// UpdateHertzMarkupRate mocks base method.
func (m *MockQuerier) UpdateHertzMarkupRate(ctx context.Context, arg db.UpdateHertzMarkupRateParams) (db.HertzMarkupRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHertzMarkupRate", ctx, arg)
	ret0, _ := ret[0].(db.HertzMarkupRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHertzMarkupRate indicates an expected call of UpdateHertzMarkupRate.
func (mr *MockQuerierMockRecorder) UpdateHertzMarkupRate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHertzMarkupRate", reflect.TypeOf((*MockQuerier)(nil).UpdateHertzMarkupRate), ctx, arg)
}

// UpsertLocationByCountryCodeName mocks base method.
func (m *MockQuerier) UpsertLocationByCountryCodeName(ctx context.Context, arg db.UpsertLocationByCountryCodeNameParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertLocationByCountryCodeName", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertLocationByCountryCodeName indicates an expected call of UpsertLocationByCountryCodeName.
func (mr *MockQuerierMockRecorder) UpsertLocationByCountryCodeName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertLocationByCountryCodeName", reflect.TypeOf((*MockQuerier)(nil).UpsertLocationByCountryCodeName), ctx, arg)
}

// UpsertLocationByIATA mocks base method.
func (m *MockQuerier) UpsertLocationByIATA(ctx context.Context, arg db.UpsertLocationByIATAParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertLocationByIATA", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertLocationByIATA indicates an expected call of UpsertLocationByIATA.
func (mr *MockQuerierMockRecorder) UpsertLocationByIATA(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertLocationByIATA", reflect.TypeOf((*MockQuerier)(nil).UpsertLocationByIATA), ctx, arg)
}

// VerifyBrokerTranslation mocks base method.
func (m *MockQuerier) VerifyBrokerTranslation(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyBrokerTranslation", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyBrokerTranslation indicates an expected call of VerifyBrokerTranslation.
func (mr *MockQuerierMockRecorder) VerifyBrokerTranslation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyBrokerTranslation", reflect.TypeOf((*MockQuerier)(nil).VerifyBrokerTranslation), ctx, id)
}
