interface CarGroupFilter {
  name: string;
  image: string;
  acrissCodes: string[];
}

export const CAR_GROUPS_FILTERS: CarGroupFilter[] = [
  {
    name: "Small",
    image: "/assets/booking/car-groups/small.png",
    acrissCodes: [
      "MCMR",
      "ECMR",
      "EDMR",
      "NBMR",
      "MDMV",
      "MDMR",
      "MBMR",
      "EXMR",
      "EBMR",
      "EBMR",
      "ECAE",
      "EDAE",
      "MDAR",
      "EDAR",
      "MZMR",
      "EDAH",
      "MTMR",
      "EDMD",
      "ECAH",
      "EFMR",
      "EDMV",
      "MXMR",
      "ETMR",
      "EDMU",
      "ETAR",
      "ETAR",
      "ECAR",
      "CCAR",
      "MCMN",
      "EDMN",
    ],
  },
  {
    name: "Medium",
    image: "/assets/booking/car-groups/medium.png",
    acrissCodes: [
      "CDMR",
      "CDAR",
      "CFMR",
      "CFAR",
      "IXMR",
      "IDMR",
      "IFMR",
      "IFAI",
      "SDMR",
      "SGMR",
      "SFAE",
      "CWMR",
      "CLMR",
      "CLAR",
      "SGAR",
      "IMMR",
      "CGMR",
      "CWAR",
      "CXMR",
      "CEAH",
      "IDAR",
      "IDAH",
      "SDAI",
      "IFAH",
      "CXAR",
      "CDAM",
      "ILMR",
      "IMAR",
      "CTMR",
      "SDAR",
      "SFAE",
      "CDMH",
      "CDAU",
      "SWAH",
      "CVMR",
      "IDAU",
      "CVAR",
      "ICAR",
      "SCAR",
    ],
  },
  {
    name: "Large",
    image: "/assets/booking/car-groups/large.png",
    acrissCodes: [
      "FFAH",
      "FDAR",
      "FWAR",
      "FWMR",
      "FFAH",
      "FDMR",
      "FCAR",
      "PCAR",
      "LCAR",
      "LDAR",
      "PDAR",
      "SDAR",
      "SDMR",
      "ICAH",
    ],
  },
  {
    name: "SUV",
    image: "/assets/booking/car-groups/suv.png",
    acrissCodes: [
      "CFMR",
      "CFAR",
      "IFMR",
      "IFAI",
      "IFAH",
      "SFAE",
      "EFMR",
      "DFAR",
      "IFAR",
      "CFAE",
      "FFAH",
      "UFBE",
      "PFAR",
      "PFAH",
      "PFAV",
      "PFAU",
      "WFAF",
      "FFAR",
      "SFAR",
      "FRAR",
      "IFAC",
      "SFBR",
      "RFAR",
      "PLAR",
      "SFDR",
      "CGAH",
      "IJAR",
      "IPAR",
      "SPAR",
    ],
  },
  {
    name: "Station Wagon",
    image: "/assets/booking/car-groups/station-wagon.png",
    acrissCodes: [
      "CWMR",
      "SWMR",
      "CWAR",
      "SWAR",
      "CWAH",
      "LWAR",
      "FWAR",
      "SWAH",
      "FWMR",
      "EWMR",
      "PWMR",
      "PWAR",
      "IWAR",
      "IWMR",
    ],
  },
  {
    name: "Passenger Van",
    image: "/assets/booking/car-groups/passenger-van.png",
    acrissCodes: [
      "IVAR",
      "IVMR",
      "FSAR",
      "IMAR",
      "FVMR",
      "FVAR",
      "FVAE",
      "FLMR",
      "OVMR",
      "MVAR",
      "SVAR",
      "SVMR",
    ],
  },
  {
    name: "Premium",
    image: "/assets/booking/car-groups/premium.png",
    acrissCodes: [
      "LDAR",
      "PDAR",
      "PDMR",
      "PWMR",
      "PWAR",
      "LSAN",
      "LSAR",
      "FTAR",
      "PFAR",
      "PFAV",
      "PDAE",
      "PXAR",
      "PDAU",
      "PWAU",
      "PFAU",
    ],
  },
];
