interface CarGroupFilter {
  name: string;
  image: string;
  acrissCodes: string[];
}

export const CAR_GROUPS_FILTERS: CarGroupFilter[] = [
  {
    name: "Small",
    image: "/assets/booking/car-groups/small.png",
    acrissCodes: [
      // Mini
      "MBMR",
      "MBAR",
      "MCMR",
      "MCAR",
      "MDMR",
      "MDAR",
      "MXMR",
      "MXAR",
      "MTMR",
      "MTAR",
      "MZMR",
      "MZAR",
      "MCMN",
      "MDMN",
      "MCAH",
      "MDAH",
      "MCAE",
      "MDAE",
      "MCAC",
      "MDAC",

      // Mini Elite
      "NBMR",
      "NBAR",
      "NCMR",
      "NCAR",
      "NDMR",
      "NDAR",
      "NXMR",
      "NXAR",

      // Economy
      "EBMR",
      "EBAR",
      "ECMR",
      "ECAR",
      "EDMR",
      "EDAR",
      "EXMR",
      "EXAR",
      "ETMR",
      "ETAR",
      "EZMR",
      "EZAR",
      "ECMN",
      "EDMN",
      "ECMD",
      "EDMD",
      "ECAH",
      "EDAH",
      "ECAE",
      "EDAE",
      "ECAC",
      "EDAC",
      "ECAU",
      "EDAU",
      "ECAV",
      "EDAV",

      // Economy Elite
      "HBMR",
      "HBAR",
      "HCMR",
      "HCAR",
      "HDMR",
      "HDAR",
    ],
  },
  {
    name: "Medium",
    image: "/assets/booking/car-groups/medium.png",
    acrissCodes: [
      // Compact
      "CBMR",
      "CBAR",
      "CCMR",
      "CCAR",
      "CDMR",
      "CDAR",
      "CXMR",
      "CXAR",
      "CLMR",
      "CLAR",
      "CMMR",
      "CMAR",
      "CTMR",
      "CTAR",
      "CGMR",
      "CGAR",
      "CDMN",
      "CDMD",
      "CDAH",
      "CDMH",
      "CDAE",
      "CDAC",
      "CDAU",
      "CDAV",
      "CCAH",
      "CCAE",
      "CCAC",

      // Compact Elite
      "DBMR",
      "DBAR",
      "DCMR",
      "DCAR",
      "DDMR",
      "DDAR",
      "DXMR",
      "DXAR",
      "DMMR",
      "DMAR",

      // Intermediate
      "IBMR",
      "IBAR",
      "ICMR",
      "ICAR",
      "IDMR",
      "IDAR",
      "IXMR",
      "IXAR",
      "ILMR",
      "ILAR",
      "IMMR",
      "IMAR",
      "ITMR",
      "ITAR",
      "IGMR",
      "IGAR",
      "IDMN",
      "IDMD",
      "IDAH",
      "IDMH",
      "IDAE",
      "IDAC",
      "IDAU",
      "IDAV",
      "ICAH",
      "ICAE",
      "ICAC",

      // Intermediate Elite
      "JBMR",
      "JBAR",
      "JCMR",
      "JCAR",
      "JDMR",
      "JDAR",
      "JXMR",
      "JXAR",
      "JMMR",
      "JMAR",

      // Standard non-SUV / non-wagon
      "SBMR",
      "SBAR",
      "SCMR",
      "SCAR",
      "SDMR",
      "SDAR",
      "SXMR",
      "SXAR",
      "SLMR",
      "SLAR",
      "SMMR",
      "SMAR",
      "STMR",
      "STAR",
      "SGMR",
      "SGAR",
      "SDAH",
      "SDAE",
      "SDAC",
      "SDAU",
      "SDAV",
    ],
  },
  {
    name: "Large",
    image: "/assets/booking/car-groups/large.png",
    acrissCodes: [
      // Fullsize
      "FBMR",
      "FBAR",
      "FCMR",
      "FCAR",
      "FDMR",
      "FDAR",
      "FXMR",
      "FXAR",
      "FLMR",
      "FLAR",
      "FMMR",
      "FMAR",
      "FTMR",
      "FTAR",
      "FGMR",
      "FGAR",
      "FDMD",
      "FDAH",
      "FDMA",
      "FDAE",
      "FDAC",
      "FDAU",
      "FDAV",

      // Fullsize Elite
      "GBMR",
      "GBAR",
      "GCMR",
      "GCAR",
      "GDMR",
      "GDAR",
      "GXMR",
      "GXAR",
      "GLMR",
      "GLAR",

      // Oversize / Special large vehicles
      "ODAR",
      "ODMR",
      "OXAR",
      "OXMR",
      "XDAR",
      "XDMR",
      "XXAR",
      "XXMR",
    ],
  },
  {
    name: "SUV",
    image: "/assets/booking/car-groups/suv.png",
    acrissCodes: [
      // Economy SUV
      "EFMR",
      "EFAR",
      "EFAH",
      "EFAE",
      "EFAC",

      // Compact SUV
      "CFMR",
      "CFAR",
      "CFAH",
      "CFAE",
      "CFAC",
      "CFAV",
      "CGAH",
      "CGAR",
      "CGMR",

      // Compact Elite SUV
      "DFMR",
      "DFAR",
      "DFAH",
      "DFAE",
      "DFAC",

      // Intermediate SUV
      "IFMR",
      "IFAR",
      "IFAH",
      "IFAI",
      "IFAE",
      "IFAC",
      "IFAV",
      "IGMR",
      "IGAR",
      "IJMR",
      "IJAR",

      // Intermediate Elite SUV
      "JFMR",
      "JFAR",
      "JFAH",
      "JFAE",
      "JFAC",

      // Standard SUV
      "SFMR",
      "SFAR",
      "SFAH",
      "SFAE",
      "SFAC",
      "SFAV",
      "SFBR",
      "SFDR",
      "SGMR",
      "SGAR",

      // Standard Elite SUV
      "RFMR",
      "RFAR",
      "RFAH",
      "RFAE",
      "RFAC",

      // Fullsize SUV
      "FFMR",
      "FFAR",
      "FFAH",
      "FFAE",
      "FFAC",
      "FFAV",
      "FGMR",
      "FGAR",

      // Fullsize Elite SUV
      "GFMR",
      "GFAR",
      "GFAH",
      "GFAE",
      "GFAC",

      // Premium SUV
      "PFMR",
      "PFAR",
      "PFAH",
      "PFAE",
      "PFAC",
      "PFAV",
      "PFAU",
      "PGAR",
      "PGMR",

      // Premium Elite SUV
      "UFMR",
      "UFAR",
      "UFAH",
      "UFAE",
      "UFAC",
      "UFBE",

      // Luxury SUV
      "LFMR",
      "LFAR",
      "LFAH",
      "LFAE",
      "LFAC",
      "LGAR",
      "LGMR",

      // Luxury Elite SUV
      "WFMR",
      "WFAR",
      "WFAH",
      "WFAE",
      "WFAC",
      "WFAF",

      // Special SUV / crossover / all-terrain
      "XFMR",
      "XFAR",
      "XFAH",
      "XFAE",
      "XFAC",
      "XJAR",
      "XJMR",
    ],
  },
  {
    name: "Station Wagon",
    image: "/assets/booking/car-groups/station-wagon.png",
    acrissCodes: [
      // Economy Wagon
      "EWMR",
      "EWAR",
      "EWAH",
      "EWAE",
      "EWAC",

      // Compact Wagon
      "CWMR",
      "CWAR",
      "CWAH",
      "CWAE",
      "CWAC",
      "CWAU",

      // Compact Elite Wagon
      "DWMR",
      "DWAR",
      "DWAH",
      "DWAE",
      "DWAC",

      // Intermediate Wagon
      "IWMR",
      "IWAR",
      "IWAH",
      "IWAE",
      "IWAC",
      "IWAU",

      // Intermediate Elite Wagon
      "JWMR",
      "JWAR",
      "JWAH",
      "JWAE",
      "JWAC",

      // Standard Wagon
      "SWMR",
      "SWAR",
      "SWAH",
      "SWAE",
      "SWAC",
      "SWAU",

      // Standard Elite Wagon
      "RWMR",
      "RWAR",
      "RWAH",
      "RWAE",
      "RWAC",

      // Fullsize Wagon
      "FWMR",
      "FWAR",
      "FWAH",
      "FWAE",
      "FWAC",

      // Fullsize Elite Wagon
      "GWMR",
      "GWAR",
      "GWAH",
      "GWAE",
      "GWAC",

      // Premium / Luxury Wagon
      "PWMR",
      "PWAR",
      "PWAH",
      "PWAE",
      "PWAC",
      "PWAU",
      "UWMR",
      "UWAR",
      "LWMR",
      "LWAR",
      "LWAH",
      "LWAE",
      "WWMR",
      "WWAR",
    ],
  },
  {
    name: "Passenger Van",
    image: "/assets/booking/car-groups/passenger-van.png",
    acrissCodes: [
      // ACRISS passenger van capacity-style codes.
      // V as 2nd letter = Passenger Van.
      "IVMR",
      "IVAR",
      "IVAH",
      "IVAE",
      "IVAC",
      "IVAV",

      "JVMR",
      "JVAR",
      "JVAH",
      "JVAE",
      "JVAC",

      "SVMR",
      "SVAR",
      "SVAH",
      "SVAE",
      "SVAC",
      "SVAV",

      "RVMR",
      "RVAR",
      "RVAH",
      "RVAE",
      "RVAC",

      "FVMR",
      "FVAR",
      "FVAH",
      "FVAE",
      "FVAC",
      "FVAV",

      "GVMR",
      "GVAR",
      "GVAH",
      "GVAE",
      "GVAC",

      "PVMR",
      "PVAR",
      "PVAH",
      "PVAE",
      "PVAC",
      "PVAV",

      "UVMR",
      "UVAR",
      "UVAH",
      "UVAE",
      "UVAC",

      "LVMR",
      "LVAR",
      "LVAH",
      "LVAE",
      "LVAC",
      "LVAV",

      "WVMR",
      "WVAR",
      "WVAH",
      "WVAE",
      "WVAC",

      "XVMR",
      "XVAR",
      "XVAH",
      "XVAE",
      "XVAC",

      "OVMR",
      "OVAR",
      "OVAH",
      "OVAE",
      "OVAC",

      // Common MPV / monospace classes that suppliers often use for family carriers.
      "CMMR",
      "CMAR",
      "IMMR",
      "IMAR",
      "SMMR",
      "SMAR",
      "FMMR",
      "FMAR",
      "PMMR",
      "PMAR",
    ],
  },
  {
    name: "Premium",
    image: "/assets/booking/car-groups/premium.png",
    acrissCodes: [
      // Premium
      "PBMR",
      "PBAR",
      "PCMR",
      "PCAR",
      "PDMR",
      "PDAR",
      "PXMR",
      "PXAR",
      "PLMR",
      "PLAR",
      "PEMR",
      "PEAR",
      "PTMR",
      "PTAR",
      "PSMR",
      "PSAR",
      "PWMR",
      "PWAR",
      "PFMR",
      "PFAR",
      "PGMR",
      "PGAR",
      "PDMD",
      "PDAH",
      "PDAE",
      "PDAC",
      "PDAU",
      "PDAV",
      "PFAH",
      "PFAE",
      "PFAC",
      "PFAV",
      "PFAU",
      "PWAH",
      "PWAE",
      "PWAC",
      "PWAU",

      // Premium Elite
      "UBMR",
      "UBAR",
      "UCMR",
      "UCAR",
      "UDMR",
      "UDAR",
      "UXMR",
      "UXAR",
      "ULMR",
      "ULAR",
      "UEMR",
      "UEAR",
      "UTMR",
      "UTAR",
      "USMR",
      "USAR",
      "UWMR",
      "UWAR",
      "UFMR",
      "UFAR",
      "UGMR",
      "UGAR",
      "UDAH",
      "UDAE",
      "UDAC",
      "UFAH",
      "UFAE",
      "UFAC",

      // Luxury
      "LBMR",
      "LBAR",
      "LCMR",
      "LCAR",
      "LDMR",
      "LDAR",
      "LXMR",
      "LXAR",
      "LLMR",
      "LLAR",
      "LEMR",
      "LEAR",
      "LTMR",
      "LTAR",
      "LSMR",
      "LSAR",
      "LWMR",
      "LWAR",
      "LFMR",
      "LFAR",
      "LGMR",
      "LGAR",
      "LDAH",
      "LDAE",
      "LDAC",
      "LFAH",
      "LFAE",
      "LFAC",

      // Luxury Elite
      "WBMR",
      "WBAR",
      "WCMR",
      "WCAR",
      "WDMR",
      "WDAR",
      "WXMR",
      "WXAR",
      "WLMR",
      "WLAR",
      "WEMR",
      "WEAR",
      "WTMR",
      "WTAR",
      "WSMR",
      "WSAR",
      "WWMR",
      "WWAR",
      "WFMR",
      "WFAR",
      "WGMR",
      "WGAR",
    ],
  },
];