// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_payments_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingPayment = `-- name: CreatePendingPayment :one
INSERT INTO pending_customer_payments (
    user_id,
    snapshot_id,
    rate_qualifier,
    supplier_code,
    plan_id,
    include_erp,
    selected_addons,
    driver_title,
    driver_first_name,
    driver_last_name,
    flight_number
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, token
`

type CreatePendingPaymentParams struct {
	UserID          int64
	SnapshotID      int64
	RateQualifier   string
	SupplierCode    string
	PlanID          string
	IncludeErp      bool
	SelectedAddons  []byte
	DriverTitle     string
	DriverFirstName string
	DriverLastName  string
	FlightNumber    *string
}

type CreatePendingPaymentRow struct {
	ID    int64
	Token pgtype.UUID
}

func (q *Queries) CreatePendingPayment(ctx context.Context, arg CreatePendingPaymentParams) (CreatePendingPaymentRow, error) {
	row := q.db.QueryRow(ctx, createPendingPayment,
		arg.UserID,
		arg.SnapshotID,
		arg.RateQualifier,
		arg.SupplierCode,
		arg.PlanID,
		arg.IncludeErp,
		arg.SelectedAddons,
		arg.DriverTitle,
		arg.DriverFirstName,
		arg.DriverLastName,
		arg.FlightNumber,
	)
	var i CreatePendingPaymentRow
	err := row.Scan(&i.ID, &i.Token)
	return i, err
}

const getPendingPaymentByID = `-- name: GetPendingPaymentByID :one
SELECT id, token, user_id, snapshot_id, rate_qualifier, supplier_code, plan_id, include_erp, selected_addons, driver_title, driver_first_name, driver_last_name, flight_number, status, reservation_id, created_at FROM pending_customer_payments WHERE id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingPaymentByID(ctx context.Context, id int64) (PendingCustomerPayment, error) {
	row := q.db.QueryRow(ctx, getPendingPaymentByID, id)
	var i PendingCustomerPayment
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.SnapshotID,
		&i.RateQualifier,
		&i.SupplierCode,
		&i.PlanID,
		&i.IncludeErp,
		&i.SelectedAddons,
		&i.DriverTitle,
		&i.DriverFirstName,
		&i.DriverLastName,
		&i.FlightNumber,
		&i.Status,
		&i.ReservationID,
		&i.CreatedAt,
	)
	return i, err
}

const resolvePendingPayment = `-- name: ResolvePendingPayment :exec
UPDATE pending_customer_payments SET 
status = 'completed', reservation_id = $2 
WHERE id = $1 AND status = 'pending'
`

type ResolvePendingPaymentParams struct {
	ID            int64
	ReservationID *int64
}

func (q *Queries) ResolvePendingPayment(ctx context.Context, arg ResolvePendingPaymentParams) error {
	_, err := q.db.Exec(ctx, resolvePendingPayment, arg.ID, arg.ReservationID)
	return err
}
