// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_payments_query.sql

package db

import (
	"context"
)

const getPendingPaymentByID = `-- name: GetPendingPaymentByID :one
SELECT id, user_id, phone, snapshot_id, rate_qualifier, supplier_code, plan_id, include_erp, selected_addons, driver_title, driver_first_name, driver_last_name, flight_number, status, reservation_id, created_at, expires_at FROM pending_customer_payments WHERE id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingPaymentByID(ctx context.Context, id int64) (PendingCustomerPayment, error) {
	row := q.db.QueryRow(ctx, getPendingPaymentByID, id)
	var i PendingCustomerPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.SnapshotID,
		&i.RateQualifier,
		&i.SupplierCode,
		&i.PlanID,
		&i.IncludeErp,
		&i.SelectedAddons,
		&i.DriverTitle,
		&i.DriverFirstName,
		&i.DriverLastName,
		&i.FlightNumber,
		&i.Status,
		&i.ReservationID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
