// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreatePendingPayment(ctx context.Context, arg CreatePendingPaymentParams) (CreatePendingPaymentRow, error)
	GetPendingPaymentByID(ctx context.Context, id int64) (PendingCustomerPayment, error)
	ResolvePendingPayment(ctx context.Context, arg ResolvePendingPaymentParams) error
}

var _ Querier = (*Queries)(nil)
