// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Broker string

const (
	BrokerFlex  Broker = "flex"
	BrokerHertz Broker = "hertz"
)

func (e *Broker) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Broker(s)
	case string:
		*e = Broker(s)
	default:
		return fmt.Errorf("unsupported scan type for Broker: %T", src)
	}
	return nil
}

type NullBroker struct {
	Broker Broker
	Valid  bool // Valid is true if Broker is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBroker) Scan(value interface{}) error {
	if value == nil {
		ns.Broker, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Broker.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBroker) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Broker), nil
}

type PaymentStatus string

const (
	PaymentStatusUnpaid        PaymentStatus = "unpaid"
	PaymentStatusPaid          PaymentStatus = "paid"
	PaymentStatusRefundPending PaymentStatus = "refund_pending"
	PaymentStatusRefunded      PaymentStatus = "refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type ReservationStatus string

const (
	ReservationStatusBooked    ReservationStatus = "booked"
	ReservationStatusVouchered ReservationStatus = "vouchered"
	ReservationStatusCanceled  ReservationStatus = "canceled"
)

func (e *ReservationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationStatus(s)
	case string:
		*e = ReservationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationStatus: %T", src)
	}
	return nil
}

type NullReservationStatus struct {
	ReservationStatus ReservationStatus
	Valid             bool // Valid is true if ReservationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationStatus), nil
}

type Reservation struct {
	ID                  int64
	UserID              int32
	BrokerReservationID string
	ReservationStatus   ReservationStatus
	PaymentStatus       PaymentStatus
	Broker              Broker
	SupplierCode        string
	CarDetails          []byte
	PlanInclusions      []string
	CountryCode         string
	CurrencyCode        string
	CurrencyRate        pgtype.Numeric
	PurchasePrice       pgtype.Numeric
	MarkupPercentage    pgtype.Numeric
	BrokerErpPrice      pgtype.Numeric
	DiscountPercentage  int32
	BtErpPrice          int32
	VatPercentage       pgtype.Numeric
	TotalPrice          int32
	PickupDate          pgtype.Date
	ReturnDate          pgtype.Date
	PickupTime          string
	DropoffTime         string
	RentalDays          int32
	DriverTitle         string
	DriverFirstName     string
	DriverLastName      string
	DriverAge           int32
	PickupLocationName  string
	DropoffLocationName string
	VoucherNumber       *string
	VoucheredAt         pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}
