// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Broker string

const (
	BrokerFlex  Broker = "flex"
	BrokerHertz Broker = "hertz"
)

func (e *Broker) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Broker(s)
	case string:
		*e = Broker(s)
	default:
		return fmt.Errorf("unsupported scan type for Broker: %T", src)
	}
	return nil
}

type NullBroker struct {
	Broker Broker
	Valid  bool // Valid is true if Broker is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBroker) Scan(value interface{}) error {
	if value == nil {
		ns.Broker, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Broker.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBroker) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Broker), nil
}

type PaymentStatus string

const (
	PaymentStatusUnpaid        PaymentStatus = "unpaid"
	PaymentStatusPaid          PaymentStatus = "paid"
	PaymentStatusRefundPending PaymentStatus = "refund_pending"
	PaymentStatusRefunded      PaymentStatus = "refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PenaltyType string

const (
	PenaltyTypeCancellation PenaltyType = "cancellation"
	PenaltyTypeNoShow       PenaltyType = "no_show"
)

func (e *PenaltyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PenaltyType(s)
	case string:
		*e = PenaltyType(s)
	default:
		return fmt.Errorf("unsupported scan type for PenaltyType: %T", src)
	}
	return nil
}

type NullPenaltyType struct {
	PenaltyType PenaltyType
	Valid       bool // Valid is true if PenaltyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPenaltyType) Scan(value interface{}) error {
	if value == nil {
		ns.PenaltyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PenaltyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPenaltyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PenaltyType), nil
}

type ReservationStatus string

const (
	ReservationStatusBooked    ReservationStatus = "booked"
	ReservationStatusVouchered ReservationStatus = "vouchered"
	ReservationStatusCanceled  ReservationStatus = "canceled"
)

func (e *ReservationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationStatus(s)
	case string:
		*e = ReservationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationStatus: %T", src)
	}
	return nil
}

type NullReservationStatus struct {
	ReservationStatus ReservationStatus
	Valid             bool // Valid is true if ReservationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationStatus), nil
}

type Outbox struct {
	ID         int64
	Topic      string
	Data       []byte
	InsertedAt pgtype.Timestamptz
}

type Reservation struct {
	ID                      int64
	BrokerReservationID     string
	UserID                  int64
	OfficeID                *int64
	OrganizationID          *int64
	IsOrganizationOrganic   *bool
	AdminRefID              *int64
	ReservationStatus       ReservationStatus
	PaymentStatus           PaymentStatus
	Broker                  Broker
	SupplierCode            string
	CarDetails              []byte
	PlanInclusions          []string
	PayAtPickup             []byte
	CurrencyCode            string
	CurrencyRate            pgtype.Numeric
	VatPercentage           pgtype.Numeric
	PurchasePrice           pgtype.Numeric
	MarkupPercentage        pgtype.Numeric
	BrokerErpPrice          pgtype.Numeric
	BtErpPrice              pgtype.Numeric
	DiscountPercentage      pgtype.Numeric
	TotalPrice              pgtype.Numeric
	FlightNumber            *string
	CountryCode             string
	PickupDate              pgtype.Date
	DropoffDate             pgtype.Date
	PickupTime              string
	DropoffTime             string
	RentalDays              int32
	PickupLocationName      string
	DropoffLocationName     string
	DriverTitle             string
	DriverFirstName         string
	DriverLastName          string
	DriverAge               int32
	VoucherNumber           *string
	VoucheredAt             pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	PaymentConfirmationCode *string
	PaymentDocNum           *string
	InvoiceDocNum           *string
	Excess                  int32
	ExcessCurrency          string
	SupplierTermsID         *int64
	PickupDetails           []byte
	DropoffDetails          []byte
	PickupLocationCode      string
	DropoffLocationCode     string
	SupplierPaidAt          pgtype.Timestamptz
	SupplierExpenseID       *string
	PaymentReceivedAt       pgtype.Timestamptz
}

type ReservationPenalty struct {
	ID                int64
	ReservationID     int64
	PenaltyType       PenaltyType
	CreatedByUserID   *int64
	CurrencyCode      string
	CurrencyRate      pgtype.Numeric
	Amount            pgtype.Numeric
	PaidAt            pgtype.Timestamptz
	InvoiceDocNum     *string
	PaymentDocNum     *string
	SupplierPaidAt    pgtype.Timestamptz
	SupplierExpenseID *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type SupplierTerm struct {
	ID               int64
	Broker           Broker
	SupplierCode     string
	PickupLocationID string
	Terms            []byte
}
