// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: outbox_query.sql

package db

import (
	"context"
)

const getOutboxByTopic = `-- name: GetOutboxByTopic :many
SELECT id, topic, data, inserted_at
FROM outbox
WHERE topic = $1
ORDER BY id DESC
`

func (q *Queries) GetOutboxByTopic(ctx context.Context, topic string) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getOutboxByTopic, topic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Data,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
