// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	ApplyVoucher(ctx context.Context, arg ApplyVoucherParams) error
	CancelReservation(ctx context.Context, id int64) error
	CountReservationsByUser(ctx context.Context, arg CountReservationsByUserParams) (int64, error)
	CountReservationsReport(ctx context.Context, arg CountReservationsReportParams) (CountReservationsReportRow, error)
	GetBillingReservation(ctx context.Context, id int64) (GetBillingReservationRow, error)
	GetOpenReservationsPickingUpWithinWeek(ctx context.Context) ([]GetOpenReservationsPickingUpWithinWeekRow, error)
	GetOutboxByTopic(ctx context.Context, topic string) ([]Outbox, error)
	GetPaymentPendingReservations(ctx context.Context) ([]GetPaymentPendingReservationsRow, error)
	GetPaymentPendingReservationsByBillingEntity(ctx context.Context, arg GetPaymentPendingReservationsByBillingEntityParams) ([]GetPaymentPendingReservationsByBillingEntityRow, error)
	GetReservationByID(ctx context.Context, id int64) (Reservation, error)
	InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error)
	ListBusinessesBalancesReport(ctx context.Context) ([]ListBusinessesBalancesReportRow, error)
	ListReservationsByUser(ctx context.Context, arg ListReservationsByUserParams) ([]ListReservationsByUserRow, error)
	ListReservationsReport(ctx context.Context, arg ListReservationsReportParams) ([]Reservation, error)
	ResolveReservationsPayment(ctx context.Context, ids []int64) error
	UpdateReservationCurrencyRate(ctx context.Context, arg UpdateReservationCurrencyRateParams) error
	VoucherReservationAfterPayment(ctx context.Context, arg VoucherReservationAfterPaymentParams) (Reservation, error)
}

var _ Querier = (*Queries)(nil)
