// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	ApplyVoucher(ctx context.Context, arg ApplyVoucherParams) (int64, error)
	CancelReservation(ctx context.Context, id int64) error
	CountReservationsByUser(ctx context.Context, arg CountReservationsByUserParams) (int64, error)
	GetReservationByID(ctx context.Context, id int64) (GetReservationByIDRow, error)
	InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error)
	ListReservationsByUser(ctx context.Context, arg ListReservationsByUserParams) ([]ListReservationsByUserRow, error)
}

var _ Querier = (*Queries)(nil)
