// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	ApplyVoucher(ctx context.Context, arg ApplyVoucherParams) (Reservation, error)
	CancelReservation(ctx context.Context, id int64) error
	CountReservationsByUser(ctx context.Context, arg CountReservationsByUserParams) (int64, error)
	GetOpenReservationsPickingUpWithinWeek(ctx context.Context) ([]GetOpenReservationsPickingUpWithinWeekRow, error)
	GetOutboxByTopic(ctx context.Context, topic string) ([]Outbox, error)
	GetPaymentPendingReservations(ctx context.Context) ([]GetPaymentPendingReservationsRow, error)
	GetPaymentPendingReservationsByAgentsIDs(ctx context.Context, agentIds []int64) ([]GetPaymentPendingReservationsByAgentsIDsRow, error)
	GetReservationByID(ctx context.Context, id int64) (GetReservationByIDRow, error)
	InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error)
	ListReservationsByUser(ctx context.Context, arg ListReservationsByUserParams) ([]ListReservationsByUserRow, error)
	ResolveReservationsPayment(ctx context.Context, ids []int64) error
}

var _ Querier = (*Queries)(nil)
