// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reservation_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertReservation = `-- name: InsertReservation :one
INSERT INTO reservations (
    user_id,
    broker_reservation_id,
    status,
    broker,
    supplier_code,
    car_details,
    plan_inclusions,
    country_code,
    currency_code,
    currency_rate,
    purchase_price,
    price_before_discount,
    price_after_discount,
    discount_percentage,
    erp_price,
    total_price,
    pickup_date,
    return_date,
    rental_days,
    driver_title,
    driver_first_name,
    driver_last_name,
    driver_age
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23
) RETURNING id
`

type InsertReservationParams struct {
	UserID              int32
	BrokerReservationID string
	Status              ReservationStatus
	Broker              Broker
	SupplierCode        string
	CarDetails          []byte
	PlanInclusions      []string
	CountryCode         string
	CurrencyCode        string
	CurrencyRate        pgtype.Numeric
	PurchasePrice       pgtype.Numeric
	PriceBeforeDiscount pgtype.Numeric
	PriceAfterDiscount  pgtype.Numeric
	DiscountPercentage  int32
	ErpPrice            pgtype.Numeric
	TotalPrice          pgtype.Numeric
	PickupDate          pgtype.Date
	ReturnDate          pgtype.Date
	RentalDays          int32
	DriverTitle         string
	DriverFirstName     string
	DriverLastName      string
	DriverAge           int32
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReservation,
		arg.UserID,
		arg.BrokerReservationID,
		arg.Status,
		arg.Broker,
		arg.SupplierCode,
		arg.CarDetails,
		arg.PlanInclusions,
		arg.CountryCode,
		arg.CurrencyCode,
		arg.CurrencyRate,
		arg.PurchasePrice,
		arg.PriceBeforeDiscount,
		arg.PriceAfterDiscount,
		arg.DiscountPercentage,
		arg.ErpPrice,
		arg.TotalPrice,
		arg.PickupDate,
		arg.ReturnDate,
		arg.RentalDays,
		arg.DriverTitle,
		arg.DriverFirstName,
		arg.DriverLastName,
		arg.DriverAge,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listReservationsByUser = `-- name: ListReservationsByUser :many
SELECT
    id,
    broker_reservation_id,
    created_at,
    country_code,
    pickup_date,
    driver_title,
    driver_first_name,
    driver_last_name,
    status,
    total_price
FROM reservations
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3::int
OFFSET $2::int
`

type ListReservationsByUserParams struct {
	UserID      int32
	QueryOffset int32
	QueryLimit  int32
}

type ListReservationsByUserRow struct {
	ID                  int64
	BrokerReservationID string
	CreatedAt           pgtype.Timestamptz
	CountryCode         string
	PickupDate          pgtype.Date
	DriverTitle         string
	DriverFirstName     string
	DriverLastName      string
	Status              ReservationStatus
	TotalPrice          pgtype.Numeric
}

func (q *Queries) ListReservationsByUser(ctx context.Context, arg ListReservationsByUserParams) ([]ListReservationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReservationsByUser, arg.UserID, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationsByUserRow
	for rows.Next() {
		var i ListReservationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BrokerReservationID,
			&i.CreatedAt,
			&i.CountryCode,
			&i.PickupDate,
			&i.DriverTitle,
			&i.DriverFirstName,
			&i.DriverLastName,
			&i.Status,
			&i.TotalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
