// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reservation_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertReservation = `-- name: InsertReservation :one
INSERT INTO reservations (
    user_id,
    broker_reservation_id,
    status,
    broker,
    supplier_code,
    car_details,
    plan_inclusions,
    country_code,
    currency_code,
    currency_rate,
    purchase_price,
    price_before_discount,
    price_after_discount,
    discount_percentage,
    erp_price,
    total_price,
    pickup_date,
    return_date,
    rental_days,
    driver_title,
    driver_first_name,
    driver_last_name,
    driver_age
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23
) RETURNING id
`

type InsertReservationParams struct {
	UserID              int32
	BrokerReservationID string
	Status              ReservationStatus
	Broker              Broker
	SupplierCode        string
	CarDetails          []byte
	PlanInclusions      []string
	CountryCode         string
	CurrencyCode        string
	CurrencyRate        pgtype.Numeric
	PurchasePrice       pgtype.Numeric
	PriceBeforeDiscount pgtype.Numeric
	PriceAfterDiscount  pgtype.Numeric
	DiscountPercentage  int32
	ErpPrice            pgtype.Numeric
	TotalPrice          pgtype.Numeric
	PickupDate          pgtype.Date
	ReturnDate          pgtype.Date
	RentalDays          int32
	DriverTitle         string
	DriverFirstName     string
	DriverLastName      string
	DriverAge           int32
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReservation,
		arg.UserID,
		arg.BrokerReservationID,
		arg.Status,
		arg.Broker,
		arg.SupplierCode,
		arg.CarDetails,
		arg.PlanInclusions,
		arg.CountryCode,
		arg.CurrencyCode,
		arg.CurrencyRate,
		arg.PurchasePrice,
		arg.PriceBeforeDiscount,
		arg.PriceAfterDiscount,
		arg.DiscountPercentage,
		arg.ErpPrice,
		arg.TotalPrice,
		arg.PickupDate,
		arg.ReturnDate,
		arg.RentalDays,
		arg.DriverTitle,
		arg.DriverFirstName,
		arg.DriverLastName,
		arg.DriverAge,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
