// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation_penalty_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPaymentPendingPenalties = `-- name: GetPaymentPendingPenalties :many
SELECT
    p.id,
    p.reservation_id,
    p.penalty_type,
    p.amount,
    p.currency_code,
    r.broker_reservation_id,
    r.user_id,
    r.created_at,
    r.vouchered_at,
    r.voucher_number,
    r.driver_title,
    r.driver_first_name,
    r.driver_last_name,
    r.pickup_date,
    r.dropoff_date,
    r.rental_days,
    r.country_code
FROM reservation_penalties p
JOIN reservations r ON r.id = p.reservation_id
WHERE p.paid_at IS NULL
`

type GetPaymentPendingPenaltiesRow struct {
	ID                  int64
	ReservationID       int64
	PenaltyType         PenaltyType
	Amount              pgtype.Numeric
	CurrencyCode        string
	BrokerReservationID string
	UserID              int64
	CreatedAt           pgtype.Timestamptz
	VoucheredAt         pgtype.Timestamptz
	VoucherNumber       *string
	DriverTitle         string
	DriverFirstName     string
	DriverLastName      string
	PickupDate          pgtype.Date
	DropoffDate         pgtype.Date
	RentalDays          int32
	CountryCode         string
}

func (q *Queries) GetPaymentPendingPenalties(ctx context.Context) ([]GetPaymentPendingPenaltiesRow, error) {
	rows, err := q.db.Query(ctx, getPaymentPendingPenalties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentPendingPenaltiesRow
	for rows.Next() {
		var i GetPaymentPendingPenaltiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.PenaltyType,
			&i.Amount,
			&i.CurrencyCode,
			&i.BrokerReservationID,
			&i.UserID,
			&i.CreatedAt,
			&i.VoucheredAt,
			&i.VoucherNumber,
			&i.DriverTitle,
			&i.DriverFirstName,
			&i.DriverLastName,
			&i.PickupDate,
			&i.DropoffDate,
			&i.RentalDays,
			&i.CountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentPendingPenaltiesByBillingEntity = `-- name: GetPaymentPendingPenaltiesByBillingEntity :many
SELECT
    p.id,
    p.reservation_id,
    r.broker_reservation_id,
    p.penalty_type,
    p.amount,
    p.currency_code,
    p.currency_rate,
    p.created_at
FROM reservation_penalties p
JOIN reservations r ON r.id = p.reservation_id
WHERE
    (
        (
            $1::BIGINT IS NULL
            AND ($2::BIGINT) IS NOT NULL
            AND r.organization_id = $2::BIGINT
            AND r.is_organization_organic = TRUE
        )
    OR
        (
            $2::BIGINT IS NULL
            AND ($1::BIGINT) IS NOT NULL
            AND r.office_id = $1::BIGINT
            AND r.is_organization_organic = FALSE
        )
    )
    AND p.paid_at IS NULL
ORDER BY p.created_at
`

type GetPaymentPendingPenaltiesByBillingEntityParams struct {
	OfficeID       *int64
	OrganizationID *int64
}

type GetPaymentPendingPenaltiesByBillingEntityRow struct {
	ID                  int64
	ReservationID       int64
	BrokerReservationID string
	PenaltyType         PenaltyType
	Amount              pgtype.Numeric
	CurrencyCode        string
	CurrencyRate        pgtype.Numeric
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) GetPaymentPendingPenaltiesByBillingEntity(ctx context.Context, arg GetPaymentPendingPenaltiesByBillingEntityParams) ([]GetPaymentPendingPenaltiesByBillingEntityRow, error) {
	rows, err := q.db.Query(ctx, getPaymentPendingPenaltiesByBillingEntity, arg.OfficeID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentPendingPenaltiesByBillingEntityRow
	for rows.Next() {
		var i GetPaymentPendingPenaltiesByBillingEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.BrokerReservationID,
			&i.PenaltyType,
			&i.Amount,
			&i.CurrencyCode,
			&i.CurrencyRate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservationPenaltyByReservationID = `-- name: GetReservationPenaltyByReservationID :one
SELECT id, reservation_id, penalty_type, created_by_user_id, currency_code, currency_rate, amount, paid_at, invoice_doc_num, payment_doc_num, supplier_paid_at, supplier_expense_id, created_at, updated_at
FROM reservation_penalties
WHERE reservation_id = $1
`

func (q *Queries) GetReservationPenaltyByReservationID(ctx context.Context, reservationID int64) (ReservationPenalty, error) {
	row := q.db.QueryRow(ctx, getReservationPenaltyByReservationID, reservationID)
	var i ReservationPenalty
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.PenaltyType,
		&i.CreatedByUserID,
		&i.CurrencyCode,
		&i.CurrencyRate,
		&i.Amount,
		&i.PaidAt,
		&i.InvoiceDocNum,
		&i.PaymentDocNum,
		&i.SupplierPaidAt,
		&i.SupplierExpenseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReservationPenalty = `-- name: InsertReservationPenalty :one
INSERT INTO reservation_penalties (
    reservation_id,
    penalty_type,
    created_by_user_id,
    currency_code,
    currency_rate,
    amount
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, reservation_id, penalty_type, created_by_user_id, currency_code, currency_rate, amount, paid_at, invoice_doc_num, payment_doc_num, supplier_paid_at, supplier_expense_id, created_at, updated_at
`

type InsertReservationPenaltyParams struct {
	ReservationID   int64
	PenaltyType     PenaltyType
	CreatedByUserID *int64
	CurrencyCode    string
	CurrencyRate    pgtype.Numeric
	Amount          pgtype.Numeric
}

func (q *Queries) InsertReservationPenalty(ctx context.Context, arg InsertReservationPenaltyParams) (ReservationPenalty, error) {
	row := q.db.QueryRow(ctx, insertReservationPenalty,
		arg.ReservationID,
		arg.PenaltyType,
		arg.CreatedByUserID,
		arg.CurrencyCode,
		arg.CurrencyRate,
		arg.Amount,
	)
	var i ReservationPenalty
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.PenaltyType,
		&i.CreatedByUserID,
		&i.CurrencyCode,
		&i.CurrencyRate,
		&i.Amount,
		&i.PaidAt,
		&i.InvoiceDocNum,
		&i.PaymentDocNum,
		&i.SupplierPaidAt,
		&i.SupplierExpenseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnpaidSupplierPenalties = `-- name: ListUnpaidSupplierPenalties :many
SELECT
    p.id,
    p.reservation_id,
    p.penalty_type,
    p.amount,
    p.currency_code,
    r.broker_reservation_id,
    r.driver_title,
    r.driver_first_name,
    r.driver_last_name,
    r.pickup_date,
    r.pickup_location_name
FROM reservation_penalties p
JOIN reservations r ON r.id = p.reservation_id
WHERE
    r.broker = $1::broker
    AND p.supplier_paid_at IS NULL
ORDER BY r.pickup_date, p.id
`

type ListUnpaidSupplierPenaltiesRow struct {
	ID                  int64
	ReservationID       int64
	PenaltyType         PenaltyType
	Amount              pgtype.Numeric
	CurrencyCode        string
	BrokerReservationID string
	DriverTitle         string
	DriverFirstName     string
	DriverLastName      string
	PickupDate          pgtype.Date
	PickupLocationName  string
}

func (q *Queries) ListUnpaidSupplierPenalties(ctx context.Context, broker Broker) ([]ListUnpaidSupplierPenaltiesRow, error) {
	rows, err := q.db.Query(ctx, listUnpaidSupplierPenalties, broker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnpaidSupplierPenaltiesRow
	for rows.Next() {
		var i ListUnpaidSupplierPenaltiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.PenaltyType,
			&i.Amount,
			&i.CurrencyCode,
			&i.BrokerReservationID,
			&i.DriverTitle,
			&i.DriverFirstName,
			&i.DriverLastName,
			&i.PickupDate,
			&i.PickupLocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPenaltiesPaidToSupplier = `-- name: MarkPenaltiesPaidToSupplier :exec
UPDATE reservation_penalties
SET
    supplier_paid_at = $1::TIMESTAMPTZ,
    supplier_expense_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ANY($3::BIGINT[])
AND supplier_paid_at IS NULL
`

type MarkPenaltiesPaidToSupplierParams struct {
	SupplierPaidAt    pgtype.Timestamptz
	SupplierExpenseID *string
	Ids               []int64
}

func (q *Queries) MarkPenaltiesPaidToSupplier(ctx context.Context, arg MarkPenaltiesPaidToSupplierParams) error {
	_, err := q.db.Exec(ctx, markPenaltiesPaidToSupplier, arg.SupplierPaidAt, arg.SupplierExpenseID, arg.Ids)
	return err
}

const resolvePenaltiesPayment = `-- name: ResolvePenaltiesPayment :exec
UPDATE reservation_penalties
SET
    paid_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ANY($1::BIGINT[])
AND paid_at IS NULL
`

func (q *Queries) ResolvePenaltiesPayment(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, resolvePenaltiesPayment, ids)
	return err
}
