// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation_penalty_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReservationPenaltyByReservationID = `-- name: GetReservationPenaltyByReservationID :one
SELECT id, reservation_id, penalty_type, created_by_user_id, currency_code, currency_rate, amount, paid_at, invoice_doc_num, payment_doc_num, supplier_paid_at, supplier_expense_id, created_at, updated_at
FROM reservation_penalties
WHERE reservation_id = $1
`

func (q *Queries) GetReservationPenaltyByReservationID(ctx context.Context, reservationID int64) (ReservationPenalty, error) {
	row := q.db.QueryRow(ctx, getReservationPenaltyByReservationID, reservationID)
	var i ReservationPenalty
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.PenaltyType,
		&i.CreatedByUserID,
		&i.CurrencyCode,
		&i.CurrencyRate,
		&i.Amount,
		&i.PaidAt,
		&i.InvoiceDocNum,
		&i.PaymentDocNum,
		&i.SupplierPaidAt,
		&i.SupplierExpenseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReservationPenalty = `-- name: InsertReservationPenalty :one
INSERT INTO reservation_penalties (
    reservation_id,
    penalty_type,
    created_by_user_id,
    currency_code,
    currency_rate,
    amount
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, reservation_id, penalty_type, created_by_user_id, currency_code, currency_rate, amount, paid_at, invoice_doc_num, payment_doc_num, supplier_paid_at, supplier_expense_id, created_at, updated_at
`

type InsertReservationPenaltyParams struct {
	ReservationID   int64
	PenaltyType     PenaltyType
	CreatedByUserID *int64
	CurrencyCode    string
	CurrencyRate    pgtype.Numeric
	Amount          pgtype.Numeric
}

func (q *Queries) InsertReservationPenalty(ctx context.Context, arg InsertReservationPenaltyParams) (ReservationPenalty, error) {
	row := q.db.QueryRow(ctx, insertReservationPenalty,
		arg.ReservationID,
		arg.PenaltyType,
		arg.CreatedByUserID,
		arg.CurrencyCode,
		arg.CurrencyRate,
		arg.Amount,
	)
	var i ReservationPenalty
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.PenaltyType,
		&i.CreatedByUserID,
		&i.CurrencyCode,
		&i.CurrencyRate,
		&i.Amount,
		&i.PaidAt,
		&i.InvoiceDocNum,
		&i.PaymentDocNum,
		&i.SupplierPaidAt,
		&i.SupplierExpenseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
