// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reservation_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReservationByID = `-- name: GetReservationByID :one
SELECT
    id,
    user_id,
    broker_reservation_id,
    status,
    broker,
    supplier_code,
    car_details,
    plan_inclusions,
    country_code,
    currency_code,
    currency_rate,
    purchase_price,
    markup_percentage,
    discount_percentage,
    broker_erp_price,
    bt_erp_price,
    vat_percentage,
    total_price,
    pickup_date,
    return_date,
    rental_days,
    driver_title,
    driver_first_name,
    driver_last_name,
    driver_age,
    pickup_location_name,
    dropoff_location_name,
    created_at
FROM reservations
WHERE id = $1
`

type GetReservationByIDRow struct {
	ID                  int64
	UserID              int32
	BrokerReservationID string
	Status              ReservationStatus
	Broker              Broker
	SupplierCode        string
	CarDetails          []byte
	PlanInclusions      []string
	CountryCode         string
	CurrencyCode        string
	CurrencyRate        pgtype.Numeric
	PurchasePrice       pgtype.Numeric
	MarkupPercentage    pgtype.Numeric
	DiscountPercentage  int32
	BrokerErpPrice      pgtype.Numeric
	BtErpPrice          int32
	VatPercentage       pgtype.Numeric
	TotalPrice          int32
	PickupDate          pgtype.Date
	ReturnDate          pgtype.Date
	RentalDays          int32
	DriverTitle         string
	DriverFirstName     string
	DriverLastName      string
	DriverAge           int32
	PickupLocationName  string
	DropoffLocationName string
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) GetReservationByID(ctx context.Context, id int64) (GetReservationByIDRow, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i GetReservationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrokerReservationID,
		&i.Status,
		&i.Broker,
		&i.SupplierCode,
		&i.CarDetails,
		&i.PlanInclusions,
		&i.CountryCode,
		&i.CurrencyCode,
		&i.CurrencyRate,
		&i.PurchasePrice,
		&i.MarkupPercentage,
		&i.DiscountPercentage,
		&i.BrokerErpPrice,
		&i.BtErpPrice,
		&i.VatPercentage,
		&i.TotalPrice,
		&i.PickupDate,
		&i.ReturnDate,
		&i.RentalDays,
		&i.DriverTitle,
		&i.DriverFirstName,
		&i.DriverLastName,
		&i.DriverAge,
		&i.PickupLocationName,
		&i.DropoffLocationName,
		&i.CreatedAt,
	)
	return i, err
}

const insertReservation = `-- name: InsertReservation :one
INSERT INTO reservations (
    user_id,
    broker_reservation_id,
    status,
    broker,
    supplier_code,
    car_details,
    plan_inclusions,
    country_code,
    currency_code,
    currency_rate,
    purchase_price,
    markup_percentage,
    discount_percentage,
    broker_erp_price,
    bt_erp_price,
    vat_percentage,
    total_price,
    pickup_date,
    return_date,
    rental_days,
    driver_title,
    driver_first_name,
    driver_last_name,
    driver_age,
    pickup_location_name,
    dropoff_location_name
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26
) RETURNING id
`

type InsertReservationParams struct {
	UserID              int32
	BrokerReservationID string
	Status              ReservationStatus
	Broker              Broker
	SupplierCode        string
	CarDetails          []byte
	PlanInclusions      []string
	CountryCode         string
	CurrencyCode        string
	CurrencyRate        pgtype.Numeric
	PurchasePrice       pgtype.Numeric
	MarkupPercentage    pgtype.Numeric
	DiscountPercentage  int32
	BrokerErpPrice      pgtype.Numeric
	BtErpPrice          int32
	VatPercentage       pgtype.Numeric
	TotalPrice          int32
	PickupDate          pgtype.Date
	ReturnDate          pgtype.Date
	RentalDays          int32
	DriverTitle         string
	DriverFirstName     string
	DriverLastName      string
	DriverAge           int32
	PickupLocationName  string
	DropoffLocationName string
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReservation,
		arg.UserID,
		arg.BrokerReservationID,
		arg.Status,
		arg.Broker,
		arg.SupplierCode,
		arg.CarDetails,
		arg.PlanInclusions,
		arg.CountryCode,
		arg.CurrencyCode,
		arg.CurrencyRate,
		arg.PurchasePrice,
		arg.MarkupPercentage,
		arg.DiscountPercentage,
		arg.BrokerErpPrice,
		arg.BtErpPrice,
		arg.VatPercentage,
		arg.TotalPrice,
		arg.PickupDate,
		arg.ReturnDate,
		arg.RentalDays,
		arg.DriverTitle,
		arg.DriverFirstName,
		arg.DriverLastName,
		arg.DriverAge,
		arg.PickupLocationName,
		arg.DropoffLocationName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listReservationsByUser = `-- name: ListReservationsByUser :many
SELECT
    id,
    broker_reservation_id,
    created_at,
    country_code,
    pickup_date,
    driver_title,
    driver_first_name,
    driver_last_name,
    status,
    total_price
FROM reservations
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3::int
OFFSET $2::int
`

type ListReservationsByUserParams struct {
	UserID      int32
	QueryOffset int32
	QueryLimit  int32
}

type ListReservationsByUserRow struct {
	ID                  int64
	BrokerReservationID string
	CreatedAt           pgtype.Timestamptz
	CountryCode         string
	PickupDate          pgtype.Date
	DriverTitle         string
	DriverFirstName     string
	DriverLastName      string
	Status              ReservationStatus
	TotalPrice          int32
}

func (q *Queries) ListReservationsByUser(ctx context.Context, arg ListReservationsByUserParams) ([]ListReservationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReservationsByUser, arg.UserID, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationsByUserRow
	for rows.Next() {
		var i ListReservationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BrokerReservationID,
			&i.CreatedAt,
			&i.CountryCode,
			&i.PickupDate,
			&i.DriverTitle,
			&i.DriverFirstName,
			&i.DriverLastName,
			&i.Status,
			&i.TotalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
