// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supplier_terms_query.sql

package db

import (
	"context"
)

const getSupplierTermsByID = `-- name: GetSupplierTermsByID :one
SELECT terms
FROM supplier_terms
WHERE id = $1
`

func (q *Queries) GetSupplierTermsByID(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSupplierTermsByID, id)
	var terms []byte
	err := row.Scan(&terms)
	return terms, err
}

const upsertSupplierTerms = `-- name: UpsertSupplierTerms :one
INSERT INTO supplier_terms (
    broker,
    supplier_code,
    pickup_location_id,
    terms
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (broker, supplier_code, pickup_location_id)
DO UPDATE SET terms = EXCLUDED.terms
RETURNING id
`

type UpsertSupplierTermsParams struct {
	Broker           Broker
	SupplierCode     string
	PickupLocationID string
	Terms            []byte
}

func (q *Queries) UpsertSupplierTerms(ctx context.Context, arg UpsertSupplierTermsParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSupplierTerms,
		arg.Broker,
		arg.SupplierCode,
		arg.PickupLocationID,
		arg.Terms,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
