// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: contacts_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countContacts = `-- name: CountContacts :one
SELECT COUNT(*)::BIGINT AS total
FROM contacts c
LEFT JOIN offices o ON o.id = c.office_id
WHERE
    ($1::VARCHAR IS NULL OR c.first_name ILIKE '%' || $1::VARCHAR || '%' OR c.last_name ILIKE '%' || $1::VARCHAR || '%')
    AND ($2::INTEGER IS NULL       OR c.office_id = $2::INTEGER)
    AND ($3::INTEGER IS NULL OR c.organization_id = $3::INTEGER OR o.organization_id = $3::INTEGER)
`

type CountContactsParams struct {
	Name           *string
	OfficeID       *int32
	OrganizationID *int32
}

func (q *Queries) CountContacts(ctx context.Context, arg CountContactsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContacts, arg.Name, arg.OfficeID, arg.OrganizationID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (first_name, last_name, role, cellphone, email, office_id, organization_id, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
RETURNING id, first_name, last_name, role, cellphone, email, office_id, organization_id, created_at, updated_at
`

type CreateContactParams struct {
	FirstName      string
	LastName       string
	Role           string
	Cellphone      string
	Email          string
	OfficeID       *int32
	OrganizationID *int32
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.Cellphone,
		arg.Email,
		arg.OfficeID,
		arg.OrganizationID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Cellphone,
		&i.Email,
		&i.OfficeID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts
WHERE id = $1
`

func (q *Queries) DeleteContact(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteContact, id)
	return err
}

const listContacts = `-- name: ListContacts :many
SELECT
    c.id,
    c.first_name,
    c.last_name,
    c.role,
    c.cellphone,
    c.email,
    c.office_id,
    c.organization_id,
    c.created_at,
    c.updated_at,
    o.name  AS office_name,
    org.name AS organization_name
FROM contacts c
LEFT JOIN offices       o   ON o.id   = c.office_id
LEFT JOIN organizations org ON org.id = c.organization_id
WHERE
    ($1::VARCHAR IS NULL OR c.first_name ILIKE '%' || $1::VARCHAR || '%' OR c.last_name ILIKE '%' || $1::VARCHAR || '%')
    AND ($2::INTEGER IS NULL       OR c.office_id = $2::INTEGER)
    AND ($3::INTEGER IS NULL OR c.organization_id = $3::INTEGER OR o.organization_id = $3::INTEGER)
ORDER BY c.last_name, c.first_name
LIMIT  $5::BIGINT
OFFSET $4::BIGINT
`

type ListContactsParams struct {
	Name           *string
	OfficeID       *int32
	OrganizationID *int32
	PageOffset     int64
	PageSize       int64
}

type ListContactsRow struct {
	ID               int32
	FirstName        string
	LastName         string
	Role             string
	Cellphone        string
	Email            string
	OfficeID         *int32
	OrganizationID   *int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	OfficeName       *string
	OrganizationName *string
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]ListContactsRow, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.Name,
		arg.OfficeID,
		arg.OrganizationID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsRow
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.Cellphone,
			&i.Email,
			&i.OfficeID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OfficeName,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET
    first_name      = COALESCE($1,      first_name),
    last_name       = COALESCE($2,       last_name),
    role            = COALESCE($3,            role),
    cellphone       = COALESCE($4,       cellphone),
    email           = COALESCE($5,           email),
    office_id       = COALESCE($6,       office_id),
    organization_id = COALESCE($7, organization_id),
    updated_at      = CURRENT_TIMESTAMP
WHERE id = $8
RETURNING id, first_name, last_name, role, cellphone, email, office_id, organization_id, created_at, updated_at
`

type UpdateContactParams struct {
	FirstName      *string
	LastName       *string
	Role           *string
	Cellphone      *string
	Email          *string
	OfficeID       *int32
	OrganizationID *int32
	ID             int32
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.Cellphone,
		arg.Email,
		arg.OfficeID,
		arg.OrganizationID,
		arg.ID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Cellphone,
		&i.Email,
		&i.OfficeID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
