// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: offices_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOffices = `-- name: CountOffices :one
SELECT COUNT(*)::BIGINT AS total
FROM offices o
WHERE
    ($1::VARCHAR IS NULL            OR o.name ILIKE '%' || $1::VARCHAR || '%')
    AND ($2::INTEGER IS NULL OR o.organization_id = $2::INTEGER)
`

type CountOfficesParams struct {
	Name           *string
	OrganizationID *int32
}

func (q *Queries) CountOffices(ctx context.Context, arg CountOfficesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOffices, arg.Name, arg.OrganizationID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createOffice = `-- name: CreateOffice :one
INSERT INTO offices (name, organization_id, phone, address, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
RETURNING id, name, organization_id, phone, address, created_at, updated_at
`

type CreateOfficeParams struct {
	Name           string
	OrganizationID int32
	Phone          *string
	Address        *string
}

func (q *Queries) CreateOffice(ctx context.Context, arg CreateOfficeParams) (Office, error) {
	row := q.db.QueryRow(ctx, createOffice,
		arg.Name,
		arg.OrganizationID,
		arg.Phone,
		arg.Address,
	)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInorganicOffices = `-- name: ListInorganicOffices :many
SELECT
    o.id, o.name
FROM offices as o
JOIN organizations org ON org.id = o.organization_id
WHERE org.inorganic = TRUE
ORDER BY o.name
`

type ListInorganicOfficesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListInorganicOffices(ctx context.Context) ([]ListInorganicOfficesRow, error) {
	rows, err := q.db.Query(ctx, listInorganicOffices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInorganicOfficesRow
	for rows.Next() {
		var i ListInorganicOfficesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffices = `-- name: ListOffices :many
SELECT
    o.id,
    o.name,
    o.organization_id,
    org.name AS organization_name,
    o.phone,
    o.address,
    o.created_at,
    o.updated_at,
    COUNT(DISTINCT c.id)::BIGINT  AS contact_count,
    COUNT(DISTINCT u.id)::BIGINT  AS agent_count
FROM offices o
JOIN organizations org ON org.id = o.organization_id
LEFT JOIN contacts c ON c.office_id = o.id
LEFT JOIN users u ON (u.office_id = o.id AND u.role = 'agent')
WHERE
    ($1::VARCHAR IS NULL            OR o.name ILIKE '%' || $1::VARCHAR || '%')
    AND ($2::INTEGER IS NULL OR o.organization_id = $2::INTEGER)
GROUP BY o.id, org.name
ORDER BY o.name
LIMIT  $4::BIGINT
OFFSET $3::BIGINT
`

type ListOfficesParams struct {
	Name           *string
	OrganizationID *int32
	PageOffset     int64
	PageSize       int64
}

type ListOfficesRow struct {
	ID               int32
	Name             string
	OrganizationID   int32
	OrganizationName string
	Phone            *string
	Address          *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ContactCount     int64
	AgentCount       int64
}

func (q *Queries) ListOffices(ctx context.Context, arg ListOfficesParams) ([]ListOfficesRow, error) {
	rows, err := q.db.Query(ctx, listOffices,
		arg.Name,
		arg.OrganizationID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOfficesRow
	for rows.Next() {
		var i ListOfficesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Phone,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactCount,
			&i.AgentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOffice = `-- name: UpdateOffice :one
UPDATE offices
SET
    name            = COALESCE($1,            name),
    organization_id = COALESCE($2, organization_id),
    phone           = COALESCE($3,           phone),
    address         = COALESCE($4,         address),
    updated_at      = CURRENT_TIMESTAMP
WHERE id = $5
RETURNING id, name, organization_id, phone, address, created_at, updated_at
`

type UpdateOfficeParams struct {
	Name           *string
	OrganizationID *int32
	Phone          *string
	Address        *string
	ID             int32
}

func (q *Queries) UpdateOffice(ctx context.Context, arg UpdateOfficeParams) (Office, error) {
	row := q.db.QueryRow(ctx, updateOffice,
		arg.Name,
		arg.OrganizationID,
		arg.Phone,
		arg.Address,
		arg.ID,
	)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
