// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offices_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOffices = `-- name: CountOffices :one
SELECT COUNT(*)::BIGINT AS total
FROM offices o
WHERE
    ($1::TEXT IS NULL            OR o.name ILIKE '%' || $1::TEXT || '%')
    AND ($2::BIGINT IS NULL OR o.organization_id = $2::BIGINT)
`

type CountOfficesParams struct {
	Name           *string
	OrganizationID *int64
}

func (q *Queries) CountOffices(ctx context.Context, arg CountOfficesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOffices, arg.Name, arg.OrganizationID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createOffice = `-- name: CreateOffice :one
INSERT INTO offices (name, organization_id, icount_client_id, phone, address, obligo, gross_markup, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
RETURNING id, name, organization_id, icount_client_id, phone, address, gross_markup, created_at, updated_at
`

type CreateOfficeParams struct {
	Name           string
	OrganizationID int64
	IcountClientID *int32
	Phone          *string
	Address        *string
	Obligo         *int32
	GrossMarkup    pgtype.Numeric
}

type CreateOfficeRow struct {
	ID             int64
	Name           string
	OrganizationID int64
	IcountClientID *int32
	Phone          *string
	Address        *string
	GrossMarkup    pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateOffice(ctx context.Context, arg CreateOfficeParams) (CreateOfficeRow, error) {
	row := q.db.QueryRow(ctx, createOffice,
		arg.Name,
		arg.OrganizationID,
		arg.IcountClientID,
		arg.Phone,
		arg.Address,
		arg.Obligo,
		arg.GrossMarkup,
	)
	var i CreateOfficeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.IcountClientID,
		&i.Phone,
		&i.Address,
		&i.GrossMarkup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfficeBillingState = `-- name: GetOfficeBillingState :one
SELECT o.icount_client_id, o.organization_id, org.is_organic
FROM offices o
JOIN organizations org ON org.id = o.organization_id
WHERE o.id = $1::BIGINT
`

type GetOfficeBillingStateRow struct {
	IcountClientID *int32
	OrganizationID int64
	IsOrganic      bool
}

func (q *Queries) GetOfficeBillingState(ctx context.Context, id int64) (GetOfficeBillingStateRow, error) {
	row := q.db.QueryRow(ctx, getOfficeBillingState, id)
	var i GetOfficeBillingStateRow
	err := row.Scan(&i.IcountClientID, &i.OrganizationID, &i.IsOrganic)
	return i, err
}

const getOfficeIcountClientID = `-- name: GetOfficeIcountClientID :one
SELECT icount_client_id
FROM offices
WHERE id = $1::BIGINT
`

func (q *Queries) GetOfficeIcountClientID(ctx context.Context, id int64) (*int32, error) {
	row := q.db.QueryRow(ctx, getOfficeIcountClientID, id)
	var icount_client_id *int32
	err := row.Scan(&icount_client_id)
	return icount_client_id, err
}

const getOfficeNamesByIDs = `-- name: GetOfficeNamesByIDs :many
SELECT id, name
FROM offices
WHERE id = ANY($1::BIGINT[])
`

type GetOfficeNamesByIDsRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetOfficeNamesByIDs(ctx context.Context, ids []int64) ([]GetOfficeNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getOfficeNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOfficeNamesByIDsRow
	for rows.Next() {
		var i GetOfficeNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInorganicOffices = `-- name: ListInorganicOffices :many
SELECT
    o.id, o.name
FROM offices as o
JOIN organizations org ON org.id = o.organization_id
WHERE org.is_organic = FALSE
ORDER BY o.name
`

type ListInorganicOfficesRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListInorganicOffices(ctx context.Context) ([]ListInorganicOfficesRow, error) {
	rows, err := q.db.Query(ctx, listInorganicOffices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInorganicOfficesRow
	for rows.Next() {
		var i ListInorganicOfficesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffices = `-- name: ListOffices :many
SELECT
    o.id,
    o.name,
    o.organization_id,
    org.name AS organization_name,
    o.icount_client_id,
    o.phone,
    o.address,
    o.obligo,
    o.balance_due,
    o.gross_markup,
    o.created_at,
    o.updated_at,
    COUNT(DISTINCT c.id)::BIGINT  AS contact_count,
    COUNT(DISTINCT u.id)::BIGINT  AS agent_count
FROM offices o
JOIN organizations org ON org.id = o.organization_id
LEFT JOIN contacts c ON c.office_id = o.id
LEFT JOIN users u ON (u.office_id = o.id AND u.role = 'agent')
WHERE
    ($1::TEXT IS NULL            OR o.name ILIKE '%' || $1::TEXT || '%')
    AND ($2::BIGINT IS NULL OR o.organization_id = $2::BIGINT)
GROUP BY o.id, org.name
ORDER BY o.name
LIMIT  $4::BIGINT
OFFSET $3::BIGINT
`

type ListOfficesParams struct {
	Name           *string
	OrganizationID *int64
	PageOffset     int64
	PageSize       int64
}

type ListOfficesRow struct {
	ID               int64
	Name             string
	OrganizationID   int64
	OrganizationName string
	IcountClientID   *int32
	Phone            *string
	Address          *string
	Obligo           *int32
	BalanceDue       pgtype.Numeric
	GrossMarkup      pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ContactCount     int64
	AgentCount       int64
}

func (q *Queries) ListOffices(ctx context.Context, arg ListOfficesParams) ([]ListOfficesRow, error) {
	rows, err := q.db.Query(ctx, listOffices,
		arg.Name,
		arg.OrganizationID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOfficesRow
	for rows.Next() {
		var i ListOfficesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.IcountClientID,
			&i.Phone,
			&i.Address,
			&i.Obligo,
			&i.BalanceDue,
			&i.GrossMarkup,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactCount,
			&i.AgentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOffice = `-- name: UpdateOffice :one
UPDATE offices
SET
    name             = $1,
    organization_id  = $2,
    icount_client_id = $3,
    phone            = $4,
    address          = $5,
    obligo           = $6,
    gross_markup = $7,
    updated_at       = CURRENT_TIMESTAMP
WHERE id = $8
RETURNING id, name, organization_id, icount_client_id, phone, address, obligo, gross_markup, created_at, updated_at
`

type UpdateOfficeParams struct {
	Name           string
	OrganizationID int64
	IcountClientID *int32
	Phone          *string
	Address        *string
	Obligo         *int32
	GrossMarkup    pgtype.Numeric
	ID             int64
}

type UpdateOfficeRow struct {
	ID             int64
	Name           string
	OrganizationID int64
	IcountClientID *int32
	Phone          *string
	Address        *string
	Obligo         *int32
	GrossMarkup    pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateOffice(ctx context.Context, arg UpdateOfficeParams) (UpdateOfficeRow, error) {
	row := q.db.QueryRow(ctx, updateOffice,
		arg.Name,
		arg.OrganizationID,
		arg.IcountClientID,
		arg.Phone,
		arg.Address,
		arg.Obligo,
		arg.GrossMarkup,
		arg.ID,
	)
	var i UpdateOfficeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.IcountClientID,
		&i.Phone,
		&i.Address,
		&i.Obligo,
		&i.GrossMarkup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOfficeBalanceDue = `-- name: UpdateOfficeBalanceDue :exec
UPDATE offices
SET balance_due = GREATEST(
    0,
    COALESCE(balance_due, 0) + $1::NUMERIC(10, 2)
)::NUMERIC(10, 2)
WHERE id = $2::BIGINT
`

type UpdateOfficeBalanceDueParams struct {
	Delta pgtype.Numeric
	ID    int64
}

func (q *Queries) UpdateOfficeBalanceDue(ctx context.Context, arg UpdateOfficeBalanceDueParams) error {
	_, err := q.db.Exec(ctx, updateOfficeBalanceDue, arg.Delta, arg.ID)
	return err
}
