// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: organizations_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*)::BIGINT AS total
FROM organizations o
WHERE
    ($1::TEXT IS NULL       OR o.name ILIKE '%' || $1::TEXT || '%')
    AND ($2::BOOLEAN IS NULL OR o.is_organic = $2::BOOLEAN)
`

type CountOrganizationsParams struct {
	Name      *string
	IsOrganic *bool
}

func (q *Queries) CountOrganizations(ctx context.Context, arg CountOrganizationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations, arg.Name, arg.IsOrganic)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, is_organic, icount_client_id, phone, address, obligo, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
RETURNING id, name, is_organic, icount_client_id, phone, address, obligo, created_at, updated_at, balance_due, agency_markup_percentage
`

type CreateOrganizationParams struct {
	Name           string
	IsOrganic      bool
	IcountClientID *int32
	Phone          *string
	Address        *string
	Obligo         *int32
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.IsOrganic,
		arg.IcountClientID,
		arg.Phone,
		arg.Address,
		arg.Obligo,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsOrganic,
		&i.IcountClientID,
		&i.Phone,
		&i.Address,
		&i.Obligo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BalanceDue,
		&i.AgencyMarkupPercentage,
	)
	return i, err
}

const getOrganizationBillingState = `-- name: GetOrganizationBillingState :one
SELECT is_organic, icount_client_id
FROM organizations
WHERE id = $1::BIGINT
`

type GetOrganizationBillingStateRow struct {
	IsOrganic      bool
	IcountClientID *int32
}

func (q *Queries) GetOrganizationBillingState(ctx context.Context, id int64) (GetOrganizationBillingStateRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationBillingState, id)
	var i GetOrganizationBillingStateRow
	err := row.Scan(&i.IsOrganic, &i.IcountClientID)
	return i, err
}

const getOrganizationIcountClientID = `-- name: GetOrganizationIcountClientID :one
SELECT icount_client_id
FROM organizations
WHERE id = $1::BIGINT
`

func (q *Queries) GetOrganizationIcountClientID(ctx context.Context, id int64) (*int32, error) {
	row := q.db.QueryRow(ctx, getOrganizationIcountClientID, id)
	var icount_client_id *int32
	err := row.Scan(&icount_client_id)
	return icount_client_id, err
}

const getOrganizationNamesByIDs = `-- name: GetOrganizationNamesByIDs :many
SELECT id, name
FROM organizations
WHERE id = ANY($1::BIGINT[])
`

type GetOrganizationNamesByIDsRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetOrganizationNamesByIDs(ctx context.Context, ids []int64) ([]GetOrganizationNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getOrganizationNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrganizationNamesByIDsRow
	for rows.Next() {
		var i GetOrganizationNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganicOrganizations = `-- name: ListOrganicOrganizations :many
SELECT
    id,name
FROM organizations
WHERE is_organic = TRUE
ORDER BY name
`

type ListOrganicOrganizationsRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListOrganicOrganizations(ctx context.Context) ([]ListOrganicOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganicOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganicOrganizationsRow
	for rows.Next() {
		var i ListOrganicOrganizationsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT
    o.id,
    o.name,
    o.is_organic,
    o.icount_client_id,
    o.phone,
    o.address,
    o.obligo,
    o.created_at,
    o.updated_at,
    COUNT(DISTINCT of.id)::BIGINT          AS office_count,
    COUNT(DISTINCT c.id)::BIGINT           AS contact_count,
    COUNT(DISTINCT u.id)::BIGINT           AS agent_count
FROM organizations o
LEFT JOIN offices of ON of.organization_id = o.id
LEFT JOIN contacts c ON (c.organization_id = o.id OR c.office_id = of.id)
LEFT JOIN users u ON (u.office_id = of.id AND u.role = 'agent')
WHERE
    ($1::TEXT IS NULL       OR o.name ILIKE '%' || $1::TEXT || '%')
    AND ($2::BOOLEAN IS NULL OR o.is_organic = $2::BOOLEAN)
GROUP BY o.id
ORDER BY o.name
LIMIT  $4::BIGINT
OFFSET $3::BIGINT
`

type ListOrganizationsParams struct {
	Name       *string
	IsOrganic  *bool
	PageOffset int64
	PageSize   int64
}

type ListOrganizationsRow struct {
	ID             int64
	Name           string
	IsOrganic      bool
	IcountClientID *int32
	Phone          *string
	Address        *string
	Obligo         *int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	OfficeCount    int64
	ContactCount   int64
	AgentCount     int64
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizations,
		arg.Name,
		arg.IsOrganic,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsRow
	for rows.Next() {
		var i ListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsOrganic,
			&i.IcountClientID,
			&i.Phone,
			&i.Address,
			&i.Obligo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OfficeCount,
			&i.ContactCount,
			&i.AgentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET
    name             = $1,
    is_organic       = $2,
    icount_client_id = $3,
    phone            = $4,
    address          = $5,
    obligo           = $6,
    updated_at       = CURRENT_TIMESTAMP
WHERE id = $7
RETURNING id, name, is_organic, icount_client_id, phone, address, obligo, created_at, updated_at, balance_due, agency_markup_percentage
`

type UpdateOrganizationParams struct {
	Name           string
	IsOrganic      bool
	IcountClientID *int32
	Phone          *string
	Address        *string
	Obligo         *int32
	ID             int64
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.Name,
		arg.IsOrganic,
		arg.IcountClientID,
		arg.Phone,
		arg.Address,
		arg.Obligo,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsOrganic,
		&i.IcountClientID,
		&i.Phone,
		&i.Address,
		&i.Obligo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BalanceDue,
		&i.AgencyMarkupPercentage,
	)
	return i, err
}

const updateOrganizationBalanceDue = `-- name: UpdateOrganizationBalanceDue :exec
UPDATE organizations
SET balance_due = $1::NUMERIC(10, 2) + COALESCE(balance_due, 0)
WHERE id = $2::BIGINT
`

type UpdateOrganizationBalanceDueParams struct {
	BalanceDue pgtype.Numeric
	ID         int64
}

func (q *Queries) UpdateOrganizationBalanceDue(ctx context.Context, arg UpdateOrganizationBalanceDueParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationBalanceDue, arg.BalanceDue, arg.ID)
	return err
}
