// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: organizations_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*)::BIGINT AS total
FROM organizations o
WHERE
    ($1::VARCHAR IS NULL       OR o.name ILIKE '%' || $1::VARCHAR || '%')
    AND ($2::BOOLEAN IS NULL OR o.is_organic = $2::BOOLEAN)
`

type CountOrganizationsParams struct {
	Name      pgtype.Text
	IsOrganic pgtype.Bool
}

func (q *Queries) CountOrganizations(ctx context.Context, arg CountOrganizationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations, arg.Name, arg.IsOrganic)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, is_organic, phone, address, obligo, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
RETURNING id, name, is_organic, phone, address, obligo, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name      string
	IsOrganic bool
	Phone     pgtype.Text
	Address   pgtype.Text
	Obligo    pgtype.Numeric
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.IsOrganic,
		arg.Phone,
		arg.Address,
		arg.Obligo,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsOrganic,
		&i.Phone,
		&i.Address,
		&i.Obligo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT
    o.id,
    o.name,
    o.is_organic,
    o.phone,
    o.address,
    o.obligo,
    o.created_at,
    o.updated_at,
    COUNT(DISTINCT of.id)::BIGINT          AS office_count,
    COUNT(DISTINCT c.id)::BIGINT           AS contact_count,
    COUNT(DISTINCT u.id)::BIGINT           AS agent_count
FROM organizations o
LEFT JOIN offices of ON of.organization_id = o.id
LEFT JOIN contacts c ON (c.organization_id = o.id OR c.office_id = of.id)
LEFT JOIN users u ON (u.office_id = of.id AND u.role = 'agent')
WHERE
    ($1::VARCHAR IS NULL       OR o.name ILIKE '%' || $1::VARCHAR || '%')
    AND ($2::BOOLEAN IS NULL OR o.is_organic = $2::BOOLEAN)
GROUP BY o.id
ORDER BY o.name
LIMIT  $4::BIGINT
OFFSET $3::BIGINT
`

type ListOrganizationsParams struct {
	Name       pgtype.Text
	IsOrganic  pgtype.Bool
	PageOffset int64
	PageSize   int64
}

type ListOrganizationsRow struct {
	ID           int32
	Name         string
	IsOrganic    bool
	Phone        pgtype.Text
	Address      pgtype.Text
	Obligo       pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	OfficeCount  int64
	ContactCount int64
	AgentCount   int64
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizations,
		arg.Name,
		arg.IsOrganic,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsRow
	for rows.Next() {
		var i ListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsOrganic,
			&i.Phone,
			&i.Address,
			&i.Obligo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OfficeCount,
			&i.ContactCount,
			&i.AgentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET
    name       = COALESCE($1,       name),
    is_organic = COALESCE($2, is_organic),
    phone      = COALESCE($3,      phone),
    address    = COALESCE($4,    address),
    obligo     = COALESCE($5,     obligo),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $6
RETURNING id, name, is_organic, phone, address, obligo, created_at, updated_at
`

type UpdateOrganizationParams struct {
	Name      pgtype.Text
	IsOrganic pgtype.Bool
	Phone     pgtype.Text
	Address   pgtype.Text
	Obligo    pgtype.Numeric
	ID        int32
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.Name,
		arg.IsOrganic,
		arg.Phone,
		arg.Address,
		arg.Obligo,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsOrganic,
		&i.Phone,
		&i.Address,
		&i.Obligo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
