// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CheckUserExists(ctx context.Context, email string) (int64, error)
	CountAgents(ctx context.Context, arg CountAgentsParams) (int64, error)
	CountContacts(ctx context.Context, arg CountContactsParams) (int64, error)
	CountOffices(ctx context.Context, arg CountOfficesParams) (int64, error)
	CountOrganizations(ctx context.Context, arg CountOrganizationsParams) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (CreateAgentRow, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error)
	CreateOffice(ctx context.Context, arg CreateOfficeParams) (CreateOfficeRow, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (CreateStaffUserRow, error)
	DeleteContact(ctx context.Context, id int64) error
	DeletePasswordResetTokenByID(ctx context.Context, id int64) error
	DeleteRefreshToken(ctx context.Context, jti string) error
	DeleteRefreshTokensByUserId(ctx context.Context, userID int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAgentsBillingContacts(ctx context.Context, usersIds []int64) ([]GetAgentsBillingContactsRow, error)
	GetOfficeBillingState(ctx context.Context, id int64) (GetOfficeBillingStateRow, error)
	GetOfficeIcountClientID(ctx context.Context, id int64) (*int32, error)
	GetOfficeNamesByIDs(ctx context.Context, ids []int64) ([]GetOfficeNamesByIDsRow, error)
	GetOrganizationBillingState(ctx context.Context, id int64) (GetOrganizationBillingStateRow, error)
	GetOrganizationIcountClientID(ctx context.Context, id int64) (*int32, error)
	GetOrganizationNamesByIDs(ctx context.Context, ids []int64) ([]GetOrganizationNamesByIDsRow, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetRefreshToken(ctx context.Context, jti string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error)
	GetUserByPhone(ctx context.Context, phoneNumber *string) (User, error)
	GetUserCredit(ctx context.Context, id int64) (GetUserCreditRow, error)
	GetUserNamesByIDs(ctx context.Context, ids []int64) ([]GetUserNamesByIDsRow, error)
	InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) (PasswordResetToken, error)
	ListAdminsEmails(ctx context.Context) ([]string, error)
	ListAgents(ctx context.Context, arg ListAgentsParams) ([]ListAgentsRow, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]ListContactsRow, error)
	ListInorganicOffices(ctx context.Context) ([]ListInorganicOfficesRow, error)
	ListOffices(ctx context.Context, arg ListOfficesParams) ([]ListOfficesRow, error)
	ListOrganicOrganizations(ctx context.Context) ([]ListOrganicOrganizationsRow, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error)
	ListStaffByRole(ctx context.Context, role UserRole) ([]ListStaffByRoleRow, error)
	SaveOTP(ctx context.Context, arg SaveOTPParams) error
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	UpdateOffice(ctx context.Context, arg UpdateOfficeParams) (UpdateOfficeRow, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
