// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refresh_tokens_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE jti = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, jti string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, jti)
	return err
}

const deleteRefreshTokensByUserId = `-- name: DeleteRefreshTokensByUserId :exec
DELETE FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserId(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUserId, userID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT jti, user_id, expires_at FROM refresh_tokens WHERE jti = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, jti string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, jti)
	var i RefreshToken
	err := row.Scan(&i.Jti, &i.UserID, &i.ExpiresAt)
	return i, err
}

const saveRefreshToken = `-- name: SaveRefreshToken :exec
INSERT INTO refresh_tokens (jti, user_id, expires_at)
VALUES ($1, $2, $3)
`

type SaveRefreshTokenParams struct {
	Jti       string
	UserID    int32
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, saveRefreshToken, arg.Jti, arg.UserID, arg.ExpiresAt)
	return err
}
