// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT id FROM users
WHERE username = $1
`

func (q *Queries) CheckUserExists(ctx context.Context, username string) (int32, error) {
	row := q.db.QueryRow(ctx, checkUserExists, username)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserById = `-- name: GetUserById :one
SELECT id, role, username, phone_number, otp, office_code, agent_code, password_hash, last_login, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.PhoneNumber,
		&i.Otp,
		&i.OfficeCode,
		&i.AgentCode,
		&i.PasswordHash,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, role, username, phone_number, otp, office_code, agent_code, password_hash, last_login, created_at, updated_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.PhoneNumber,
		&i.Otp,
		&i.OfficeCode,
		&i.AgentCode,
		&i.PasswordHash,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerAdmin = `-- name: RegisterAdmin :one
INSERT INTO users (role, username, password_hash, office_code, agent_code, created_at, updated_at)
VALUES ('admin', $1, $2, $3, $4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, role, username, office_code, agent_code, last_login, created_at, updated_at
`

type RegisterAdminParams struct {
	Username     string
	PasswordHash string
	OfficeCode   pgtype.Text
	AgentCode    pgtype.Text
}

type RegisterAdminRow struct {
	ID         int32
	Role       UserRole
	Username   string
	OfficeCode pgtype.Text
	AgentCode  pgtype.Text
	LastLogin  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) RegisterAdmin(ctx context.Context, arg RegisterAdminParams) (RegisterAdminRow, error) {
	row := q.db.QueryRow(ctx, registerAdmin,
		arg.Username,
		arg.PasswordHash,
		arg.OfficeCode,
		arg.AgentCode,
	)
	var i RegisterAdminRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.OfficeCode,
		&i.AgentCode,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerAgent = `-- name: RegisterAgent :one
INSERT INTO users (role, username, password_hash, office_code, agent_code, created_at, updated_at)
VALUES ('agent', $1, $2, $3, $4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, role, username, office_code, agent_code, last_login, created_at, updated_at
`

type RegisterAgentParams struct {
	Username     string
	PasswordHash string
	OfficeCode   pgtype.Text
	AgentCode    pgtype.Text
}

type RegisterAgentRow struct {
	ID         int32
	Role       UserRole
	Username   string
	OfficeCode pgtype.Text
	AgentCode  pgtype.Text
	LastLogin  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) RegisterAgent(ctx context.Context, arg RegisterAgentParams) (RegisterAgentRow, error) {
	row := q.db.QueryRow(ctx, registerAgent,
		arg.Username,
		arg.PasswordHash,
		arg.OfficeCode,
		arg.AgentCode,
	)
	var i RegisterAgentRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.OfficeCode,
		&i.AgentCode,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  agent_code   = COALESCE($1,   agent_code),
  office_code  = COALESCE($2,  office_code),
  phone_number = COALESCE($3, phone_number),
  updated_at   = CURRENT_TIMESTAMP
WHERE id = $4
RETURNING id, role, username, office_code, agent_code, phone_number, last_login, created_at, updated_at
`

type UpdateUserParams struct {
	AgentCode   pgtype.Text
	OfficeCode  pgtype.Text
	PhoneNumber pgtype.Text
	ID          int32
}

type UpdateUserRow struct {
	ID          int32
	Role        UserRole
	Username    string
	OfficeCode  pgtype.Text
	AgentCode   pgtype.Text
	PhoneNumber pgtype.Text
	LastLogin   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.AgentCode,
		arg.OfficeCode,
		arg.PhoneNumber,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.OfficeCode,
		&i.AgentCode,
		&i.PhoneNumber,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           int32
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
