// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT id FROM users
WHERE email = $1
`

func (q *Queries) CheckUserExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, checkUserExists, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const countAgents = `-- name: CountAgents :one
SELECT COUNT(*)
FROM users
WHERE role = 'agent'
  AND ($1::text IS NULL OR email ILIKE '%' || $1::text || '%' OR phone_number ILIKE '%' || $1::text || '%')
  AND ($2::bigint IS NULL OR office_id = $2::bigint)
  AND ($3::bigint IS NULL OR office_id IN (
    SELECT id FROM offices WHERE organization_id = $3::bigint
  ))
`

type CountAgentsParams struct {
	Search         *string
	OfficeID       *int64
	OrganizationID *int64
}

func (q *Queries) CountAgents(ctx context.Context, arg CountAgentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAgents, arg.Search, arg.OfficeID, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO users (role, first_name, last_name, email, phone_number, password_hash, office_id, created_at, updated_at)
VALUES ('agent', $1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, role, first_name, last_name, email, phone_number, office_id, last_login, created_at, updated_at
`

type CreateAgentParams struct {
	FirstName    string
	LastName     string
	Email        string
	PhoneNumber  *string
	PasswordHash string
	OfficeID     *int64
}

type CreateAgentRow struct {
	ID          int64
	Role        UserRole
	FirstName   string
	LastName    string
	Email       string
	PhoneNumber *string
	OfficeID    *int64
	LastLogin   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (CreateAgentRow, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.OfficeID,
	)
	var i CreateAgentRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.OfficeID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO users (role, first_name, last_name, email, phone_number, otp, password_hash, created_at, updated_at)
VALUES (
  'customer',
  $1,
  $2,
  $3,
  $4,
  $5::text,
  $6,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
RETURNING id, role, first_name, last_name, email, phone_number, otp, office_id, last_login, created_at, updated_at
`

type CreateCustomerParams struct {
	FirstName    string
	LastName     string
	Email        string
	PhoneNumber  *string
	Otp          *string
	PasswordHash string
}

type CreateCustomerRow struct {
	ID          int64
	Role        UserRole
	FirstName   string
	LastName    string
	Email       string
	PhoneNumber *string
	Otp         *string
	OfficeID    *int64
	LastLogin   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.Otp,
		arg.PasswordHash,
	)
	var i CreateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Otp,
		&i.OfficeID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStaffUser = `-- name: CreateStaffUser :one
INSERT INTO users (role, first_name, last_name, email, password_hash, created_at, updated_at)
VALUES ($1::user_role, $2, $3, $4, $5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, role, first_name, last_name, email, office_id, last_login, created_at, updated_at
`

type CreateStaffUserParams struct {
	Role         UserRole
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
}

type CreateStaffUserRow struct {
	ID        int64
	Role      UserRole
	FirstName string
	LastName  string
	Email     string
	OfficeID  *int64
	LastLogin pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (CreateStaffUserRow, error) {
	row := q.db.QueryRow(ctx, createStaffUser,
		arg.Role,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateStaffUserRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.OfficeID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAgentsBillingContacts = `-- name: GetAgentsBillingContacts :many
SELECT
u.id as agent_id, u.first_name as agent_first_name, u.last_name as agent_last_name,
c.id as contact_id, c.email, c.first_name as contact_first_name, c.last_name as contact_last_name,
org.id as organization_id, org.name as organization_name, org.is_organic,
office.id as office_id, office.name as office_name
FROM users as u
INNER JOIN offices as office ON office.id = u.office_id
INNER JOIN organizations as org ON org.id = office.organization_id
INNER JOIN contacts as c ON c.is_payment_responsible = TRUE AND (
    (c.organization_id = org.id AND org.is_organic = TRUE) OR 
    (c.office_id = office.id AND org.is_organic = FALSE)
)
WHERE u.role = 'agent'
  AND u.id = ANY($1::bigint[])
`

type GetAgentsBillingContactsRow struct {
	AgentID          int64
	AgentFirstName   string
	AgentLastName    string
	ContactID        int64
	Email            string
	ContactFirstName string
	ContactLastName  string
	OrganizationID   int64
	OrganizationName string
	IsOrganic        bool
	OfficeID         int64
	OfficeName       string
}

func (q *Queries) GetAgentsBillingContacts(ctx context.Context, usersIds []int64) ([]GetAgentsBillingContactsRow, error) {
	rows, err := q.db.Query(ctx, getAgentsBillingContacts, usersIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAgentsBillingContactsRow
	for rows.Next() {
		var i GetAgentsBillingContactsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.AgentFirstName,
			&i.AgentLastName,
			&i.ContactID,
			&i.Email,
			&i.ContactFirstName,
			&i.ContactLastName,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.IsOrganic,
			&i.OfficeID,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT users.id, users.first_name, users.last_name, users.role, users.email, users.phone_number, users.otp, users.office_id, users.password_hash, users.last_login, users.created_at, users.updated_at, organization.id AS organization_id, organization.is_organic
FROM users
LEFT JOIN offices ON offices.id = users.office_id
LEFT JOIN organizations AS organization ON organization.id = offices.organization_id
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             int64
	FirstName      string
	LastName       string
	Role           UserRole
	Email          string
	PhoneNumber    *string
	Otp            *string
	OfficeID       *int64
	PasswordHash   string
	LastLogin      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	OrganizationID *int64
	IsOrganic      *bool
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Email,
		&i.PhoneNumber,
		&i.Otp,
		&i.OfficeID,
		&i.PasswordHash,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.IsOrganic,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT users.id, users.first_name, users.last_name, users.role, users.email, users.phone_number, users.otp, users.office_id, users.password_hash, users.last_login, users.created_at, users.updated_at, organization.id AS organization_id, organization.is_organic
FROM users
LEFT JOIN offices ON offices.id = users.office_id
LEFT JOIN organizations AS organization ON organization.id = offices.organization_id
WHERE users.id = $1
`

type GetUserByIdRow struct {
	ID             int64
	FirstName      string
	LastName       string
	Role           UserRole
	Email          string
	PhoneNumber    *string
	Otp            *string
	OfficeID       *int64
	PasswordHash   string
	LastLogin      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	OrganizationID *int64
	IsOrganic      *bool
}

func (q *Queries) GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Email,
		&i.PhoneNumber,
		&i.Otp,
		&i.OfficeID,
		&i.PasswordHash,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.IsOrganic,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, first_name, last_name, role, email, phone_number, otp, office_id, password_hash, last_login, created_at, updated_at
FROM users
WHERE phone_number = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Email,
		&i.PhoneNumber,
		&i.Otp,
		&i.OfficeID,
		&i.PasswordHash,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCredit = `-- name: GetUserCredit :one
SELECT (
  CASE WHEN org.is_organic = TRUE
    THEN COALESCE(org.obligo, 0)
    ELSE COALESCE(offices.obligo, 0)
  END
)::INTEGER AS obligo,
(
  CASE WHEN org.is_organic = TRUE
    THEN org.balance_due
    ELSE offices.balance_due
  END
)::NUMERIC(10, 2) AS balance_due
FROM users AS u
INNER JOIN offices ON u.office_id = offices.id
INNER JOIN organizations AS org ON org.id = offices.organization_id
WHERE u.id = $1
`

type GetUserCreditRow struct {
	Obligo     int32
	BalanceDue pgtype.Numeric
}

func (q *Queries) GetUserCredit(ctx context.Context, id int64) (GetUserCreditRow, error) {
	row := q.db.QueryRow(ctx, getUserCredit, id)
	var i GetUserCreditRow
	err := row.Scan(&i.Obligo, &i.BalanceDue)
	return i, err
}

const getUserNamesByIDs = `-- name: GetUserNamesByIDs :many
SELECT id, first_name, last_name
FROM users
WHERE id = ANY($1::BIGINT[])
`

type GetUserNamesByIDsRow struct {
	ID        int64
	FirstName string
	LastName  string
}

func (q *Queries) GetUserNamesByIDs(ctx context.Context, ids []int64) ([]GetUserNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUserNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserNamesByIDsRow
	for rows.Next() {
		var i GetUserNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminsEmails = `-- name: ListAdminsEmails :many
SELECT email
FROM users
WHERE role = 'admin'
`

func (q *Queries) ListAdminsEmails(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAdminsEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT u.id, u.role, u.first_name, u.last_name, u.email, u.phone_number, u.office_id, u.last_login, u.created_at, u.updated_at,
       o.name AS office_name,
       org.name AS organization_name
FROM users u
LEFT JOIN offices       o   ON o.id   = u.office_id
LEFT JOIN organizations org ON org.id = o.organization_id
WHERE u.role = 'agent'
  AND ($1::text IS NULL 
    OR u.email ILIKE '%' || $1::text || '%' 
    OR u.phone_number ILIKE '%' || $1::text || '%'
    OR u.first_name ILIKE '%' || $1::text || '%'
    OR u.last_name ILIKE '%' || $1::text || '%'
    )
  AND ($2::bigint IS NULL OR u.office_id = $2::bigint)
  AND ($3::bigint IS NULL OR o.organization_id = $3::bigint)
ORDER BY u.created_at DESC
LIMIT $5
OFFSET $4
`

type ListAgentsParams struct {
	Search         *string
	OfficeID       *int64
	OrganizationID *int64
	PageOffset     int32
	PageSize       int32
}

type ListAgentsRow struct {
	ID               int64
	Role             UserRole
	FirstName        string
	LastName         string
	Email            string
	PhoneNumber      *string
	OfficeID         *int64
	LastLogin        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	OfficeName       *string
	OrganizationName *string
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents,
		arg.Search,
		arg.OfficeID,
		arg.OrganizationID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsRow
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNumber,
			&i.OfficeID,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OfficeName,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffByRole = `-- name: ListStaffByRole :many
SELECT id, role, first_name, last_name, email, office_id, last_login, created_at, updated_at
FROM users
WHERE role = $1::user_role
`

type ListStaffByRoleRow struct {
	ID        int64
	Role      UserRole
	FirstName string
	LastName  string
	Email     string
	OfficeID  *int64
	LastLogin pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListStaffByRole(ctx context.Context, role UserRole) ([]ListStaffByRoleRow, error) {
	rows, err := q.db.Query(ctx, listStaffByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffByRoleRow
	for rows.Next() {
		var i ListStaffByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.OfficeID,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOTP = `-- name: SaveOTP :exec
UPDATE users
SET
  otp = $2
WHERE
  id = $1
`

type SaveOTPParams struct {
	ID  int64
	Otp *string
}

func (q *Queries) SaveOTP(ctx context.Context, arg SaveOTPParams) error {
	_, err := q.db.Exec(ctx, saveOTP, arg.ID, arg.Otp)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  first_name = COALESCE($1::text, first_name),
  last_name = COALESCE($2::text, last_name),
  email = COALESCE($3::text, email),
  phone_number = COALESCE($4::text, phone_number),
  office_id = COALESCE($5::bigint, office_id),
  password_hash = COALESCE($6::text, password_hash),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $7
RETURNING id, role, first_name, last_name, email, phone_number, office_id, last_login, created_at, updated_at
`

type UpdateUserParams struct {
	FirstName    *string
	LastName     *string
	Email        *string
	PhoneNumber  *string
	OfficeID     *int64
	PasswordHash *string
	ID           int64
}

type UpdateUserRow struct {
	ID          int64
	Role        UserRole
	FirstName   string
	LastName    string
	Email       string
	PhoneNumber *string
	OfficeID    *int64
	LastLogin   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.OfficeID,
		arg.PasswordHash,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.OfficeID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
