package broker

var flexSupplierMap = map[string]struct {
	name string
	code string
}{
	"CT": {name: "ACA Rent", code: "CT"},
	"C5": {name: "ACA Rent", code: "CT"},
	"AW": {name: "Ace", code: "AW"},
	"DA": {name: "Ada", code: "DA"},
	"AR": {name: "Add Car", code: "AR"},
	"AY": {name: "Add Car", code: "AR"},
	"AB": {name: "Adobe", code: "AB"},
	"A2": {name: "Adobe", code: "AB"},
	"A3": {name: "Adobe", code: "AB"},
	"AI": {name: "Air Auto", code: "AI"},
	"A1": {name: "Air Auto", code: "AI"},
	"AL": {name: "Alamo", code: "AL"},
	"A4": {name: "Alamo", code: "AL"},
	"A6": {name: "Alamo Max", code: "A6"},
	"CK": {name: "Arnold Clark", code: "CK"},
	"AA": {name: "AutAtlantis ", code: "AA"},
	"AX": {name: "AutAtlantis ", code: "AA"},
	"AU": {name: "Auto Menorca", code: "AU"},
	"A7": {name: "Auto Menorca", code: "AU"},
	"A8": {name: "Auto Menorca", code: "AU"},
	"AV": {name: "Auto Via", code: "AV"},
	"IO": {name: "Autos Union", code: "IO"},
	"I6": {name: "Autos Union", code: "IO"},
	"VI": {name: "AVIS", code: "VI"},
	"V7": {name: "AVIS", code: "VI"},
	"AC": {name: "Avis Canaries", code: "AC"},
	"A5": {name: "Avis Canaries", code: "AC"},
	"BC": {name: "Bravacar Rent A Car", code: "BC"},
	"B1": {name: "B-Rent", code: "B1"},
	"B2": {name: "B-Rent", code: "B1"},
	"BU": {name: "Buchbinde", code: "BU"},
	"BG": {name: "Budget", code: "BG"},
	"BS": {name: "Budget Canaries", code: "BS"},
	"B3": {name: "Budget Canaries", code: "BS"},
	"BI": {name: "Budget Ireland", code: "BI"},
	"BR": {name: "Budget Romania", code: "BR"},
	"CN": {name: "Canarias.com", code: "CN"},
	"C1": {name: "Canarias.com", code: "CN"},
	"CA": {name: "Car Rental Company", code: "CA"},
	"C3": {name: "Car Rental Company", code: "CA"},
	"CE": {name: "Centauro", code: "CE"},
	"CS": {name: "Centauro", code: "CE"},
	"CP": {name: "Centauro", code: "CE"},
	"CC": {name: "Cicar", code: "CC"},
	"CB": {name: "Cooltra ", code: "CB"},
	"CR": {name: "Cuba on the Road", code: "CR"},
	"DI": {name: "Discount", code: "DI"},
	"DS": {name: "Dollar", code: "DS"},
	"D7": {name: "Dollar", code: "DS"},
	"D1": {name: "Dollar Portugal", code: "D1"},
	"D2": {name: "Dollar Portugal", code: "D1"},
	"D4": {name: "Dollar Portugal", code: "D1"},
	"ZR": {name: "Dollar Spain", code: "ZR"},
	"Z1": {name: "Dollar Spain", code: "ZR"},
	"Z3": {name: "Dollar Spain", code: "ZR"},
	"VF": {name: "Drivalia France", code: "VF"},
	"V4": {name: "Drivalia France", code: "VF"},
	"WR": {name: "Drivalia Italy", code: "WR"},
	"W1": {name: "Drivalia Italy", code: "WR"},
	"W2": {name: "Drivalia Italy", code: "WR"},
	"VP": {name: "Drivalia Portugal", code: "VP"},
	"V5": {name: "Drivalia Portugal", code: "VP"},
	"VS": {name: "Drivalia Spain", code: "VS"},
	"V2": {name: "Drivalia Spain", code: "VS"},
	"ET": {name: "Drivalia UK & IR", code: "ET"},
	"EP": {name: "Drivalia UK & IR", code: "ET"},
	"DM": {name: "Drive A Matic", code: "DM"},
	"DH": {name: "Drive on Holidays", code: "DH"},
	"D6": {name: "Drive on Holidays", code: "DH"},
	"EC": {name: "Eastcoast", code: "EC"},
	"E8": {name: "Eastcoast", code: "EC"},
	"E7": {name: "Eastcoast", code: "EC"},
	"EM": {name: "EasyCarHire", code: "EM"},
	"EE": {name: "EasyCarHire", code: "EM"},
	"EF": {name: "EasyCarHire", code: "EM"},
	"EV": {name: "Eco Via", code: "EV"},
	"ED": {name: "Eco Via", code: "EV"},
	"EJ": {name: "eecar Balearics", code: "EJ"},
	"EH": {name: "eecar Balearics", code: "EJ"},
	"EN": {name: "Enterprise", code: "EN"},
	"E9": {name: "Enterprise", code: "EN"},
	"ER": {name: "EuropCar", code: "ER"},
	"E5": {name: "EuropCar", code: "ER"},
	"E6": {name: "EuropCar", code: "ER"},
	"JR": {name: "Europcar Chanel Islands", code: "JR"},
	"EU": {name: "Europcar Cyprus", code: "EU"},
	"GE": {name: "Europcar Greece", code: "GE"},
	"ES": {name: "Europcar South Africa", code: "ES"},
	"E3": {name: "Europcar South Africa", code: "ES"},
	"E2": {name: "Europcar South Africa", code: "ES"},
	"EZ": {name: "Ezi-rent", code: "EZ"},
	"E4": {name: "Ezi-rent", code: "EZ"},
	"E1": {name: "Ezi-rent", code: "EZ"},
	"FR": {name: "Felirent Italy", code: "FR"},
	"F5": {name: "Felirent Italy", code: "FR"},
	"AD": {name: "FireFly", code: "AD"},
	"FC": {name: "First Car Hire", code: "FC"},
	"F2": {name: "First Car Hire", code: "FC"},
	"F1": {name: "First Car Hire", code: "FC"},
	"FH": {name: "First car Hire Malta", code: "FH"},
	"F4": {name: "First car Hire Malta", code: "FH"},
	"FZ": {name: "Flizzr", code: "FZ"},
	"F3": {name: "Flizzr", code: "FZ"},
	"GC": {name: "GoldCar", code: "GC"},
	"G1": {name: "GoldCar", code: "GC"},
	"G2": {name: "GoldCar", code: "GC"},
	"GM": {name: "Green motion Car Hire", code: "GM"},
	"G4": {name: "Green motion Car Hire", code: "GM"},
	"G5": {name: "Green motion Car Hire", code: "GM"},
	"GU": {name: "Guerin", code: "GU"},
	"G3": {name: "Guerin", code: "GU"},
	"GP": {name: "Guerin", code: "GU"},
	"HH": {name: "Helle Hollis", code: "HH"},
	"H9": {name: "Helle Hollis", code: "HH"},
	"HT": {name: "Hertz", code: "HT"},
	"H5": {name: "Hertz", code: "HT"},
	"H6": {name: "Hertz", code: "HT"},
	"HG": {name: "Hertz AutoHellas", code: "HG"},
	"HZ": {name: "Hertz Balearics", code: "HZ"},
	"H1": {name: "Hertz Balearics", code: "HZ"},
	"Z2": {name: "Hertz Balearics", code: "HZ"},
	"HC": {name: "Hertz Canaries", code: "HC"},
	"H3": {name: "Hertz Canaries", code: "HC"},
	"C2": {name: "Hertz Canaries", code: "HC"},
	"HV": {name: "Hertz Cape Verde", code: "HV"},
	"HN": {name: "Hertz Panama", code: "HN"},
	"HP": {name: "Hertz Portugal", code: "HP"},
	"H7": {name: "Hertz Portugal", code: "HP"},
	"H8": {name: "Hertz Portugal", code: "HP"},
	"HE": {name: "Hiper", code: "HE"},
	"H4": {name: "Hiper", code: "HE"},
	"H2": {name: "Hiper", code: "HE"},
	"IV": {name: "Ilha Verde Rent A Car", code: "IV"},
	"I4": {name: "Ilha Verde Rent A Car", code: "IV"},
	"IS": {name: "Island Car Rentals", code: "IS"},
	"IC": {name: "Italy Car Rent", code: "IC"},
	"I3": {name: "Italy Car Rent", code: "IC"},
	"KD": {name: "Keddy", code: "KD"},
	"K1": {name: "Keddy", code: "KD"},
	"K2": {name: "Keddy", code: "KD"},
	"LA": {name: "LocAuto", code: "LA"},
	"L1": {name: "LocAuto", code: "LA"},
	"L2": {name: "LocAuto", code: "LA"},
	"MR": {name: "Madeira Rent", code: "MR"},
	"M1": {name: "Madeira Rent", code: "MR"},
	"GI": {name: "Maggiore Italy", code: "GI"},
	"G6": {name: "Maggiore Italy", code: "GI"},
	"MK": {name: "Master Kings", code: "MK"},
	"MG": {name: "Megadrive", code: "MG"},
	"ZM": {name: "Micauto", code: "ZM"},
	"Z5": {name: "Micauto", code: "ZM"},
	"MV": {name: "Movida", code: "MV"},
	"ZL": {name: "National", code: "ZL"},
	"Z4": {name: "National", code: "ZL"},
	"NT": {name: "Nokta", code: "NT"},
	"NG": {name: "Noleggiare", code: "NG"},
	"N1": {name: "Noleggiare", code: "NG"},
	"N2": {name: "Noleggiare", code: "NG"},
	"OK": {name: "OK Rent a Car", code: "OK"},
	"O1": {name: "OK Rent a Car", code: "OK"},
	"O2": {name: "OK Rent a Car", code: "OK"},
	"OR": {name: "Orlando Rent A Car", code: "OR"},
	"OS": {name: "Orlando Rent A Car", code: "OR"},
	"OP": {name: "Orlando Rent A Car", code: "OR"},
	"OW": {name: "Owners Car Rental", code: "OW"},
	"O4": {name: "Owners Car Rental", code: "OW"},
	"O5": {name: "Owners Car Rental", code: "OW"},
	"RE": {name: "Record", code: "RE"},
	"R4": {name: "Record", code: "RE"},
	"R5": {name: "Record", code: "RE"},
	"RC": {name: "Right Car Vehicle Rental", code: "RC"},
	"R3": {name: "Right Car Vehicle Rental", code: "RC"},
	"RZ": {name: "Routes", code: "RZ"},
	"R6": {name: "Routes", code: "RZ"},
	"SC": {name: "Sicily By Car", code: "SC"},
	"S1": {name: "Sicily By Car", code: "SC"},
	"SZ": {name: "Sicily By Car", code: "SC"},
	"SX": {name: "SIXT", code: "SX"},
	"S2": {name: "SIXT", code: "SX"},
	"X1": {name: "SIXT", code: "SX"},
	"ST": {name: "Stoutes Car Rental", code: "ST"},
	"SP": {name: "SurPrice", code: "SP"},
	"S3": {name: "SurPrice", code: "SP"},
	"TE": {name: "Tempest Car Hire", code: "TE"},
	"T1": {name: "Tempest Car Hire", code: "TE"},
	"T2": {name: "Tempest Car Hire", code: "TE"},
	"TY": {name: "Thrifty", code: "TY"},
	"T9": {name: "Thrifty", code: "TY"},
	"TI": {name: "Thrifty Iceland", code: "TI"},
	"TX": {name: "Top Car Canaries", code: "TX"},
	"T8": {name: "Top Car Canaries", code: "TX"},
	"TO": {name: "Tourent", code: "TO"},
	"T6": {name: "Tourent", code: "TO"},
	"T7": {name: "Tourent", code: "TO"},
	"VR": {name: "Viaggiare Rent", code: "VR"},
	"V3": {name: "Viaggiare Rent", code: "VR"},
	"VG": {name: "Volta Greece", code: "VG"},
	"V1": {name: "Volta Greece", code: "VG"},
	"V6": {name: "Volta Greece", code: "VG"},
	"WI": {name: "WIber", code: "WI"},
	"W3": {name: "WIber", code: "WI"},
	"W4": {name: "WIber", code: "WI"},
	"WG": {name: "Wheego Premium", code: "WG"},
	"W5": {name: "Wheego", code: "WG"},
}
