// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CheckUserExists(ctx context.Context, username string) (int32, error)
	DeleteRefreshToken(ctx context.Context, jti string) error
	DeleteRefreshTokensByUserId(ctx context.Context, userID int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetRefreshToken(ctx context.Context, jti string) (RefreshToken, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	RegisterAdmin(ctx context.Context, arg RegisterAdminParams) (RegisterAdminRow, error)
	RegisterAgent(ctx context.Context, arg RegisterAgentParams) (RegisterAgentRow, error)
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
