// Code generated by the Encore v1.54.0 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-global-rental-2m42.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the global-rental-2m42 Encore application.
 */
export default class Client {
    public readonly accounts: accounts.ServiceClient
    public readonly booking: booking.ServiceClient
    public readonly reservation: reservation.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * @deprecated This constructor is deprecated, and you should move to using BaseURL with an Options object
     */
    constructor(target: string, token?: string)

    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions)
    constructor(target: string | BaseURL = "prod", options?: string | ClientOptions) {

        // Convert the old constructor parameters to a BaseURL object and a ClientOptions object
        if (!target.startsWith("http://") && !target.startsWith("https://")) {
            target = Environment(target)
        }

        if (typeof options === "string") {
            options = { auth: options }
        }

        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.accounts = new accounts.ServiceClient(base)
        this.booking = new booking.ServiceClient(base)
        this.reservation = new reservation.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the auth token to be used for each request
     * either by passing in a static token string or by passing in a function
     * which returns the auth token.
     *
     * These tokens will be sent as bearer tokens in the Authorization header.
     */
    auth?: string | AuthDataGenerator
}

export namespace accounts {
    export interface AdminResponse {
        id: number
        email: string
        lastLogin: string
        createdAt: string
        updatedAt: string
    }

    export interface AgentResponse {
        id: number
        email: string
        phoneNumber: string
        officeId: number
        officeName: string
        organizationName: string
        lastLogin: string
        createdAt: string
        updatedAt: string
    }

    export interface ContactResponse {
        id: number
        firstName: string
        lastName: string
        role: string
        cellphone: string
        email: string
        officeId: number
        organizationId: number
        officeName: string
        organizationName: string
    }

    export interface CreateAdminRequest {
        email: string
        password: string
    }

    export interface CreateAdminResponse {
        id: number
    }

    export interface CreateAgentRequest {
        email: string
        password: string
        phoneNumber: string
        officeId: number
    }

    export interface CreateAgentResponse {
        id: number
    }

    export interface CreateContactRequest {
        firstName: string
        lastName: string
        role: string
        cellphone: string
        email: string
        officeId?: number
        organizationId?: number
    }

    export interface CreateOfficeRequest {
        name: string
        organizationId: number
        phone?: string
        address?: string
    }

    export interface CreateOrganizationRequest {
        name: string
        isOrganic: boolean
        phone?: string
        address?: string
        obligo?: number
    }

    export interface ListAdminsResponse {
        admins: AdminResponse[]
    }

    export interface ListAgentsRequest {
        Search: string
        OfficeID: number
        OrgID: number
        Page: number
    }

    export interface ListAgentsResponse {
        agents: AgentResponse[]
        total: number
    }

    export interface ListContactsRequest {
        Search: string
        OfficeID: number
        OrgID: number
        Page: number
    }

    export interface ListContactsResponse {
        contacts: ContactResponse[]
        total: number
    }

    export interface ListOfficesRequest {
        Search: string
        OrgID: number
        Page: number
    }

    export interface ListOfficesResponse {
        offices: OfficeResponse[]
        total: number
    }

    export interface ListOrganizationsRequest {
        Search?: string
        IsOrganic?: string
        Page: number
    }

    export interface ListOrganizationsResponse {
        organizations: ListOrganizationsRow[]
        total: number
    }

    export interface ListOrganizationsRow {
        id: number
        name: string
        isOrganic: boolean
        phone: string
        address: string
        obligo: number
        officeCount: number
        contactCount: number
        agentCount: number
    }

    export interface LoginAsAgentParams {
        agentId: number
    }

    /**
     * LoginParams defines the parameters required for user login.
     */
    export interface LoginParams {
        email: string
        password: string
    }

    /**
     * LoginResponse defines the response structure for user login.
     */
    export interface LoginResponse {
        id: number
        email: string
        role: db.UserRole
        accessToken: string
        refreshToken: string
        phoneNumber: string
        officeId: number
    }

    export interface OfficeResponse {
        id: number
        name: string
        organizationId: number
        organizationName: string
        phone: string
        address: string
        contactCount: number
        agentCount: number
    }

    export interface OrganizationResponse {
        id: number
        name: string
        isOrganic: boolean
        phone: string
        address: string
        obligo: number
    }

    /**
     * RefreshTokensParams defines the parameters required for refreshing tokens.
     */
    export interface RefreshTokensParams {
        RefreshToken: string
    }

    export interface TempAgentTagUsageResponse {
    }

    export interface UpdateContactRequest {
        firstName?: string
        lastName?: string
        role?: string
        cellphone?: string
        email?: string
        officeId?: number
        organizationId?: number
    }

    export interface UpdateOfficeRequest {
        name?: string
        organizationId?: number
        phone?: string
        address?: string
    }

    export interface UpdateOrganizationRequest {
        name?: string
        isOrganic?: boolean
        phone?: string
        address?: string
        obligo?: number
    }

    export interface UpdateUserRequest {
        email?: string
        phoneNumber?: string
        officeId?: number
        password?: string
    }

    export interface UpdateUserResponse {
        id: number
        email: string
        phoneNumber: string
        officeId: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.CreateAdmin = this.CreateAdmin.bind(this)
            this.CreateAgent = this.CreateAgent.bind(this)
            this.CreateContact = this.CreateContact.bind(this)
            this.CreateOffice = this.CreateOffice.bind(this)
            this.CreateOrganization = this.CreateOrganization.bind(this)
            this.DeleteContact = this.DeleteContact.bind(this)
            this.ListAdmins = this.ListAdmins.bind(this)
            this.ListAgents = this.ListAgents.bind(this)
            this.ListContacts = this.ListContacts.bind(this)
            this.ListOffices = this.ListOffices.bind(this)
            this.ListOrganizations = this.ListOrganizations.bind(this)
            this.Login = this.Login.bind(this)
            this.LoginAsAgent = this.LoginAsAgent.bind(this)
            this.LoginBackToAdmin = this.LoginBackToAdmin.bind(this)
            this.RefreshTokens = this.RefreshTokens.bind(this)
            this.TempCustomerTagUsage = this.TempCustomerTagUsage.bind(this)
            this.UpdateContact = this.UpdateContact.bind(this)
            this.UpdateOffice = this.UpdateOffice.bind(this)
            this.UpdateOrganization = this.UpdateOrganization.bind(this)
            this.UpdateUser = this.UpdateUser.bind(this)
        }

        /**
         * CreateAdmin creates a new admin user.
         */
        public async CreateAdmin(params: CreateAdminRequest): Promise<CreateAdminResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admins`, JSON.stringify(params))
            return await resp.json() as CreateAdminResponse
        }

        /**
         * CreateAgent creates a new agent user.
         */
        public async CreateAgent(params: CreateAgentRequest): Promise<CreateAgentResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/agents`, JSON.stringify(params))
            return await resp.json() as CreateAgentResponse
        }

        /**
         * CreateContact creates a new contact.
         */
        public async CreateContact(params: CreateContactRequest): Promise<ContactResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/contacts`, JSON.stringify(params))
            return await resp.json() as ContactResponse
        }

        /**
         * CreateOffice creates a new office.
         */
        public async CreateOffice(params: CreateOfficeRequest): Promise<OfficeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/offices`, JSON.stringify(params))
            return await resp.json() as OfficeResponse
        }

        /**
         * CreateOrganization creates a new organization.
         */
        public async CreateOrganization(params: CreateOrganizationRequest): Promise<OrganizationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/organizations`, JSON.stringify(params))
            return await resp.json() as OrganizationResponse
        }

        /**
         * DeleteContact deletes a contact by its ID.
         */
        public async DeleteContact(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/contacts/${encodeURIComponent(id)}`)
        }

        /**
         * ListAdmins returns all admin users.
         */
        public async ListAdmins(): Promise<ListAdminsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admins`)
            return await resp.json() as ListAdminsResponse
        }

        /**
         * ListAgents lists agents with optional filtering and pagination.
         */
        public async ListAgents(params: ListAgentsRequest): Promise<ListAgentsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                officeId: String(params.OfficeID),
                orgId:    String(params.OrgID),
                page:     String(params.Page),
                search:   params.Search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/agents`, undefined, {query})
            return await resp.json() as ListAgentsResponse
        }

        /**
         * ListContacts lists contacts with optional filtering and pagination.
         */
        public async ListContacts(params: ListContactsRequest): Promise<ListContactsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                officeId: String(params.OfficeID),
                orgId:    String(params.OrgID),
                page:     String(params.Page),
                search:   params.Search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/contacts`, undefined, {query})
            return await resp.json() as ListContactsResponse
        }

        /**
         * ListOffices lists offices with optional filtering and pagination.
         */
        public async ListOffices(params: ListOfficesRequest): Promise<ListOfficesResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                orgId:  String(params.OrgID),
                page:   String(params.Page),
                search: params.Search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/offices`, undefined, {query})
            return await resp.json() as ListOfficesResponse
        }

        /**
         * ListOrganizations lists organizations with optional search and pagination.
         */
        public async ListOrganizations(params: ListOrganizationsRequest): Promise<ListOrganizationsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                isOrganic: params.IsOrganic,
                page:      String(params.Page),
                search:    params.Search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/organizations`, undefined, {query})
            return await resp.json() as ListOrganizationsResponse
        }

        public async Login(params: LoginParams): Promise<LoginResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/login`, JSON.stringify(params))
            return await resp.json() as LoginResponse
        }

        public async LoginAsAgent(params: LoginAsAgentParams): Promise<LoginResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/login/as-agent`, JSON.stringify(params))
            return await resp.json() as LoginResponse
        }

        public async LoginBackToAdmin(): Promise<LoginResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/login/back-to-admin`)
            return await resp.json() as LoginResponse
        }

        public async RefreshTokens(params: RefreshTokensParams): Promise<LoginResponse> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.RefreshToken,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/refresh`, undefined, {headers})
            return await resp.json() as LoginResponse
        }

        public async TempCustomerTagUsage(): Promise<TempAgentTagUsageResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/temp-customer-tag-usage`)
            return await resp.json() as TempAgentTagUsageResponse
        }

        /**
         * UpdateContact updates an existing contact.
         */
        public async UpdateContact(id: number, params: UpdateContactRequest): Promise<ContactResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/contacts/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as ContactResponse
        }

        /**
         * UpdateOffice updates an existing office.
         */
        public async UpdateOffice(id: number, params: UpdateOfficeRequest): Promise<OfficeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/offices/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as OfficeResponse
        }

        /**
         * UpdateOrganization updates an existing organization.
         */
        public async UpdateOrganization(id: number, params: UpdateOrganizationRequest): Promise<OrganizationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/organizations/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as OrganizationResponse
        }

        /**
         * UpdateUser updates an existing user.
         */
        public async UpdateUser(id: number, params: UpdateUserRequest): Promise<UpdateUserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/users/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as UpdateUserResponse
        }
    }
}

export namespace booking {
    /**
     * AvailableVehicle represents a vehicle that is available for rent, including details about the car, the rental plans, add-ons, location details, and price details.
     */
    export interface AvailableVehicle {
        id: number
        broker: broker.Name
        carDetails: broker.CarDetails
        plans: Plan[]
        addOns: broker.AddOn[]
        locationDetails: broker.LocationDetails
        priceDetails: broker.PriceDetails
        signals?: BookingSignals
    }

    /**
     * BookResponse represents the response returned after a successful booking, including the booking reference number and any relevant details.
     */
    export interface BookRequest {
        snapshotId: number
        rateQualifier: string
        supplierCode: string
        planId: string
        includeERP: boolean
        selectedAddOns: broker.SelectAddOn[]
        driverTitle: string
        driverFirstName: string
        driverLastName: string
        flightNumber?: string
    }

    export interface BookResponse {
        reservationId: number
    }

    /**
     * BookingSignals holds UI-facing demand and inventory indicators for a vehicle card.
     */
    export interface BookingSignals {
        liveViewers: number
        remainingCount: number
        tags: string[]
    }

    export interface BrokerTranslationRow {
        id: number
        "source_text": string
        "target_text": string
        status: string
        "confidence_score": number
    }

    export interface BulkToggleLocationsRequest {
        ids: number[]
        enabled: boolean
    }

    export interface CouponResponse {
        id: number
        name: string
        code: string
        discount: number
        isEnabled: boolean
    }

    export interface CreateCouponRequest {
        name: string
        code: string
        discount: number
        isEnabled: boolean
    }

    export interface CreateCurrencyRequest {
        currencyCode: string
        currencyISOName: string
        rate: number
    }

    export interface CreateHertzMarkupRateRequest {
        country: string
        brand: string
        pickupDateFrom: string
        pickupDateTo: string
        carGroup: string
        numOfRentalDaysFrom: number
        numOfRentalDaysTo: number
        markUpGross: number
        markUpNet: number
    }

    export interface CurrencyResponse {
        id: number
        currencyCode: string
        currencyISOName: string
        rate: number
    }

    /**
     * GetPendingTranslationsRequest is the request for GetPendingTranslations endpoint
     */
    export interface GetPendingTranslationsRequest {
        Token: string
    }

    /**
     * GetPendingTranslationsResponse is the response for GetPendingTranslations endpoint
     */
    export interface GetPendingTranslationsResponse {
        translations: db.BrokerTranslation[]
    }

    export interface HertzMarkupRateResponse {
        id: number
        country: string
        brand: string
        pickupDateFrom: string
        pickupDateTo: string
        carGroup: string
        numOfRentalDaysFrom: number
        numOfRentalDaysTo: number
        markUpGross: number
        markUpNet: number
    }

    /**
     * InsertLocationParams defines the parameters for inserting a single location.
     */
    export interface InsertLocationParams {
        broker: broker.Name
        id: string
        name: string
        country: string
        "country_code": string
        city: string
        iata: string
    }

    export interface ListBrokerTranslationsRequest {
        Page: number
        Search: string
        Status: string
        SortDir: string
    }

    export interface ListBrokerTranslationsResponse {
        translations: BrokerTranslationRow[]
        total: number
    }

    export interface ListCouponsResponse {
        coupons: CouponResponse[]
    }

    export interface ListCurrenciesResponse {
        currencies: CurrencyResponse[]
    }

    export interface ListHertzMarkupRatesRequest {
        Country: string
        Brand: string
        CarGroup: string
        SortBy: string
        SortDir: string
        Page: number
    }

    export interface ListHertzMarkupRatesResponse {
        rates: HertzMarkupRateResponse[]
        total: number
    }

    export interface ListLocationsRequest {
        CountryCode: string
        Broker: string
        Name: string
        Iata: string
        Enabled: string
        Page: number
    }

    export interface ListLocationsResponse {
        locations: LocationRow[]
        total: number
    }

    export interface LocationResult {
        id: number
        name: string
        country: string
        countryCode: string
        city: string
        iata: string
    }

    export interface LocationRow {
        id: number
        name: string
        "country_code": string
        country: string
        city: string
        iata: string
        enabled: boolean
        "broker_location_id": string
    }

    /**
     * Plan represents a rental plan, including its ID, name, description, full price, discount, and other pricing details.
     */
    export interface Plan {
        planId: number
        planName: string
        fullPrice: number
        discount: number
        price: number
        erpPrice: number
        planInclusions: string[]
        info: string[]
        rateQualifier: string
        supplierCode: string
    }

    /**
     * SearchAvailabilityRequest represents the request for searching availability of vehicles.
     */
    export interface SearchAvailabilityRequest {
        PickupLocationID: number
        DropoffLocationID: number
        PickupTime: string
        DropoffTime: string
        PickupDate: string
        DropoffDate: string
        DriverAge: number
        CouponCode: string
    }

    /**
     * SearchAvailabilityResponse represents the response for searching availability of vehicles.
     */
    export interface SearchAvailabilityResponse {
        snapshotId: number
        pickupLocationName: string
        dropoffLocationName: string
        daysCount: number
        availableVehicles: AvailableVehicle[]
    }

    export interface SearchLocationParams {
        Search: string
    }

    export interface SearchLocationResponse {
        locations: LocationResult[]
    }

    export interface ToggleLocationRequest {
        enabled: boolean
    }

    /**
     * TranslateTranslationRequest is the request for TranslateTranslation endpoint
     */
    export interface TranslateTranslationRequest {
        Token: string
        id: number
        targetText: string
        confidence: number
    }

    export interface UpdateBrokerTranslationRequest {
        "target_text": string
    }

    export interface UpdateCouponRequest {
        name?: string
        code?: string
        discount?: number
        isEnabled?: boolean
    }

    export interface UpdateCurrencyRequest {
        currencyCode?: string
        currencyISOName?: string
        rate?: number
    }

    export interface UpdateHertzMarkupRateRequest {
        country: string
        brand: string
        pickupDateFrom: string
        pickupDateTo: string
        carGroup: string
        numOfRentalDaysFrom: number
        numOfRentalDaysTo: number
        markUpGross: number
        markUpNet: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.Book = this.Book.bind(this)
            this.BulkToggleLocations = this.BulkToggleLocations.bind(this)
            this.CreateCoupon = this.CreateCoupon.bind(this)
            this.CreateCurrency = this.CreateCurrency.bind(this)
            this.CreateHertzMarkupRate = this.CreateHertzMarkupRate.bind(this)
            this.DeleteBrokerTranslation = this.DeleteBrokerTranslation.bind(this)
            this.DeleteCoupon = this.DeleteCoupon.bind(this)
            this.DeleteCurrency = this.DeleteCurrency.bind(this)
            this.DeleteHertzMarkupRate = this.DeleteHertzMarkupRate.bind(this)
            this.DeleteLocation = this.DeleteLocation.bind(this)
            this.GetPendingTranslations = this.GetPendingTranslations.bind(this)
            this.InsertFlexLocations = this.InsertFlexLocations.bind(this)
            this.InsertHertzLocations = this.InsertHertzLocations.bind(this)
            this.InsertLocation = this.InsertLocation.bind(this)
            this.ListBrokerTranslations = this.ListBrokerTranslations.bind(this)
            this.ListCoupons = this.ListCoupons.bind(this)
            this.ListCurrencies = this.ListCurrencies.bind(this)
            this.ListHertzMarkupRates = this.ListHertzMarkupRates.bind(this)
            this.ListLocations = this.ListLocations.bind(this)
            this.SearchAvailability = this.SearchAvailability.bind(this)
            this.SearchLocations = this.SearchLocations.bind(this)
            this.ToggleLocation = this.ToggleLocation.bind(this)
            this.TranslateTranslation = this.TranslateTranslation.bind(this)
            this.UpdateBrokerTranslation = this.UpdateBrokerTranslation.bind(this)
            this.UpdateCoupon = this.UpdateCoupon.bind(this)
            this.UpdateCurrency = this.UpdateCurrency.bind(this)
            this.UpdateHertzMarkupRate = this.UpdateHertzMarkupRate.bind(this)
            this.VerifyBrokerTranslation = this.VerifyBrokerTranslation.bind(this)
        }

        public async Book(params: BookRequest): Promise<BookResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/booking`, JSON.stringify(params))
            return await resp.json() as BookResponse
        }

        public async BulkToggleLocations(params: BulkToggleLocationsRequest): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/location-bulk-toggle`, JSON.stringify(params))
        }

        /**
         * CreateCoupon creates a new coupon.
         */
        public async CreateCoupon(params: CreateCouponRequest): Promise<CouponResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/coupons`, JSON.stringify(params))
            return await resp.json() as CouponResponse
        }

        /**
         * CreateCurrency creates a new currency.
         */
        public async CreateCurrency(params: CreateCurrencyRequest): Promise<CurrencyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/currencies`, JSON.stringify(params))
            return await resp.json() as CurrencyResponse
        }

        /**
         * CreateHertzMarkupRate creates a new hertz markup rate.
         */
        public async CreateHertzMarkupRate(params: CreateHertzMarkupRateRequest): Promise<HertzMarkupRateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/hertz-markup-rates`, JSON.stringify(params))
            return await resp.json() as HertzMarkupRateResponse
        }

        /**
         * DeleteBrokerTranslation deletes a broker translation by ID.
         */
        public async DeleteBrokerTranslation(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/broker-translations/${encodeURIComponent(id)}`)
        }

        /**
         * DeleteCoupon deletes a coupon by its ID.
         */
        public async DeleteCoupon(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/coupons/${encodeURIComponent(id)}`)
        }

        /**
         * DeleteCurrency deletes a currency by its ID.
         */
        public async DeleteCurrency(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/currencies/${encodeURIComponent(id)}`)
        }

        /**
         * DeleteHertzMarkupRate deletes a hertz markup rate by its ID.
         */
        public async DeleteHertzMarkupRate(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/hertz-markup-rates/${encodeURIComponent(id)}`)
        }

        /**
         * DeleteLocation deletes a location broker code by its ID.
         * If no other broker codes reference the same location, the location is also deleted.
         */
        public async DeleteLocation(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/locations/${encodeURIComponent(id)}`)
        }

        /**
         * GetPendingTranslations returns the list of pending translations for brokers. It requires a valid translation token in the header.
         */
        public async GetPendingTranslations(params: GetPendingTranslationsRequest): Promise<GetPendingTranslationsResponse> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "x-translation-token": params.Token,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/booking/translations/pending`, undefined, {headers})
            return await resp.json() as GetPendingTranslationsResponse
        }

        /**
         * InsertFlexLocations handles the HTTP request to insert Flex locations.
         */
        public async InsertFlexLocations(): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/locations/flex`)
        }

        /**
         * InsertHertzLocations handles the HTTP request to insert Hertz locations.
         */
        public async InsertHertzLocations(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/locations/hertz`, body, options)
        }

        /**
         * InsertLocations handles the HTTP request to insert a single location
         */
        public async InsertLocation(params: InsertLocationParams): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/locations`, JSON.stringify(params))
        }

        public async ListBrokerTranslations(params: ListBrokerTranslationsRequest): Promise<ListBrokerTranslationsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                page:    String(params.Page),
                search:  params.Search,
                sortDir: params.SortDir,
                status:  params.Status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/broker-translations`, undefined, {query})
            return await resp.json() as ListBrokerTranslationsResponse
        }

        /**
         * ListCoupons lists all coupons.
         */
        public async ListCoupons(): Promise<ListCouponsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/coupons`)
            return await resp.json() as ListCouponsResponse
        }

        /**
         * ListCurrencies lists all currencies.
         */
        public async ListCurrencies(): Promise<ListCurrenciesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/currencies`)
            return await resp.json() as ListCurrenciesResponse
        }

        /**
         * ListHertzMarkupRates lists hertz markup rates with pagination, optional filtering, and sorting.
         */
        public async ListHertzMarkupRates(params: ListHertzMarkupRatesRequest): Promise<ListHertzMarkupRatesResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                brand:    params.Brand,
                carGroup: params.CarGroup,
                country:  params.Country,
                page:     String(params.Page),
                sortBy:   params.SortBy,
                sortDir:  params.SortDir,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/hertz-markup-rates`, undefined, {query})
            return await resp.json() as ListHertzMarkupRatesResponse
        }

        public async ListLocations(params: ListLocationsRequest): Promise<ListLocationsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                broker:         params.Broker,
                "country_code": params.CountryCode,
                enabled:        params.Enabled,
                iata:           params.Iata,
                name:           params.Name,
                page:           String(params.Page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/locations`, undefined, {query})
            return await resp.json() as ListLocationsResponse
        }

        /**
         * SearchAvailability handles the http request for searching availability of vehicles.
         */
        public async SearchAvailability(params: SearchAvailabilityRequest): Promise<SearchAvailabilityResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                couponCode:        params.CouponCode,
                driverAge:         String(params.DriverAge),
                dropoffDate:       params.DropoffDate,
                dropoffLocationId: String(params.DropoffLocationID),
                dropoffTime:       params.DropoffTime,
                pickupDate:        params.PickupDate,
                pickupLocationId:  String(params.PickupLocationID),
                pickupTime:        params.PickupTime,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/booking/availability`, undefined, {query})
            return await resp.json() as SearchAvailabilityResponse
        }

        /**
         * SearchLocations searches for locations in the database that match the given search query
         */
        public async SearchLocations(params: SearchLocationParams): Promise<SearchLocationResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                search: params.Search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/locations/search`, undefined, {query})
            return await resp.json() as SearchLocationResponse
        }

        public async ToggleLocation(id: number, params: ToggleLocationRequest): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/locations/${encodeURIComponent(id)}`, JSON.stringify(params))
        }

        /**
         * TranslateTranslation translates a pending translation. It requires a valid translation token in the header.
         */
        public async TranslateTranslation(params: TranslateTranslationRequest): Promise<void> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "x-translation-token": params.Token,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                confidence: params.confidence,
                id:         params.id,
                targetText: params.targetText,
            }

            await this.baseClient.callTypedAPI("PATCH", `/booking/translations/translate`, JSON.stringify(body), {headers})
        }

        /**
         * UpdateBrokerTranslation updates a broker translation target text by ID.
         */
        public async UpdateBrokerTranslation(id: number, params: UpdateBrokerTranslationRequest): Promise<void> {
            await this.baseClient.callTypedAPI("PUT", `/broker-translations/${encodeURIComponent(id)}`, JSON.stringify(params))
        }

        /**
         * UpdateCoupon updates an existing coupon.
         */
        public async UpdateCoupon(id: number, params: UpdateCouponRequest): Promise<CouponResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/coupons/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as CouponResponse
        }

        /**
         * UpdateCurrency updates an existing currency.
         */
        public async UpdateCurrency(id: number, params: UpdateCurrencyRequest): Promise<CurrencyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/currencies/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as CurrencyResponse
        }

        /**
         * UpdateHertzMarkupRate updates an existing hertz markup rate.
         */
        public async UpdateHertzMarkupRate(id: number, params: UpdateHertzMarkupRateRequest): Promise<HertzMarkupRateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/hertz-markup-rates/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as HertzMarkupRateResponse
        }

        /**
         * VerifyBrokerTranslation marks a broker translation as verified by ID.
         */
        public async VerifyBrokerTranslation(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/broker-translations/${encodeURIComponent(id)}/verify`)
        }
    }
}

export namespace reservation {
    /**
     * ApplyVoucherRequest is the request payload type for the apply voucher EP
     */
    export interface ApplyVoucherRequest {
        voucher: string
    }

    export interface GetReservationResponse {
        id: number
        brokerReservationId: string
        status: string
        carDetails: broker.CarDetails
        planInclusions: string[]
        currencyCode: string
        currencyRate: number
        priceBefDesc: number
        discountAmount: number
        erpPrice: number
        totalPrice: number
        pickupLocationName: string
        dropoffLocationName: string
        pickupDate: string
        returnDate: string
        pickupTime: string
        dropoffTime: string
        rentalDays: number
        driverTitle: string
        driverFirstName: string
        driverLastName: string
        driverAge: number
        voucher?: string
        voucheredAt?: string
        createdAt: string
    }

    export interface ListReservationsRequest {
        Page: number
    }

    export interface ListReservationsResponse {
        reservations: ReservationSummary[]
    }

    export interface ReservationSummary {
        id: number
        brokerReservationId: string
        createdAt: string
        countryCode: string
        pickupDate: string
        driverTitle: string
        driverFirstName: string
        driverLastName: string
        status: string
        totalPrice: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.ApplyVoucher = this.ApplyVoucher.bind(this)
            this.GetReservation = this.GetReservation.bind(this)
            this.ListReservations = this.ListReservations.bind(this)
        }

        /**
         * ApplyVoucher is the EP for applying a voucher on an agent order
         */
        public async ApplyVoucher(id: number, params: ApplyVoucherRequest): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/reservations/${encodeURIComponent(id)}/voucher`, JSON.stringify(params))
        }

        public async GetReservation(id: number): Promise<GetReservationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reservations/${encodeURIComponent(id)}`)
            return await resp.json() as GetReservationResponse
        }

        public async ListReservations(params: ListReservationsRequest): Promise<ListReservationsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                page: String(params.Page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reservations`, undefined, {query})
            return await resp.json() as ListReservationsResponse
        }
    }
}

export namespace broker {
    /**
     * AddOn represents an additional service or product that can be added to a rental, including its ID, name, price, allowed quantity, and rental period.
     */
    export interface AddOn {
        id: number
        name: string
        price: number
        currency: string
        allowedQuantity: number
        period: string
    }

    /**
     * CarDetails represents the details of a car available for rent, including its ID, model, car group, image URL, supplier, car type, car size, ACRISS code, whether it has AC and auto gear, and the number of seats, bags, and doors.
     */
    export interface CarDetails {
        model: string
        carGroup: string
        imageUrl: string
        supplierName: string
        carType: string
        acriss: string
        hasAC: boolean
        isAutoGear: boolean
        isElectric: boolean
        seats: number
        bags: number
        doors: number
    }

    /**
     * LocationDetails represents the details of a rental location, including delivery collection, pickup and return branch addresses and phone numbers, location type, and pickup notes.
     */
    export interface LocationDetails {
        deliveryCollection: string
        pickupBranchAddress: string
        returnBranchAddress: string
        pickupBranchPhone: string
        returnBranchPhone: string
        pickupNotes: string
        locationType: string
    }

    /**
     * Name represents the name of a broker, such as "flex" or "hertz".
     */
    export type Name = string

    /**
     * PriceDetails represents the pricing details of a rental, including the currency, drop charge, and drop charge currency.
     */
    export interface PriceDetails {
        currency: string
        dropCharge: number
        dropChargeCurrency: string
    }

    /**
     * SelectAddOn represents an add-on selected by the user during the booking process, including its ID and quantity.
     */
    export interface SelectAddOn {
        id: number
        quantity: number
    }
}

export namespace db {
    export interface BrokerTranslation {
        ID: number
        SourceText: string
        TargetText: string
        Status: BrokerTranslationStatus
        ConfidenceScore: number
        CreatedAt: pgtype.Timestamptz
        UpdatedAt: pgtype.Timestamptz
    }

    export type BrokerTranslationStatus = string

    export type UserRole = string
}

export namespace pgtype {
    export type InfinityModifier = number

    /**
     * Timestamptz represents the PostgreSQL timestamptz type.
     */
    export interface Timestamptz {
        Time: string
        InfinityModifier: InfinityModifier
        Valid: boolean
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | string
  | Promise<string | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "global-rental-2m42-Generated-TS-Client (Encore/v1.54.0)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: string | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = {};
            data.headers["Authorization"] = "Bearer " + authData;

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
